### PR TITLE
Fix rna upload with dna case

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b fix-rna-upload-with-dna-case
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### RNA case, 👍 
```
Called undefined __fields__ on HousekeeperAPI, please wrap
----------------- UPLOAD -----------------
----------------- UPLOAD RNA TO SCOUT -----------------------
----------------- UPLOAD RNA ALIGNMENT FILE TO SCOUT -----------------------
Uploading RNA alignment CRAM file for sample 17119-I-1A to case causalmite
Uploading RNA alignment CRAM file for sample 17119-I-1A to case viablesparrow
Uploaded RNA alignment CRAM file for sample 17119-I-1A in case causalmite
Uploaded RNA alignment CRAM file for sample 17119-I-1A in case viablesparrow
Upload RNA alignment CRAM file finished!
----------------- UPLOAD MULTIQC TO SCOUT -----------------------
Finding DNA cases related to RNA case teachingladybird
Running upload of report to DNA case viablesparrow.
Uploading multiqc_rna report to Scout for case viablesparrow.
Would have uploaded multiqc_rna report.
Running upload of report to DNA case causalmite.
Uploading multiqc_rna report to Scout for case causalmite.
Would have uploaded multiqc_rna report.
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Clinical fusion report teachingladybird/2024-07-27/teachingladybird_report.selected.pdf found
Uploading Clinical fusion report to Scout for case viablesparrow.
Uploading Clinical fusion report to Scout for case causalmite.
Upload Clinical fusion report finished!
----------------- UPLOAD RNA JUNCTIONS TO SCOUT -----------------------
Uploading splice junctions bed file for sample 17119-I-1A in case causalmite in Scout.
Uploading splice junctions bed file for sample 17119-I-1A in case viablesparrow in Scout.
Uploaded splice junctions bed file for sample 17119-I-1A in case causalmite.
Uploaded splice junctions bed file for sample 17119-I-1A in case viablesparrow.
Upload splice junctions bed file finished!
Uploading RNA coverage bigwig file for sample 17119-I-1A in case causalmite in Scout.
Uploading RNA coverage bigwig file for sample 17119-I-1A in case viablesparrow in Scout.
Uploaded bigwig coverage file for sample 17119-I-1A in case causalmite.
Uploaded bigwig coverage file for sample 17119-I-1A in case viablesparrow.
```

DNA case, 👍 
```
cg.exc.CaseNotFoundError
[henrik.stranneheim@hasta:~] [S_base] $ cg upload rna-to-scout justhusky --dry-run
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
----------------- UPLOAD -----------------
----------------- UPLOAD RNA TO SCOUT -----------------------
justhusky has non-RNA samples - aborting.
Aborted!

**Review by ChrOertlin — APPROVED** [review]
Would be nice if we could get around invoking other CLI commands within CLI commands. Otherwise good!

**Comment by henrikstranneheim** [comment]
> Would be nice if we could get around invoking other CLI commands within CLI commands. Otherwise good!

I agree with you. However, we need to agree on a good replacement pattern before making that change.

**Comment by henrikstranneheim** [comment]
Deployed to prod:
```
Log deploy... done.
cg, version 62.0.56

**Pull request merged**
