### PR TITLE
adding clinical delivery to mip-dna upload

### PR DESCRIPTION
**Pull request by GustavLagneborgScilifelab**
### Added

- Automatic delivery to Caesar for MIP-DNA

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b automatic-clinical-delivery-mip -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by GustavLagneborgScilifelab** [comment]
#### Test 1 - upload case simplemonkey with the following command: `cg upload -f simplemonkey -r`:
Screenshot 2022-10-31 at 15 02 06

The outcome is as expected, it delivers the file and then creates a rsync script, and submits the sbatch job

**Comment by GustavLagneborgScilifelab** [comment]
#### Test 2 - upload case merry bee that shouldn't be uploaded to caesar with the following command: `cg upload -f merrybee -r`:
Screenshot 2022-10-31 at 15 17 03

The outcome is as expected, it does not deliver anything to caesar and continues with the rest of the upload tasks.

**Comment by GustavLagneborgScilifelab** [comment]
#### Test 3 - upload simplemonkey again when the inbox folder is already created:
Screenshot 2022-10-31 at 15 16 09

The outcome is that it checks if the files to deliver are there and then rsyncs it. This is the same outcome as `CG deliver rsync` would have produced

**Review by henrikstranneheim — APPROVED** [review]
👍! Nice

**Comment by GustavLagneborgScilifelab** [comment]
Screenshot 2022-11-02 at 11 04 18

**Pull request merged**
