### PR TITLE
change/required fields for delivery report

### PR DESCRIPTION
**Pull request by ivadym**
## Description

Allow for missing values `bait set` if the application tag starts with WGS.

### Changed

- Removed bait set from required fields for WGS samples

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@ivadym Wait a bit with this one as we need to figure out if the capture kit info in StatusDB is actually used properly. @patrikgrenfeldt?

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Comment by patrikgrenfeldt** [comment]
> @ivadym Wait a bit with this one as we need to figure out if the capture kit info in StatusDB is actually used properly. @patrikgrenfeldt?

I think this PR is useful if the business rule is sound @henrikstranneheim ?

I think we might fetch the value from LIMS instead of statusdb if that sounds correct with you @henrikstranneheim ?

**Comment by ivadym** [comment]
Tests:

---

- Master branch (`cg generate mip-dna delivery-report epicsawfly -d`):

Screen Shot 2022-04-07 at 16 57 48

- This branch (`cg generate mip-dna delivery-report epicsawfly -d`):

Screen Shot 2022-04-07 at 16 59 57

---

- Report upload (`cg generate mip-dna delivery-report epicsawfly -f`):

Screen Shot 2022-04-07 at 17 31 27

- Report generated:
[F0045110_2022-04-07_scout_delivery.pdf](https://github.com/Clinical-Genomics/cg/files/8444435/F0045110_2022-04-07_scout_delivery.pdf)

**Comment by ivadym** [comment]
Screen Shot 2022-04-07 at 18 12 51

**Pull request merged**
