### PR TITLE
Fix code smell by refactoring add_decompressed_fastq_files_to_housekeeper

### PR DESCRIPTION
**Pull request by islean**
## Description

In #2378 there was a code smell left that this PR handles. It reduces the complexity in `add_decompressed_fastq_files_to_housekeeper`.

### Fixed

- `add_decompressed_fastq_files_to_housekeeper` is split into smaller methods.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b fix-code-smell -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
This is beautiful 🌷 Maybe add some tests too 👀

**Comment by islean** [comment]
> This is beautiful 🌷 Maybe add some tests too 👀

I definitely could but this is essentially some cutting and pasting work 😅 Does not seem to be any unit tests for this functionality previously though.

**Comment by diitaz93** [comment]
> > This is beautiful 🌷 Maybe add some tests too 👀
> 
> I definitely could but this is essentially some cutting and pasting work 😅 Does not seem to be any unit tests for this functionality previously though.

Yes, that is what I meant. I think we should try to add tests to functions we touch if they don't have any. But if you feel it is out of scope feel free to disregard

**Comment by islean** [comment]
@diitaz93 Added some tests now!

**Review by diitaz93 — APPROVED** [review]
Good job with the tests 👍

**Comment by islean** [comment]
Test performed successfully:

Screenshot 2023-11-01 at 10 14 31

**Comment by islean** [comment]
Tests performed successfully:

**Comment by islean** [comment]
Tests performed successfully:

Screenshot 2023-11-01 at 10 14 31

**Comment by islean** [comment]
Deployed to production: 

```
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 51.10.4
1d [isak.ohlsson@hasta:~] [P_base] 1m13s $ 
```

**Pull request merged**
