### PR TITLE
making %kth requiered

### PR DESCRIPTION
**Pull request by mayabrandi**
We have a problem that the %kth field in the application tag table in the database, often is empty. Valtteri has now filled in the field for all tags that are not archived. The archived tags will not be touched or used in the future, so I suppose we can ignore those? Can we make the field not nullable in the database as soon as this PR is approved, or is there anything else that could be affected by this that needs to be fixed first? @patrikgrenfeldt

Script was added to update the database. It has been tested on cg-stage

**How to prepare for test**:
- [ ] install on stage

**How to test**:
- [ ] go to [the admin view on stage ](https://clinical-api-stage.scilifelab.se/admin/) and try to update a application tag by deleting the %kth field and save. That should not be possible.
- [ ] run the sql code in make_percent_kth_not_null.sql on cg-stage.  It should convert Nones to -1. 

**Expected test outcome**:

Skärmavbild 2020-01-30 kl  13 59 57

**Review:**
- [x] code approved by @adrosenbaum 
- [x] tests executed by @mayabrandi 30/1
- [ ] "Merge and deploy" approved by

This is minor **version bump** because it is extending a function definition which in turn causes 25 files to change.

### CODE REVIEW

**Comment by mayabrandi** [comment]
Tested the sql script on cg-stage

Lots of tags have %kth=NULL:


Skärmavbild 2020-01-30 kl  14 17 53

Running the lines in the sql code:

Skärmavbild 2020-01-30 kl  14 18 20



Skärmavbild 2020-01-30 kl  14 18 45


The nulls have now changed to -1:


Skärmavbild 2020-01-30 kl  14 19 01

The "Tillåt NULL" is now unchecked:

Skärmavbild 2020-01-30 kl  14 19 33

**Comment by mayabrandi** [comment]
Okej @adrosenbaum Just some code foramting complains from black now. I suggest we run black after you have gon through the PR if @patrikgrenfeldt is ok with that.

**Comment by ingkebil** [comment]
Sorry for flying in here. I would change the version bump to minor as you're extending a function definition which in turn causes 25 (!) files to change. I would consider that extending the functionality, which is a minor.

Otherwise: well done. Kuddos on also testing the SQL script.

**Comment by mayabrandi** [comment]
I see. Okej I will do that. Thanks for feedback.

**Comment by patrikgrenfeldt** [comment]
deploy

**Pull request merged**
