### PR TITLE
Autozygous tag name and content in scout config

### PR DESCRIPTION
**Pull request by dnil**
This PR adds/fixes some issues with Chromograph image loading to Scout

The Chromograph image loading seems broken. No images appear although MIP runs chromograph and Scout can display images. Also, code for handling this is present in cg, but seems to have had some bit rot since December.

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh chromograph_tag_revert`

### How to test
- [x] do upload a recent MIP case to scout-stage (e.g. deepbeagle, but note that the currently loaded version has manually added chromograph images.. 😸)
- [x] notice how no chromograph images are displayed for the case
- [x] apply patch
- [x] re-upload the case
- [x] notice how the case now has chromograph images available on the case page

### Expected test outcome
- [x] check that 
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MR
- [x] tests executed by DN, MR
- [ ] "Merge and deploy" approved by DN, MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by Mropat** [comment]
scout load config

```
owner: cust002
family: keenviper
family_name: F0013248-3
gene_panels:
   -  BRAIN
   -  Cardiology
   -  CTD
   -  ENDO
   -  EP
   -  IBMFS
   -  IEM
   -  IF
   -  NEURODEG
   -  NMD
   -  mcarta
   -  MHT
   -  MIT
   -  MOVE
   -  mtDNA
   -  PEDHEP
   -  PID
   -  PIDCAD
   -  OMIM-AUTO
   -  SKD
default_gene_panels:
   -  NMD
human_genome_build: '37'
rank_model_version: '1.31'
rank_score_threshold: 5
sv_rank_model_version: '1.8'
analysis_date: 2021-02-02 13:04:15
samples:
   -  sample_id: ACC3218A1
      father: '0'
      mother: '0'
      sample_name: 2017-20794-02
      sex: male
      phenotype: affected
      alignment_path: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/ACC3218A1_lanes_6666_sorted_md_brecal.cram
      analysis_type: wgs
      tissue_type: blood
      mt_bam: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/ACC3218A1_lanes_6666_sorted_md_brecal_subsample_MT.bam
      chromograph_images:
          autozygous: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb_rhocall_vt_af_rhoviz.ACC3218A1.autozyg_
          coverage: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/ACC3218A1_lanes_6666_sorted_md_brecal_tcov_
      vcf2cytosure: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_cyto.ACC3218A1.cgh
multiqc: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/multiqc_report.html
track: rare
smn_tsv: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_smn.tsv
vcf_snv: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb_rhocall_vt_af_frqf_cadd_vep_parsed_ranked.selected.vcf.gz
vcf_sv: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_comb_ann_vep_parsed_ranked.selected.vcf.gz
vcf_str: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_exphun.vcf.gz
vcf_snv_research: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb_rhocall_vt_af_frqf_cadd_vep_parsed_ranked.vcf.gz
vcf_sv_research: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_comb_ann_vep_parsed_ranked.vcf.gz
peddy_ped: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb.peddy.ped
peddy_sex: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb.sex_check.csv
peddy_check: /home/proj/stage/housekeeper-bundles/keenviper/2021-02-01/keenviper_gatkcomb.ped_check.csv
Would save file to /home/proj/stage/rare-disease/cases/keenviper/scout_load.yaml

```

**Comment by dnil** [comment]
Thank you! You know you didn't have to run that - I was just waiting for cg-stage and myself to be available at the same time.

**Comment by Mropat** [comment]
No problem!!

**Comment by dnil** [comment]
Works in scout-stage
Screenshot 2021-02-05 at 16 19 39

**Review by Mropat — APPROVED** [review]
:fire_engine:

**Comment by Mropat** [comment]
Deployed on prod

```
Building wheels for collected packages: cg
  Running setup.py bdist_wheel for cg ... done
  Stored in directory: /home/maryia.ropart/tmp/pip-ephem-wheel-cache-vcp8fibu/wheels/5c/23/37/e3635140fad58f81760c6db5705a64683daf19230a7bb26dda
Successfully built cg
Installing collected packages: cg
  Found existing installation: cg 18.11.1
    Uninstalling cg-18.11.1:
      Successfully uninstalled cg-18.11.1
Successfully installed cg-18.11.2
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/proj/stage/nipt/cases/lovedkitten
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 18.11.2
housekeeper, version 3.2.0
demux, version 5.5.1
cglims, version 1.3.4

```

**Pull request merged**
