### PR TITLE
Last analysis 2 chanjo

### LINKED ISSUE #95: cg upload doesn't replace coverage data for re-runs
Whenever a re-run analysis is completed and cg upload uploads it to scout, then the coverage subroutine is invoked from cg upload without the (replace) -r True parameter, so the coverage data is not uploaded in chanjo db and chanjo-report uses old analyses when used to create coverage reports from scout. For more info check https://github.com/Clinical-Genomics/scout/issues/699.

### PR DESCRIPTION
**Pull request by northwestwitch**
This should fix #95 issue, hopefully. Once fixed the issue for the current and future re-runs we should compile a list of all re-runs with outdated coverage, I'm on it!

### CODE REVIEW

**Comment by ingkebil** [comment]
Have you discussed with @emiliaol and @emmser if this is needed?

**Comment by northwestwitch** [comment]
It was actually @emmser that noticed that the coverage data was not updated and opened the bug in scout. I've discussed about with @vwirta because I wasn't sure that this was a bug at all, but he confirmed that we want the coverage to be up to date with the analysis re-runs, so it's something we should fix.

**Comment by ingkebil** [comment]
Perfect! That wasn't clear from the context.

Nice catch and good solution!

**Comment by ingkebil** [comment]
Feel free to merge. We can sit together tomorrow and deploy together :)

**Comment by northwestwitch** [comment]
Ok, see you later! :)

**Comment by ingkebil** [comment]
@emmser @emiliaol @b4ckm4n This is now fixed and pushed into production.

Result: no need to run `cg upload coverage -r` anymore :)

**Pull request merged**
