### PR TITLE
Fix(TB): Restore argument name when adding analysis

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes argument name when adding analysis

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on production:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] add new analysis run
- [ ] login to trailblazer

### Expected test outcome
- [ ] check that pipeline is filled in
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [ ] tests executed by
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch
- [ ] Test and document test
- [ ] Inform to production

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test installation to stage: 
image
👍

**Comment by patrikgrenfeldt** [comment]
deployed to Hasta: 
image

**Comment by patrikgrenfeldt** [comment]
Tested on prod: 
image
👍

**Review by Mropat — COMMENTED** [review]
:+1:

**Pull request merged**
