### PR TITLE
Fix/queries delivery mip

### PR DESCRIPTION
**Pull request by Mropat**
Session conflicts were occurring since several different instances of the same API were found and used in the same context.
Fixes:
- Upload delivery report should now only happen for mip analyses
- Re-use the same API within all upload context
- Handle unspecified exceptions in order to keep the cron running when unexpected exception occurs for one case
- When linking file without data analysis set, warn about it and link file correctly

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [x] ssh to clinical-db (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta stage
- [x] do cg upload delivery-report civiltick

- [x] do cg workflow mip-dna link -c keenviper

### Expected test outcome
- [x] civiltick uploads correctly
- [x] keenviper linked successfully and user receives warning about data analysis missing

## Review
- [ ] code approved by
- [x] tests executed by MR
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by Mropat** [comment]
upload delivery report works!
image

**Comment by Mropat** [comment]
Linking log message
image

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
Screenshot 2020-09-10 at 13 00 01

**Pull request merged**
