### PR TITLE
Add multiQC report to rna delivery

### PR DESCRIPTION
**Pull request by moahaegglund**
### Added

- Include multiQC report in RNA delivery

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b add_qc_report_to_delivery -a
    ```

### How to test

- [x] Do `cg deliver analysis -d mip-rna -c tenderhen`

### Expected test outcome

- [x] Check that the multiQC report is included in the delivery.
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [x] Tests executed by @moahaegglund 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [X] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by moahaegglund** [comment]
MultiQC report included in delivery:
Screenshot 2022-10-31 at 11 53 32
Screenshot 2022-10-31 at 11 53 49

**Review by jemten — APPROVED** [review]
LGTM!

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by moahaegglund** [comment]
Deployed to production:
Screenshot 2022-11-01 at 08 37 23

Don't think the deployment to stage worked:
Screenshot 2022-11-01 at 08 33 38

**Pull request merged**
