### PR TITLE
Store commands

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...
- Adds new commands
`cg  store ticket`
`cg store sample`
`cg store case`
`cg store flowcell`

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta
- [x] do 
`cg  store ticket`
`cg store sample`
`cg store case`
`cg store flowcell`

### Expected test outcome
- [x] check that commands run successfully
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by MR
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes

### CODE REVIEW

**Comment by Mropat** [comment]
store case
image

store sample
image

store ticket
image

store flowcell
image

**Review by moonso — APPROVED** [review]
👍

**Comment by Mropat** [comment]
Deployed on stage
image

Deployed on prod
image

**Comment by Mropat** [comment]
@karlnyr @keyvanelhami @henningonsbring @emmser 

New commands to decompress and store fastq!

**Comment by moonso** [comment]
Would it not be possible to remove the store code from the workflow commands by this?

**Comment by Mropat** [comment]
@moonso store code in workflow commands is referring to storing analysis data, while this stores decompressed fastq files! 
But it is indeed a bit dangerous that they are named so similarly

**Comment by moonso** [comment]
Ok good. We should merge the store commands into one right. Should be something like
```
cg store fastq case
cg store fastq sample
cg store analysis case
.
.
.
```

**Pull request merged**
