### PR TITLE
Check for case name uniqueness before lims sample creation

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
This PR fixes the problem with cases being created in lims that can't be created in status-db due to lack of case name uniqueness

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for clinical-db):
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] do login to clinical-stage.scilifelab.se
- [x] create a mip-dna order
- [x] add a family that you know already exists in the database, but don't select it as an existing one in UI
- [x] submit

### Expected test outcome
- [x] check that the system gives an error in duplicate case name
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HO, MR
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to AL, ES, SC

### CODE REVIEW

**Review by henningonsbring — APPROVED** [review]

**Review by Mropat — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
Test result:
image
🆗 We got an error before the order was processed in LIMS

**Comment by patrikgrenfeldt** [comment]
Deployed to clinical-db:
image

**Comment by patrikgrenfeldt** [comment]
@saschaconradt @AnnaLeinfelt @emmser: This patch for Deviation "Not all samples were added to statusDB #66" has been deployed to production

**Comment by AnnaLeinfelt** [comment]
@patrikgrenfeldt Are you linking to the correct issue? Seems the link is for all _required changes to integrate beacon in cg 66_ and should have been for _Not all samples were added to statusDB 66_, https://github.com/Clinical-Genomics/Deviations/issues/66. I think this cross linking is sometimes tricky...

**Pull request merged**
