### PR TITLE
Allow scout loading of STR VCFs

### PR DESCRIPTION
**Pull request by barrystokman**
This PR adds scout loading of STR VCFs.
See also https://github.com/Clinical-Genomics/trailblazer/pull/57

\# TODO: fix unit tests

**How to test**:

##### Installation:
1. install on stage: 
 `/home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh str-vcf`
 `/home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh str-vcf`
1. activate stage: `us`

##### Preconditions:

1. Remove any existing analysis from status-db. It should be the only MIP7.1 analysis. Family/case_id is justhusky.
1. Remove any existing links from HK: `housekeeper delete bundle justhusky --yes`

#### Run tests

Test case 1: store analysis
1. run `cg store analysis /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky_config.yaml`

**Expected outcome**:
1. A new bundle and bundle version should be created for `justhusky`:
image
1. the STR VCF file should be linked in housekeeper:
image
1. The linked str vcf should have the tag `expansion hunter vcf`:
image

Test case 2: scout upload:
1. run `cg upload scout -p justhusky`

**Expected outcome**:
The scout upload config, printed to screen should display the str vcf file, identified by the key 'str-vcf'

**Review:**
- [x] code approved by @ingkebil 
- [x] tests executed by @emiliaol @barrystokman @patrikgrenfeldt 
- [x] Merge approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

No version bump because not merging with master.

### CODE REVIEW

**Comment by emiliaol** [comment]
Tests looks good!

Test case 1:
1. 
Skärmavbild 2019-07-29 kl  16 32 55
2 and 3. 
Skärmavbild 2019-07-29 kl  16 33 18

Test case 2:
The exansion hunter vcf has the tag vcf_str, not str_vcf but as all other vcfs have the same order as vcf_str I will assume that is correct.
Skärmavbild 2019-07-29 kl  16 34 21

**Comment by barrystokman** [comment]
> Test case 2:
> The exansion hunter vcf has the tag vcf_str, not str_vcf but as all other vcfs have the same order as vcf_str I will assume that is correct.

I used `vcf_str` because it was in the user story. Probably for the reasons you mentioned.

**Comment by emiliaol** [comment]
I also tried to upload the case to Scout stage and that fails although I think that is another issue:
Skärmavbild 2019-07-29 kl  16 48 45

**Comment by emiliaol** [comment]
> > Test case 2:
> > The exansion hunter vcf has the tag vcf_str, not str_vcf but as all other vcfs have the same order as vcf_str I will assume that is correct.
> 
> I used `vcf_str` because it was in the user story. Probably for the reasons you mentioned.

Yes, but you said in the test case to look for str_vcf, which was a bit confusing and therefor I wanted to explain why I approved it anyway.

**Comment by patrikgrenfeldt** [comment]
@emiliaol Scout stage is up ;)

**Comment by barrystokman** [comment]
@dnil The STR VCFs can now be uploaded to Scout stage (see screenshot below). Does this look correct to you? I'm asking you because there's no one else on site due to vacations. Thanks for your input! This is case justhusky for cust000.

image

**Comment by dnil** [comment]
Neat-o! Yep, looks good enough. Does this mean MIP7 parsing is now in place in cg in general or is this part of going there?

Best,

// Daniel

**Comment by vwirta** [comment]
Minor comment - is there a specific reason why the values in the estimated and reference columns are expressed in different way?

**Comment by barrystokman** [comment]
Development is still ongoing, but we're close now to starting validation and subsequent deployment of the rd_dna pipeline.

**Comment by barrystokman** [comment]
@VW That is a question the Scout people can answer.

**Comment by dnil** [comment]
@vwirta It follows directly from the Expansion Hunter output vcf, which has them in different formats. We should just parse it in Scout; no reason to confuse the end user! 😊

**Comment by vwirta** [comment]
sounds good :)

**Comment by patrikgrenfeldt** [comment]
@barrystokman and @emiliaol, I removed the test checkbox since we made some changes to that I think needs retesting

**Comment by barrystokman** [comment]
In order to have sucessful Traivis builds, we need to include TB MIP7.1-dev branch (pip install)

**Comment by ingkebil** [comment]
Yeah, I wonder how we can get around that easily?

**Comment by patrikgrenfeldt** [comment]
We could do like we did in this(!) PR; https://travis-ci.org/Clinical-Genomics/cg/builds/568402550
We built on travis with a custom config where we installed the specific trailblazer branch:
 
```
language: python

python:
    - '3.6'

cache: pip

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt .
    - pip install -U git+https://github.com/Clinical-Genomics/trailblazer@MIP7.1-dev
    - pip check

script:
    - coverage run --source "$(basename "$PWD")" setup.py test
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

after_success: coveralls

notifications:
    email: never
```

I don't know what qualifies as 'getting around it easily' but I think we should consider this a special case, building a non-production-ready branch against a non-production-ready dependency, and just accept that we have to do some non-normal things to make it work, what do you think about it?

**Comment by ingkebil** [comment]
Sounds like a plan!

Let's add that TB branch to the travis.cfg and merge it into CG's MIP7.1-dev branch. We cannot forget to undo that change once we merge to master. Any suggestions on how to not forget that?

Some options from the top of my head:
1. Make an issue with the todo list for everything we need to do before and after merging to master. It'll show up on the BL, so that's nice for planning
1. Make a PR with the changes we need to undo. I think we can also put that on the BL.

Anyway, up to you!

**Comment by patrikgrenfeldt** [comment]
I guess we'll remember if all builds starts failing due to failing installation after we delete the MIP7.1-dev branch?

In which repo would you have created those BL-items?

**Comment by ingkebil** [comment]
I would've created those BL-items in whatever repo they are relevant. If we tag them with 'PBL Teamname' they'll show up in the BL.

Good point about the failing build. I would still prefer to create an exit USs so we don't have to rely on things failing. e.g. It seems still didn't wrap up all the items needed to be done for MIP6 move to hasta ;)

**Comment by patrikgrenfeldt** [comment]
I created a PR for the cg-mip7 branch, it seemed appropriate to me to have the post merge step there, right?

**Comment by ingkebil** [comment]
Yes! großartig!

**Pull request merged**
