### PR TITLE
Adding MIP validation cases to fastq.py

### PR DESCRIPTION
**Pull request by henningonsbring**
This PR adds cases that should not be compressed since these families are often used for validation.

### How to prepare for test
- [ ] wait for the automatic fastq compression to start

### Expected test outcome
- [ ] Check that the problematic/validation cases where skipped
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @moonso 
- [ ] tests executed by
- [x] "Merge and deploy" approved by @moonso 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Mropat** [comment]
Could we also put keenviper (mip-dna) and sharpparrot (mip-rna) in the cases to ignore list?

Maybe make their own list of validation samples, and unpack both validation list and problematic cases list when skipping

**Review by moonso — APPROVED** [review]
Nice ⭐

**Comment by Mropat** [comment]
Are we sure the only way to test this is to deploy? There was no test for skipping cases in compress?

**Review by Mropat — CHANGES_REQUESTED** [review]
You can create tests for this by:

in tests/cli/compress/ you could do either:
1.
- Add problematic families to populated compress store in tests/cli/compress/conftest.py
- Write test for fastq_cmd checking the log for skipped case message

2.
- Write test for fastq_cmd while adding the problematic cases to ready-made populated_compress_store, checking the log for skipped case message

**Comment by hassanfa** [comment]
Could we add the following to the list as well? 

```
moralgoat - wgs paired
fleetjay - wgs single
bosssponge - panel single
unitedbeagle - panel paired
```

I test run on these when testing BALSAMIC releases.

Thanks!

**Review by Mropat — APPROVED** [review]
It would be great to add a test for this, but since this might be not the n1 prio right now, we could deploy this as is

**Comment by moonso** [comment]
@henningonsbring is this ready?

**Comment by henningonsbring** [comment]
No, there is something I need to solve in production before I deal with this

**Comment by Mropat** [comment]
Deployed hasta-stage 
image

Deployed on hasta-prod
image

**Comment by Mropat** [comment]
Congratulations @henningonsbring on your first contribution to cg! :partying_face:

**Comment by moonso** [comment]
Nice work @henningonsbring !

**Comment by henningonsbring** [comment]
Thank you for the help! :)

**Pull request merged**
