### PR TITLE
Fix(Ordering): Join synopsis list before processing

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
### Fixed
- Synopsis can now be either a list or a string

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test as list
- [x] do submit order with synopsis as a list

### Expected test outcome
- [x] check that the order has saved the synopsis as a string

### How to test as string
- [x] do submit order with synopsis as a string

### Expected test outcome
- [x] check that the order has saved the synopsis as a string

- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @barrystokman 
- [x] tests executed by PG
- [x] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to AG, DN, customer

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result list: 
image
🆗 synopsis saved as string when submitted as list

Test result string:
image
🆗 synopsis saved as string when submitted as string

**Review by barrystokman — APPROVED** [review]
🔥

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Comment by patrikgrenfeldt** [comment]
@annagellerbring @dnil This fix is now in production

**Pull request merged**
