### PR TITLE
feat(deploy): Ship loqusdb

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description
*This PR adds/fixes ...*
- Ship loqusdb via shipping

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh ship_loqusdb`

### How to test
- [x] do `cg deploy loqusdb`
- [x] do `loqusdb --version`
- [x] do  `loqusdb export -o loqusdb-snv-indel-variants-export-test.vcf -t snv --freq`

### Expected test outcome
- [x] Check that loqusdb is successfully deployed on Hasta stage
- [x] Check that the new version is installed
- [x] Check that new freq annotation is exported
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MM, MR
- [x] tests executed by HS
- [x] "Merge and deploy" approved by MM, HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in https://github.com/Clinical-Genomics/atlas/pull/111
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
- [ ] `cg deploy loqudb`
```
cg deploy loqusdb
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running CG DEPLOY
Use base call ['/home/proj/bin/conda/envs/S_shipping/bin/shipping', '--host-config', '/home/proj/stage/servers/config/hasta.scilifelab.se/host_config_stage.yaml']
Set dry run to False
Deploying LoqusDB with CG
Deploying the loqusdb software
Running command /home/proj/bin/conda/envs/S_shipping/bin/shipping --host-config /home/proj/stage/servers/config/hasta.scilifelab.se/host_config_stage.yaml --tool-name loqusdb deploy
2021-04-13 16:05:16 hasta.scilifelab.se shipping.cli.base[159322] INFO Hello shipper henrik.stranneheim
2021-04-13 16:05:16 hasta.scilifelab.se shipping.cli.base[159322] INFO Sailing on hasta.scilifelab.se
2021-04-13 16:05:16 hasta.scilifelab.se shipping.cli.deploy[159322] INFO Running shipping deploy
2021-04-13 16:05:16 hasta.scilifelab.se shipping.environment[159322] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-13 16:05:16 hasta.scilifelab.se shipping.environment[159322] INFO Locating base to /home/proj/bin/conda
2021-04-13 16:05:16 hasta.scilifelab.se shipping.commands[159322] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/S_loqusdb/bin/python
2021-04-13 16:05:16 hasta.scilifelab.se shipping.commands[159322] DEBUG Use base call ['/home/proj/bin/conda/envs/S_loqusdb/bin/python']
2021-04-13 16:05:16 hasta.scilifelab.se shipping.package[159322] INFO Fetch current version for package loqusdb
2021-04-13 16:05:16 hasta.scilifelab.se shipping.commands[159322] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip show loqusdb
2021-04-13 16:05:23 hasta.scilifelab.se shipping.cli.deploy[159322] INFO henrik.stranneheim wants to deploy loqusdb on host hasta.scilifelab.se in environment S_loqusdb
2021-04-13 16:05:23 hasta.scilifelab.se shipping.deploy.conda[159322] INFO Check if conda is available on your system
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] INFO Locating base to /home/proj/bin/conda
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Conda is available: /home/proj/bin/conda
2021-04-13 16:05:23 hasta.scilifelab.se shipping.deploy.conda[159322] INFO You are in conda environment S_main
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] INFO Locating base to /home/proj/bin/conda
2021-04-13 16:05:23 hasta.scilifelab.se shipping.deploy.conda[159322] INFO You want to install in conda environment /home/proj/bin/conda/envs/S_loqusdb
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Check if conda environment S_loqusdb exists
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] INFO Locating base to /home/proj/bin/conda
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Conda env: S_loqusdb exists: True
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-13 16:05:23 hasta.scilifelab.se shipping.environment[159322] INFO Locating base to /home/proj/bin/conda
2021-04-13 16:05:23 hasta.scilifelab.se shipping.commands[159322] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/S_loqusdb/bin/python
2021-04-13 16:05:23 hasta.scilifelab.se shipping.commands[159322] DEBUG Use base call ['/home/proj/bin/conda/envs/S_loqusdb/bin/python']
2021-04-13 16:05:23 hasta.scilifelab.se shipping.commands[159322] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip install -U loqusdb
2021-04-13 16:05:24 hasta.scilifelab.se shipping.cli.deploy[159322] INFO Tool was successfully deployed
2021-04-13 16:05:24 hasta.scilifelab.se shipping.package[159322] INFO Fetch current version for package loqusdb
2021-04-13 16:05:24 hasta.scilifelab.se shipping.commands[159322] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip show loqusdb
```

**Review by Mropat — APPROVED** [review]

**Comment by henrikstranneheim** [comment]
@moonso and @Mropat I think this needs another review

**Comment by henrikstranneheim** [comment]
Redoing tests after merge and bug fixing
- [x] `cg deploy loqusdb`
```
[0|0|97] θ63° [henrik.stranneheim@hasta:~] [S_main] 2m3s $ cg deploy loqusdb
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running CG DEPLOY
Instantiating shipping api
Use base call ['/home/proj/bin/conda/envs/S_shipping/bin/shipping', '--host-config', '/home/proj/stage/servers/config/hasta.scilifelab.se/host_config_stage.yaml']
Set dry run to False
Deploying LoqusDB with CG
Deploying the loqusdb software
Running command /home/proj/bin/conda/envs/S_shipping/bin/shipping --host-config /home/proj/stage/servers/config/hasta.scilifelab.se/host_config_stage.yaml --tool-name loqusdb deploy
2021-04-15 09:21:23 hasta.scilifelab.se shipping.cli.base[127117] INFO Hello shipper henrik.stranneheim
2021-04-15 09:21:23 hasta.scilifelab.se shipping.cli.base[127117] INFO Sailing on hasta.scilifelab.se
2021-04-15 09:21:23 hasta.scilifelab.se shipping.cli.deploy[127117] INFO Running shipping deploy
2021-04-15 09:21:23 hasta.scilifelab.se shipping.environment[127117] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-15 09:21:23 hasta.scilifelab.se shipping.environment[127117] INFO Locating base to /home/proj/bin/conda
2021-04-15 09:21:23 hasta.scilifelab.se shipping.commands[127117] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/S_loqusdb/bin/python
2021-04-15 09:21:23 hasta.scilifelab.se shipping.commands[127117] DEBUG Use base call ['/home/proj/bin/conda/envs/S_loqusdb/bin/python']
2021-04-15 09:21:23 hasta.scilifelab.se shipping.package[127117] INFO Fetch current version for package loqusdb
2021-04-15 09:21:23 hasta.scilifelab.se shipping.commands[127117] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip show loqusdb
2021-04-15 09:21:29 hasta.scilifelab.se shipping.cli.deploy[127117] INFO henrik.stranneheim wants to deploy loqusdb on host hasta.scilifelab.se in environment S_loqusdb
2021-04-15 09:21:29 hasta.scilifelab.se shipping.deploy.conda[127117] INFO Check if conda is available on your system
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] INFO Locating base to /home/proj/bin/conda
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] DEBUG Conda is available: /home/proj/bin/conda
2021-04-15 09:21:29 hasta.scilifelab.se shipping.deploy.conda[127117] INFO You are in conda environment S_main
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] INFO Locating base to /home/proj/bin/conda
2021-04-15 09:21:29 hasta.scilifelab.se shipping.deploy.conda[127117] INFO You want to install in conda environment /home/proj/bin/conda/envs/S_loqusdb
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] DEBUG Check if conda environment S_loqusdb exists
2021-04-15 09:21:29 hasta.scilifelab.se shipping.environment[127117] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-15 09:21:30 hasta.scilifelab.se shipping.environment[127117] INFO Locating base to /home/proj/bin/conda
2021-04-15 09:21:30 hasta.scilifelab.se shipping.environment[127117] DEBUG Conda env: S_loqusdb exists: True
2021-04-15 09:21:30 hasta.scilifelab.se shipping.environment[127117] DEBUG Found conda env path: /home/proj/bin/conda/envs/S_shipping
2021-04-15 09:21:30 hasta.scilifelab.se shipping.environment[127117] INFO Locating base to /home/proj/bin/conda
2021-04-15 09:21:30 hasta.scilifelab.se shipping.commands[127117] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/S_loqusdb/bin/python
2021-04-15 09:21:30 hasta.scilifelab.se shipping.commands[127117] DEBUG Use base call ['/home/proj/bin/conda/envs/S_loqusdb/bin/python']
2021-04-15 09:21:30 hasta.scilifelab.se shipping.commands[127117] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip install -U loqusdb
2021-04-15 09:21:31 hasta.scilifelab.se shipping.cli.deploy[127117] INFO Tool was successfully deployed
2021-04-15 09:21:31 hasta.scilifelab.se shipping.package[127117] INFO Fetch current version for package loqusdb
2021-04-15 09:21:31 hasta.scilifelab.se shipping.commands[127117] INFO Running command /home/proj/bin/conda/envs/S_loqusdb/bin/python -m pip show loqusdb
```

- [x] New version installed (previous was 2.5)
```
[0|0|97] θ66° [henrik.stranneheim@hasta:~] [S_main] 2s $ loqusdb --version
loqusdb, version 2.5.2
```

- [x] Exporting using new freq flag
```
[0|0|97] θ68° [henrik.stranneheim@hasta:~] [S_main] 7s $ loqusdb export -o loqusdb-snv-indel-variants-export-test.vcf -t snv --freq
2021-04-15 09:25:53 hasta.scilifelab.se loqusdb.commands.cli[130347] INFO Running loqusdb version 2.5.2
2021-04-15 09:25:53 hasta.scilifelab.se mongo_adapter.client[130347] INFO Connecting to uri:mongodb://loqusdb-stage:******@localhost:27030
2021-04-15 09:25:53 hasta.scilifelab.se mongo_adapter.client[130347] INFO Connection established
2021-04-15 09:25:53 hasta.scilifelab.se mongo_adapter.adapter[130347] INFO Use database loqusdb-rd-stage
2021-04-15 09:25:53 hasta.scilifelab.se loqusdb.commands.export[130347] INFO Export the variants from MongoAdapter(db=loqusdb-rd-stage)
2021-04-15 09:25:53 hasta.scilifelab.se loqusdb.commands.export[130347] INFO Found 8 cases in database
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding fileformat to vcf: VCFv4.3
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding meta line to vcf: ##NrCases=8
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding info line to vcf: ##INFO=<ID=Frq,Number=1,Type=Float,Description="Observation frequency of the variant (not allele frequency)">
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding info line to vcf: ##INFO=<ID=Obs,Number=1,Type=Integer,Description="The number of observations for the variant">
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding info line to vcf: ##INFO=<ID=Hom,Number=1,Type=Integer,Description="The number of observed homozygotes">
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding info line to vcf: ##INFO=<ID=Hem,Number=1,Type=Integer,Description="The number of observed hemizygotes">
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=1,length=249240489>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=2,length=243189191>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=3,length=197961601>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=4,length=191044166>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=5,length=180905086>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=6,length=171053561>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=7,length=159128640>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=8,length=146303562>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=9,length=141149863>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=10,length=135524732>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=11,length=134946509>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=12,length=133841648>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=13,length=115109853>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=14,length=107289437>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=15,length=102521378>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=16,length=90294733>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=17,length=81195086>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=18,length=78016904>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=19,length=59118929>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=20,length=62965368>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=21,length=48119820>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=22,length=51243071>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=X,length=155260437>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=Y,length=59033731>
2021-04-15 09:25:53 hasta.scilifelab.se vcftoolbox.header_parser[130347] INFO Adding contig line to vcf: ##contig=<ID=MT,length=16520>
2021-04-15 09:25:53 hasta.scilifelab.se loqusdb.commands.export[130347] INFO Collecting all SNV variants
2021-04-15 09:25:53 hasta.scilifelab.se loqusdb.plugins.mongo.variant[130347] INFO Find all variants {'chrom': '1'}
2021-04-15 09:25:55 hasta.scilifelab.se loqusdb.commands.export[130347] INFO 590334 variants found
```

**Review by Mropat — APPROVED** [review]
:+1:

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:
```
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.20.0) (0.4.3)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-20.20.0-py3-none-any.whl size=432173 sha256=8cc085657c007276fd45a5391d8564969d00b583bc082cd18d08e266e0757bcc
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-cm9naat2/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 20.19.5
    Uninstalling cg-20.19.5:
      Successfully uninstalled cg-20.19.5
Successfully installed cg-20.20.0
remote: Enumerating objects: 1686, done.
remote: Counting objects: 100% (1299/1299), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 1093 (delta 867), reused 959 (delta 742), pack-reused 0
Receiving objects: 100% (1093/1093), 180.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (867/867), completed with 101 local objects.
From https://github.com/Clinical-Genomics/cg
   d3c8027..001371d  master     -> origin/master
 * [new branch]      demux-finish -> origin/demux-finish
 * [new branch]      fix-link-undetermined -> origin/fix-link-undetermined
   5f295ea..27af76f  gisaid     -> origin/gisaid
 * [new tag]         v20.20.0   -> v20.20.0
Updating d3c8027..001371d
Fast-forward
 .bumpversion.cfg                        |  3 ++-
 CHANGELOG.md                            |  5 +++++
 cg/cli/deploy/base.py                   | 54 ++++++++++++++++++++++++++++++++----------------------
 cg/models/cg_config.py                  |  6 +++++-
 setup.py                                |  2 +-
 tests/cli/deploy/conftest.py            | 12 ++++++++++++
 tests/cli/deploy/test_deploy_command.py | 58 ++++++++++++++++++++++++++++++++++++++++++++++++++++------
 7 files changed, 109 insertions(+), 31 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 20.20.0
housekeeper, version 3.2.0
demux, version 5.8.0
cglims, version 1.3.4
```

**Comment by henrikstranneheim** [comment]
Updating loqusdb:
```
[9|268|667] 2d [hiseq.clinical@hasta:~] [P_main] $ cg deploy loqusdb
Running CG DEPLOY
Instantiating shipping api
Use base call ['/home/proj/bin/conda/envs/P_shipping/bin/shipping', '--host-config', '/home/proj/production/servers/config/hasta.scilifelab.se/host_config_prod.yaml']
Set dry run to False
Deploying LoqusDB with CG
Deploying the loqusdb software
Running command /home/proj/bin/conda/envs/P_shipping/bin/shipping --host-config /home/proj/production/servers/config/hasta.scilifelab.se/host_config_prod.yaml --tool-name loqusdb deploy
2021-04-15 13:46:09 hasta.scilifelab.se shipping.cli.base[149901] INFO Hello shipper hiseq.clinical
2021-04-15 13:46:09 hasta.scilifelab.se shipping.cli.base[149901] INFO Sailing on hasta.scilifelab.se
2021-04-15 13:46:09 hasta.scilifelab.se shipping.cli.deploy[149901] INFO Running shipping deploy
2021-04-15 13:46:09 hasta.scilifelab.se shipping.environment[149901] DEBUG Found conda env path: /home/proj/bin/conda/envs/P_shipping
2021-04-15 13:46:09 hasta.scilifelab.se shipping.environment[149901] INFO Locating base to /home/proj/bin/conda
2021-04-15 13:46:09 hasta.scilifelab.se shipping.commands[149901] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/P_loqusdb/bin/python
2021-04-15 13:46:09 hasta.scilifelab.se shipping.commands[149901] DEBUG Use base call ['/home/proj/bin/conda/envs/P_loqusdb/bin/python']
2021-04-15 13:46:09 hasta.scilifelab.se shipping.package[149901] INFO Fetch current version for package loqusdb
2021-04-15 13:46:09 hasta.scilifelab.se shipping.commands[149901] INFO Running command /home/proj/bin/conda/envs/P_loqusdb/bin/python -m pip show loqusdb
2021-04-15 13:46:16 hasta.scilifelab.se shipping.cli.deploy[149901] INFO hiseq.clinical wants to deploy loqusdb on host hasta.scilifelab.se in environment P_loqusdb
2021-04-15 13:46:16 hasta.scilifelab.se shipping.deploy.conda[149901] INFO Check if conda is available on your system
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Found conda env path: /home/proj/bin/conda/envs/P_shipping
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] INFO Locating base to /home/proj/bin/conda
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Conda is available: /home/proj/bin/conda
2021-04-15 13:46:16 hasta.scilifelab.se shipping.deploy.conda[149901] INFO You are in conda environment P_main
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Found conda env path: /home/proj/bin/conda/envs/P_shipping
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] INFO Locating base to /home/proj/bin/conda
2021-04-15 13:46:16 hasta.scilifelab.se shipping.deploy.conda[149901] INFO You want to install in conda environment /home/proj/bin/conda/envs/P_loqusdb
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Check if conda environment P_loqusdb exists
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Found conda env path: /home/proj/bin/conda/envs/P_shipping
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] INFO Locating base to /home/proj/bin/conda
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Conda env: P_loqusdb exists: True
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] DEBUG Found conda env path: /home/proj/bin/conda/envs/P_shipping
2021-04-15 13:46:16 hasta.scilifelab.se shipping.environment[149901] INFO Locating base to /home/proj/bin/conda
2021-04-15 13:46:16 hasta.scilifelab.se shipping.commands[149901] DEBUG Initialising Process with binary: /home/proj/bin/conda/envs/P_loqusdb/bin/python
2021-04-15 13:46:16 hasta.scilifelab.se shipping.commands[149901] DEBUG Use base call ['/home/proj/bin/conda/envs/P_loqusdb/bin/python']
2021-04-15 13:46:16 hasta.scilifelab.se shipping.commands[149901] INFO Running command /home/proj/bin/conda/envs/P_loqusdb/bin/python -m pip install -U loqusdb
2021-04-15 13:46:18 hasta.scilifelab.se shipping.cli.deploy[149901] INFO Tool was successfully deployed
2021-04-15 13:46:18 hasta.scilifelab.se shipping.package[149901] INFO Fetch current version for package loqusdb
2021-04-15 13:46:18 hasta.scilifelab.se shipping.commands[149901] INFO Running command /home/proj/bin/conda/envs/P_loqusdb/bin/python -m pip show loqusdb
[8|267|662] θ61° 2d [hiseq.clinical@hasta:~] [P_main] 29s $ loqusdb --version
loqusdb, version 2.5.2
```

**Pull request merged**
