### PR TITLE
first tag map

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...

New script to link old balsamic tagged cases to cust inbox

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] cg deliver old-analysis -c hotoyster -d balsamic --dry-run
- [x] cg deliver old-analysis -c hotoyster -d balsamic-qc --dry-run
- [x] cg deliver old-analysis -c movedjay -d balsamic --dry-run
- [x] cg deliver old-analysis -c movedjay -d balsamic-qc --dry-run
- [x] cg deliver old-analysis -c famoussnail -d balsamic --dry-run
- [x] cg deliver old-analysis -c famoussnail -d balsamic-qc --dry-run

### Expected test outcome
- [x] check that necessary files are linked
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by MR, KE
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MINOR** - when you add functionality in a backwards compatible manner

## Implementation Plan
- [ ] Deploy this branch
- [x] Inform @keyvanelhami

### CODE REVIEW

**Comment by Mropat** [comment]
```
cg deliver old-analysis -c hotoyster -d balsamic --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle hotoyster
Setting ticket_id to 821450
Setting customer_id to cust096
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.vardict.all.filtered.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.vardict.all.filtered.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.vardict.all.filtered.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.vardict.all.filtered.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/tumor.merged.cnr to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/tumor.merged.cnr
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/tumor.merged-scatter.pdf to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/tumor.merged-scatter.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/tumor.merged-diagram.pdf to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/tumor.merged-diagram.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.vardict.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.vardict.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.vardict.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.vardict.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SV.somatic.hotoyster.manta.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SV.somatic.Case-7-relapse.manta.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SV.somatic.hotoyster.manta.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SV.somatic.Case-7-relapse.manta.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.tnhaplotyper.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.tnhaplotyper.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/SNV.somatic.hotoyster.tnhaplotyper.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/SNV.somatic.Case-7-relapse.tnhaplotyper.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/CNV.somatic.hotoyster.cnvkit.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/CNV.somatic.Case-7-relapse.cnvkit.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/CNV.somatic.hotoyster.cnvkit.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/CNV.somatic.Case-7-relapse.cnvkit.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/tumor.merged.cram to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/tumor.merged.cram
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/tumor.merged.cram.crai to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/tumor.merged.cram.crai
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/multiqc_report.html to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/multiqc_report.html
Linked 16 files for case hotoyster
Linked 0 files for sample ACC6968A49, case hotoyster

```
```
cg deliver old-analysis -c hotoyster -d balsamic-qc --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle hotoyster
Setting ticket_id to 821450
Setting customer_id to cust096
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/multiqc_report.html to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/multiqc_report.html
Linked 1 files for case hotoyster
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/concatenated_ACC6968A49_XXXXXX_R_1.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/2-RT/concatenated_2-RT_XXXXXX_R_1.fp.fastq.gz
Would hard link file /home/proj/stage/housekeeper-bundles/hotoyster/2020-11-19/concatenated_ACC6968A49_XXXXXX_R_2.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/Case-7-relapse/2-RT/concatenated_2-RT_XXXXXX_R_2.fp.fastq.gz
Linked 2 files for sample ACC6968A49, case hotoyster

```

**Comment by Mropat** [comment]
```
cg deliver old-analysis -c movedjay -d balsamic --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle movedjay
Setting ticket_id to 821450
Setting customer_id to cust096
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/tumor.merged.cram to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/tumor.merged.cram
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/tumor.merged.cram.crai to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/tumor.merged.cram.crai
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.tnhaplotyper.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.tnhaplotyper.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.tnhaplotyper.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.tnhaplotyper.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/CNV.somatic.movedjay.cnvkit.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/CNV.somatic.case-12-metastas.cnvkit.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/CNV.somatic.movedjay.cnvkit.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/CNV.somatic.case-12-metastas.cnvkit.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.vardict.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.vardict.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.vardict.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.vardict.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.strelka.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.strelka.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SNV.somatic.movedjay.strelka.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SNV.somatic.case-12-metastas.strelka.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SV.somatic.movedjay.manta.pass.vcf.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SV.somatic.case-12-metastas.manta.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/SV.somatic.movedjay.manta.pass.vcf.gz.tbi to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/SV.somatic.case-12-metastas.manta.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/tumor.merged.cnr to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/tumor.merged.cnr
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/tumor.merged-scatter.pdf to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/tumor.merged-scatter.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/tumor.merged-diagram.pdf to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/tumor.merged-diagram.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/normal.merged.cram to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/normal.merged.cram
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/normal.merged.cram.crai to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/normal.merged.cram.crai
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/multiqc_report.html to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/multiqc_report.html
Linked 18 files for case movedjay
Linked 0 files for sample ACC6968A60, case movedjay
Linked 0 files for sample ACC6968A61, case movedjay

```
```
cg deliver old-analysis -c movedjay -d balsamic-qc --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle movedjay
Setting ticket_id to 821450
Setting customer_id to cust096
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/multiqc_report.html to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/multiqc_report.html
Linked 1 files for case movedjay
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/concatenated_ACC6968A60_XXXXXX_R_1.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/19-PN/concatenated_19-PN_XXXXXX_R_1.fp.fastq.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/concatenated_ACC6968A60_XXXXXX_R_2.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/19-PN/concatenated_19-PN_XXXXXX_R_2.fp.fastq.gz
Linked 2 files for sample ACC6968A60, case movedjay
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/concatenated_ACC6968A61_XXXXXX_R_1.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/11-DMT/concatenated_11-DMT_XXXXXX_R_1.fp.fastq.gz
Would hard link file /home/proj/stage/housekeeper-bundles/movedjay/2020-11-06/concatenated_ACC6968A61_XXXXXX_R_2.fp.fastq.gz to /home/proj/stage/customers/cust096/inbox/821450/case-12-metastas/11-DMT/concatenated_11-DMT_XXXXXX_R_2.fp.fastq.gz
Linked 2 files for sample ACC6968A61, case movedjay

```

**Comment by Mropat** [comment]
```
cg deliver old-analysis -c famoussnail -d balsamic --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle famoussnail
Setting ticket_id to 288945
Setting customer_id to cust080
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.tnhaplotyper.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.tnhaplotyper.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.tnhaplotyper.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.tnhaplotyper.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.mutect.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.mutect.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.mutect.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.mutect.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/CNV.somatic.famoussnail.cnvkit.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/CNV.somatic.KMP00109.cnvkit.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/CNV.somatic.famoussnail.cnvkit.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/CNV.somatic.KMP00109.cnvkit.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.strelka.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.strelka.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.strelka.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.strelka.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SV.somatic.famoussnail.manta.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SV.somatic.KMP00109.manta.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SV.somatic.famoussnail.manta.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SV.somatic.KMP00109.manta.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.vardict.pass.vcf.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.vardict.pass.vcf.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/SNV.somatic.famoussnail.vardict.pass.vcf.gz.tbi to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/SNV.somatic.KMP00109.vardict.pass.vcf.gz.tbi
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/normal.merged.cram to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/normal.merged.cram
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/normal.merged.cram.crai to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/normal.merged.cram.crai
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/tumor.merged.cnr to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/tumor.merged.cnr
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/tumor.merged-scatter.pdf to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/tumor.merged-scatter.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/tumor.merged-diagram.pdf to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/tumor.merged-diagram.pdf
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/multiqc_report.html to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/multiqc_report.html
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/tumor.merged.cram to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/tumor.merged.cram
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/tumor.merged.cram.crai to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/tumor.merged.cram.crai
Linked 20 files for case famoussnail
Linked 0 files for sample ACC7200A6, case famoussnail
Linked 0 files for sample ACC7200A7, case famoussnail

```

```
cg deliver old-analysis -c famoussnail -d balsamic-qc --dry-run
Running CG deliver
Set dry run to True
Fetch latest version from bundle famoussnail
Setting ticket_id to 288945
Setting customer_id to cust080
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/multiqc_report.html to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/multiqc_report.html
Linked 1 files for case famoussnail
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/concatenated_ACC7200A6_XXXXXX_R_1.fp.fastq.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/KMP00144G/concatenated_KMP00144G_XXXXXX_R_1.fp.fastq.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/concatenated_ACC7200A6_XXXXXX_R_2.fp.fastq.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/KMP00144G/concatenated_KMP00144G_XXXXXX_R_2.fp.fastq.gz
Linked 2 files for sample ACC7200A6, case famoussnail
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/concatenated_ACC7200A7_XXXXXX_R_1.fp.fastq.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/KMP00145T/concatenated_KMP00145T_XXXXXX_R_1.fp.fastq.gz
Would hard link file /home/proj/stage/housekeeper-bundles/famoussnail/2020-11-09/concatenated_ACC7200A7_XXXXXX_R_2.fp.fastq.gz to /home/proj/stage/customers/cust080/inbox/288945/KMP00109/KMP00145T/concatenated_KMP00145T_XXXXXX_R_2.fp.fastq.gz
Linked 2 files for sample ACC7200A7, case famoussnail


```

**Review by moonso — APPROVED** [review]
😲

**Comment by Mropat** [comment]
Deployed on prod

```
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-19.1.0-py3-none-any.whl size=397130 sha256=386818ffb81320ad155afb7b3ac30945661d2d194c239134ccb2329a87370cab
  Stored in directory: /home/maryia.ropart/tmp/pip-ephem-wheel-cache-7mobjspy/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 19.0.0
    Uninstalling cg-19.0.0:
      Successfully uninstalled cg-19.0.0
Successfully installed cg-19.1.0
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/maryia.ropart
done.
Log deploy... done.

```

**Pull request merged**
