### PR TITLE
Update PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:

- This typo: hasta.sclifelab.se

**Review:**
- [ ] code approved by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@barrystokman Could you review this one. It is really tiny

**Comment by henrikstranneheim** [comment]
@barrystokman Thx. Please merge and deploy when you have time

**Comment by barrystokman** [comment]
Deployed.

**Comment by henrikstranneheim** [comment]
@barrystokman Thx

**Comment by patrikgrenfeldt** [comment]
Good catch!

**Pull request merged**
