### PR TITLE
feat(ordeform 1508) Support new orderform version

### PR DESCRIPTION
**Pull request by Vince-janv**
## Description
@annagellerbring has updated the orderform for clinical samples and this PR changes all the fixture plus the allowed version for the affected order types

### Changed

- Allowed version for orderform 1508 changed from 28 to 29

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by seallard — APPROVED** [review]
👍 Hopefully we can clean this up some day

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by Vince-janv** [comment]
> 👍 Hopefully we can clean this up some day

Please yes. I just spend an hour editing excel sheets 😢

**Comment by Vince-janv** [comment]
New orderform works with this PR deployed on stage

**Pull request merged**
