### PR TITLE
Convey sv_rank_model_version from MIP to Scout

### PR DESCRIPTION
**Pull request by dnil**
As in Scout issue #493 (fix in scout #1220). Available already in MIP 6. I suppose the structure changes much as for the other similar values for MIP 7.

This PR fixes the leaking coffee machine.

How to test:
On stage, upload a case with SV rank model version set to scout post PR #1220. 

Expected outcome:
See that SV rank model version is displayed under Rank models on the Scout case page.

- [x] Code reviewed by @ingkebil 
- [x] Tested OK by @emiliaol 
- [x] deploy OK by @ingkebil 

This is minor version: adds functionality.

### CODE REVIEW

**Comment by dnil** [comment]
Nope, true that! I've added a PR there as well for good measure!

**Comment by ingkebil** [comment]
So does any case work with this? If possible, can you point us to a case with SV variants?

**Comment by dnil** [comment]
Any decently recent MIP6 case. I guess ideally one of the external control samples, but for a recent local one, how about sample "neededkoi"?

**Comment by emiliaol** [comment]
Couldn't use update scripts for installing so did this:
Skärmavbild 2019-05-28 kl  10 21 44

Uploaded case `neededkoi` got the following error:
Skärmavbild 2019-05-28 kl  10 48 46

It seems the info is not there in the sample_qc_info file under `genmod`:
Skärmavbild 2019-05-28 kl  10 51 14

Instead the info seems to be under `sv_genmod`:
Skärmavbild 2019-05-28 kl  10 52 43

I made a change request in the trailblazer PR #51

**Comment by emiliaol** [comment]
Tested again after update to trailblazer in https://github.com/Clinical-Genomics/trailblazer/pull/51

I followed the same procedure as last time and the test passed:

Skärmavbild 2019-06-11 kl  16 04 57

**Comment by emiliaol** [comment]
@ingkebil @dnil Shouldn't we just deploy this?

**Comment by ingkebil** [comment]
This is now deployed

**Pull request merged**
