### PR TITLE
Adds tests for fix spring paths

### PR DESCRIPTION
**Pull request by moonso**
This PR fixes some small bugs in the fix spring paths functions and adds some tests for these.

### How to test
Follow instructions in #698

## Review
- [x] code approved by @barrystokman 
- [ ] tests executed by @barrystokman 
- [ ] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moonso** [comment]
Ping @barrystokman

**Comment by barrystokman** [comment]
Bumped:
image


Deployed:
image

Tests:
image

**Comment by barrystokman** [comment]
@moonso Looks okay to me, do you agree?

**Comment by moonso** [comment]
Not exactly what I expected but it was my fault, thanks again! I'll do some more improvements in another PR. This is just a command that we will run manually so there is nothing dangerous if it not perfect right now.

**Pull request merged**
