### PR TITLE
Fix automated spring decompression when cases contain both spring and fastq files

### PR DESCRIPTION
**Pull request by henningonsbring**
This PR fixes the automated spring decompression for the situation when cases contain files that are both decompressed (fastq) and compressed (spring).

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh fix_mixed_cases`

### How to test
- [x] do `cg workflow mip-dna start` for a case that got only fastq files
- [x] do `cg workflow mip-dna start` for a case that got only spring files
- [x] do `cg workflow mip-dna start` for a case that got both spring and fastq files

### Expected test outcome
- [x] decompression starts when there are spring
- [x] mip analysis starts when there are no spring
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by @henningonsbring (commands ran from @jemten that can run jobs on stage)
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henningonsbring** [comment]
```
cg workflow mip-dna start -p low wittymarlin
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Starting full MIP-DNA analysis workflow for case wittymarlin
All flowcells present on disk
Fetch latest version from bundle codetest3
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Compression/decompression is not running
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
The analysis for wittymarlin could not start, decompression is needed
Fetch latest version from bundle codetest3
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Fetch latest version from bundle codetest3
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Decompressing /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.spring to FASTQ format for sample codetest3
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.json
Validating SPRING metadata content
Generating sbatch header
Generating SPRING to FASTQ sbatch body
Created temporary dir /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/spring_0c7cp0yv_decompress
Submit sbatch
Creating pending flag
Running command sbatch /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001_decompress_spring.sh
Submitted batch job 963599
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest3/codetest3_XXXXXX_S26_L001.json
Validating SPRING metadata content
Adding todays date to SPRING metadata file
Decompression started for wittymarlin
Workflow interrupted: decompression is not finished
```

**Comment by henningonsbring** [comment]
```
cg workflow mip-dna start -p low  sharpcolt
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Starting full MIP-DNA analysis workflow for case sharpcolt
All flowcells present on disk
Fetch latest version from bundle codetest2
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Compression/decompression is not running
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
The analysis for sharpcolt could not start, decompression is needed
Fetch latest version from bundle codetest2
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Fetch latest version from bundle codetest2
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Decompressing /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.spring to FASTQ format for sample codetest2
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.json
Validating SPRING metadata content
Generating sbatch header
Generating SPRING to FASTQ sbatch body
Created temporary dir /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/spring_b_4yeo46_decompress
Submit sbatch
Creating pending flag
Running command sbatch /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001_decompress_spring.sh
Submitted batch job 963597
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L001.json
Validating SPRING metadata content
Adding todays date to SPRING metadata file
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002_R1_001.fastq.gz does not exist
Decompression is possible
Decompressing /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.spring to FASTQ format for sample codetest2
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.json
Validating SPRING metadata content
Generating sbatch header
Generating SPRING to FASTQ sbatch body
Created temporary dir /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/spring_dhw73ury_decompress
Submit sbatch
Creating pending flag
Running command sbatch /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002_decompress_spring.sh
Submitted batch job 963598
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest2/codetest2_XXXXXX_S26_L002.json
Validating SPRING metadata content
Adding todays date to SPRING metadata file
Decompression started for sharpcolt
Workflow interrupted: decompression is not finished
```

**Comment by henningonsbring** [comment]
```
cg workflow mip-dna start -p low eagerfowl
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Starting full MIP-DNA analysis workflow for case eagerfowl
All flowcells present on disk
Fetch latest version from bundle codetest1
Fetch latest version from bundle codetest1
Linking fastq files in housekeeper for case eagerfowl
Fetch latest version from bundle codetest1
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest1/codetest1_XXXXXX_S26_L001_R1_001.fastq.gz
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest1/codetest1_XXXXXX_S26_L001_R2_001.fastq.gz
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest1/codetest1_XXXXXX_S26_L002_R1_001.fastq.gz
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/codetest1/codetest1_XXXXXX_S26_L002_R2_001.fastq.gz
Fetch latest version from bundle codetest1
Decompression for case eagerfowl not needed, starting analysis
codetest1: mip-dna link FASTQ files
Fetching files from bundle codetest1
Fetching files with tags in [fastq]
Running command /home/proj/bin/conda/envs/S_scout/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml export panel --bed BRAIN Cardiology CTD ENDO EP IBMFS IEM IF NEURODEG NMD mcarta MHT MIT MOVE mtDNA PEDHEP PID PIDCAD OMIM-AUTO SKD
Config file saved to /home/proj/stage/rare-disease/cases/eagerfowl/pedigree.yaml
codetest1: downsampled/external - skip evaluation
Running command source activate S_mip9.0; /home/proj/bin/conda/envs/S_mip9.0/bin/mip analyse rd_dna eagerfowl --config /home/proj/stage/servers/config/hasta.scilifelab.se/mip9.0-dna-stage.yaml --slurm_quality_of_service low --email anders.jemt@scilifelab.se --qccollect_skip_evaluation
[INFO] 2021/02/18 12:43:12 MIP_ANALYSE - MIP Version: v9.1.3
```

**Review by Mropat — APPROVED** [review]
:100:

**Pull request merged**
