### PR TITLE
Move filters into separate directory

### PR DESCRIPTION
**Pull request by seallard**
## Description
I think we should group the filters in a separate directory.

### Fixed
- Move filters into separate directory

## Review
- [x] "Merge and deploy" approved by CO, HS, SD

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
I like this idea the directory was becoming quite full. In addition to this I would also move the tests to tests/store/filters/

**Review by henrikstranneheim — APPROVED** [review]
Awesome!

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by seallard** [comment]
I'm unable to deploy since I don't have access to Hasta yet.

**Pull request merged**
