### PR TITLE
Fix clean fc no bundles

### LINKED ISSUE #2861: Flow cells not removed
## Description

Some flow cell directories are not removed correctly. 

Examples:
22FWKKLT3
22FYY7LT3
22FJMMLT3 - Missing fastq files in housekeepr

## Suggested solution
- Look into the logs (`journalctl --user-unit cg-clean-flow-cells.service`) and see which criteria is blocking the removal
- See if the criterias are too strict

## This can be closed when

Any flow cell, (barring crashed runs) are removed once demultiplexed and added to the databases

### PR DESCRIPTION
**Pull request by diitaz93**
## Description
Fixes #2861. The clean command would fail a check if at least one sample bundle was missing in Housekeeper for the given flow cell.

### Changed

- Changed debug statements for warnings

### Fixed

- The check now fails if **all** samples are missing. So if only one sample is missing, it will clean the existing sample bundles
- A Try-except will catch individual bundles `HousekeeperBundleVersionMissingError`

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b fix-clean-fc-no-bundles -a
    ```

### How to test

- [x] Copy one of the uncleaned flow cells from prod to stage
- [x] run `cg clean flow-cells --dry-run`

### Expected test outcome

- [x] Check that the flow cell would have been deleted

## Review

- [x] Tests executed by SD
- [x] "Merge and deploy" approved by CO
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Deploy this branch on 
  - [ ] cg stage
  - [ ] cg production

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Looks still good despite changed branch name. :)

**Comment by islean** [comment]
Not knowing anything about this flow, take my comment with a grain of salt, but is this not risky? Like, don't we want to be certain that we have all data in place before cleaning old?

**Comment by islean** [comment]
> > Not knowing anything about this flow, take my comment with a grain of salt, but is this not risky? Like, don't we want to be certain that we have all data in place before cleaning old?
> 
> This is the behaviour as it was intended back when the api was designed. There are additional checks that need to be fulfilled as well.

Oh okay, if it was only intended to check if any data was in place, disregard my comment.

**Comment by diitaz93** [comment]
## Tests on stage
```shell
2024-01-24 10:14:31 hasta.scilifelab.se cg.apps.housekeeper.hk[35318] DEBUG Fetch latest version from bundle ACC13504A4
2024-01-24 10:14:31 hasta.scilifelab.se cg.apps.housekeeper.hk[35318] WARNING Bundle: ACC13504A4 not found in Housekeeper
2024-01-24 10:14:31 hasta.scilifelab.se cg.meta.clean.clean_flow_cells[35318] DEBUG Dry run: Would have removed: /srv/seqdata/seqdata/20231219_LH00188_0048_A22FWKKLT3
```

**Comment by diitaz93** [comment]
> > > Not knowing anything about this flow, take my comment with a grain of salt, but is this not risky? Like, don't we want to be certain that we have all data in place before cleaning old?
> > 
> > 
> > This is the behaviour as it was intended back when the api was designed. There are additional checks that need to be fulfilled as well.
> 
> Oh okay, if it was only intended to check if any data was in place, disregard my comment.

There are some other checks, like that the data is older than 21 days and that the flow cell is backed up 😊

**Comment by diitaz93** [comment]
## Deployed to stage:
```shell
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 55.4.11
θ62° 1d [js.diazboada@hasta:~] [S_base] 3m16s $
```
## Deployed to production:
```shell
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 55.4.11
θ65° 1d [js.diazboada@hasta:~] [P_base] 3m5s $
```

**Pull request merged**
