### PR TITLE
Use reference genome from customer input

### PR DESCRIPTION
**Pull request by sylvinite**
Previously the implementation would incorrectly fetch the organism reference instead of the provided reference.
This has now been resolved.

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh fix/microsalt-sample-reference-genome`

### How to test
- ssh to hasta
- up
- Create a config-case for microbial project 431359 

### Expected test outcome
- Verify that samples ACC7254A19, ACC7254A20, ACC7254A21 now have a null differing reference genome
Skärmavbild 2020-11-11 kl  16 33 36

## Review
- [x] code approved by @Mropat 
- [x] tests executed by @sylvinite 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by Mropat — APPROVED** [review]
:+1:

**Comment by Mropat** [comment]
Ready to deploy @sylvinite ?

**Comment by sylvinite** [comment]
@Mropat Everything done and works successfully.

**Comment by Mropat** [comment]
Installed on stage
image

Installed on prod
image

**Pull request merged**
