### PR TITLE
Adds list of problematic cases

### PR DESCRIPTION
**Pull request by moonso**
This PR adds a list of problematic cases that will be skipped during spring compression.
Related to #101

**Review:**
- [x] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moonso** [comment]
Hi @barrystokman , it would be nice if you could merge and deploy this before 22 tonight (20200706). Have a nice summer 🌤️

**Comment by barrystokman** [comment]
I'll take care of it, enjoy your vacation!

**Comment by moonso** [comment]
Really frustrating that the Github Actions don't finish. I think it has to do with the automatic black thing.

**Comment by barrystokman** [comment]
Bumped:
image

Deployed:
image

Crontabs updated:
image

**Pull request merged**
