### PR TITLE
Fix bug where only one sampels is linked from family trio

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes:
- Fixes but where linking MIP trio samples only linked the first sample instead of the whole family (Introduced in recent PR)
- Fixes bug where linking by SampleID was not linking the entire family (Old)
- Fixes bug where linking by SampleID would not be able to generate correct linking path (Old)

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] run cg workflow mip-dna -c majorlab

### Expected test outcome
- [ ] samples are linked successfully and analysis starts

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Mropat** [comment]
all files in majorlab link successfully
image

**Comment by Mropat** [comment]
Linking by sample successfully links all samples in family
image

**Review by henrikstranneheim — APPROVED** [review]
Looks good

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
Screenshot 2020-09-14 at 14 59 17

**Pull request merged**
