### PR TITLE
Remove revision for already existing index on sample_internal_id

### PR DESCRIPTION
**Pull request by seallard**
This reverts commit 9cb0ddc3e41fb5859d922b6bf8dc4d889c328ec8.

## Description
This PR removes the commit which introduced an index on the `sample_internal_id`. I missed that this column is marked as a foreign key which means it already has an index. So the revision is useless and the downgrade method does not work.

So this PR removes the revision and I will have to manually edit the id of the latest applied revision in the database since the down method is broken.

### Fixed
- Revert introduction of index on already indexed column

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by seallard** [comment]
Deployed to stage and revisions applied successfully.

**Comment by seallard** [comment]
Deployed to prod and revisions applied successfully.

**Pull request merged**
