### PR TITLE
Fix(Ordering): Use correct exception

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
### Fixed
- Use correct exception when applications are of different types

### How to test
- [x] do submit RML-OF with different apptags in it

### Expected test outcome
- [x] check that there is a message for the user other than "Network Error"
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by PG
- [ ] "Merge and deploy" approved by 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch
- [ ] Inform to SC

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result: 
image
🆗 Error message shown to user instead of "Network Error"

**Review by barrystokman — APPROVED** [review]
👍🏻

**Comment by patrikgrenfeldt** [comment]
@saschaconradt I have fixed the problem in the orderportal that gave users a "Network Error" instead of a message explaining that more than one application was used in the same pool

**Comment by patrikgrenfeldt** [comment]
Deployed to production: 
image

**Pull request merged**
