### PR TITLE
Feature: Update orderform 2184 to latest version 4 (#296)

### PR DESCRIPTION
**Pull request by JessicaHillert**
## Description
*This PR updates orderform 2184 to latest version 4*

Issue: https://github.com/Clinical-Genomics/cgweb/issues/296 

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] Go to the order portal

### Expected test outcome
- [x] Uploading an old orderform (e.g. 2184:3) will NOT be allowed
- [x] Uploading an orderform with correct version (2184:4) will be allowed
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by JH
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in changelog
- [ ] Deploy this branch to clinical-db (wait for FE fix for prod)
- [ ] Inform to clinical_production@scilifelab.se and Anna G

### CODE REVIEW

**Comment by JessicaHillert** [comment]
@patrikgrenfeldt Is this minor or major? Also, is it correct to bump it already? It did that automatically.

**Comment by JessicaHillert** [comment]
Screen Shot 2021-03-24 at 10 59 03
Tests worked!

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Comment by patrikgrenfeldt** [comment]
Deployed on Hasta:
image

Deployed on clinical-db:
image

**Pull request merged**
