### PR TITLE
dry-run command unification

### PR DESCRIPTION
**Pull request by eliottBo**
## Description
This PR is linked to issue #2947. The dry-run command was defined in multiple files. This PR unifies the definition and references of the dry-run command. Each file using the dry-run command were changed to use the command definition from cg/constants/constants.py. Import statements were added or changed, @DRY_RUN decorators were added and modified, other definitions were removed.

### Changed

- Following files were changed:
	- [x]  cg/cli/add.py
	- [x]  cg/cli/deliver/base.py
	- [x]  cg/cli/demultiplex/demux.py
	- [x]  cg/cli/generate/report/options.py
	    - files referring to this definition:
	        - [x]  /Users/eliottbosshard/cg/cg/cli/generate/report/base.py
	- [x]  cg/cli/upload/delivery_report.py
	- [x]  cg/cli/upload/fohm.py
	- [x]  cg/cli/upload/mutacc.py
	- [x]  cg/cli/upload/nipt/base.py
	- [x]  cg/cli/upload/nipt/ftp.py
	- [x]  cg/cli/upload/nipt/statina.py
	- [x]  cg/cli/workflow/commands.py
	    - Files refering to this definition:
	        - [x]  /Users/eliottbosshard/cg/cg/cli/upload/gens.py
	        - [x]  /Users/eliottbosshard/cg/cg/cli/upload/observations/observations.py
	        - [x]  /Users/eliottbosshard/cg/cg/cli/workflow/mutant/base.py
	        - [x]  /Users/eliottbosshard/cg/cg/cli/workflow/nf_analysis.py
	        - [x]  /Users/eliottbosshard/cg/cg/cli/workflow/raredisease/base.py
	- [x]  cg/cli/workflow/fluffy/base.py
	- [x]  cg/cli/workflow/microsalt/base.py
	- [x]  cg/cli/workflow/mip/options.py

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [X] Run command cg generate delivery-report acetuna --dry-run

### Expected test outcome

- [X] Check that the command worked
- [X] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [X] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ivadym — APPROVED** [review]
Nice! Well done ⭐ 💯 

I noticed another instance of the dry run declaration in `cg/cli/delete/cases.py`. Feel free to remove it as well

**Review by diitaz93 — APPROVED** [review]
Amazing 💯

**Comment by eliottBo** [comment]
Tested following command in cg-stage:

```Shell
[eliott.bosshard@hasta:~] [S_base] $ cg generate delivery-report acetuna --dry-run
```
Got following output:
```Shell
--------------- DELIVERY REPORT ---------------
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Using analysis started at: 2024-04-29 13:58:13
Found analysis type tumor_panel
Found analysis type tumor_panel
Empty report fields: 
applications:
  PANKTTR020:
  - workflow_limitations
data_analysis:
- panels
- delivered_files
samples:
  ACC9362A4:
  - delivered_files
  - delivered_fastq_files
 ```

**Comment by eliottBo** [comment]
Installation in production environment:

Screenshot 2024-05-13 at 16 52 04

**Pull request merged**
