### PR TITLE
Allow customer to delete file on caesar

### PR DESCRIPTION
**Pull request by henningonsbring**
## Description
To allow the customer to delete SARS-CoV-2 reports on caesar sent for automated processing.

### Added

-

### Changed

-

### Fixed

- Allows customer to delete files on caesar

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henningonsbring** [comment]
Did:
`rsync -rvptL --chmod=777 /home/proj/production/mutant/cases/funnyleech/results/sars-cov-2_515822_results.csv caesar.scilifelab.se:/home/cust124/inbox/wwLab_automatisk_hamtning/`

The covid report showed up on caesar with permissions:
`-rwxrwxrwx  1 hiseq.clinical  cust124  17226 Jan 12 21:01 sars-cov-2_515822_results.csv`

A few minutes later the file disappeared:
```
ll wwLab_automatisk_hamtning/
total 0
```

The `-p` is necessary despite the `--chmod` flag. If skipping `-p` then permissions looks like this:
`-rwxr-xr-x  1 hiseq.clinical  cust124  17226 Jan 13 11:50 sars-cov-2_515822_results.csv`

The `--chmod=777` setting is necessary as well, otherwise the file wont be deleted automatically. The `-t` will preserve modification time of the file during the transfer.

**Comment by henningonsbring** [comment]
I closed this PR: https://github.com/Clinical-Genomics/cg/pull/1359

In the closed PR we are using `-a` which means `-rlptgoD`, and the preserved ownership via `-o` will prevent customers from deleting the files in their space on caesar.

**Comment by henningonsbring** [comment]
Adding `-p` and `-t` flag for the SARS-CoV-2 fastq transfer as well.

I ran rsync with -rvL flag (i.e. as we have done it before) and I got the following permissions on caesar (`rsync -rvL --progress /home/proj/production/customers/cust124/inbox/935793/ caesar.scilifelab.se:/home/cust124/inbox/935793/`):
```
ll 935793/
total 48
drwxr-s---  2 hiseq.clinical  cust124  4 Jan 13 12:42 22CS100001
drwxr-s---  2 hiseq.clinical  cust124  4 Jan 13 12:42 22CS100002
drwxr-s---  2 hiseq.clinical  cust124  4 Jan 13 12:42 22CS100003
drwxr-s---  2 hiseq.clinical  cust124  4 Jan 13 12:42 22CS100004
drwxr-s---  2 hiseq.clinical  cust124  4 Jan 13 12:42 22CS100005
```
Looking at all other folders on caesar we have the following permissions:
```
ll 938613
total 50
drwxrws---  2 hiseq.clinical  cust124  4 Dec 28 09:11 21CS107526
drwxrws---  2 hiseq.clinical  cust124  4 Dec 28 09:11 21CS107527
drwxrws---  2 hiseq.clinical  cust124  4 Dec 28 09:11 21CS107528
drwxrws---  2 hiseq.clinical  cust124  4 Dec 28 09:11 21CS107529
```

I do not understand why a writing permission suddenly disappeared from the permissions when we do like we always have done. Should we add `-p` to all other rsyncs as well?

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Pull request merged**
