### PR TITLE
change/q30-flowcell-check

### PR DESCRIPTION
**Pull request by karlnyr**
## Description

Updated how Q30 threshold values for NovaSeq 6000 flow cells, according  AM dock 1830, are passed. In the future, if these values are to be changed, they can be done so through the new constants 

### Changed

- Q30 threshold values for samples

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh add/q30-flowcell-check`

### How to test
- [x] do `cg transfer flowcell HMWTFDRXY `

### Expected test outcome
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by @karlnyr 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in *NA*
- [ ] Deploy this branch
- [x] Inform to @Clinical-Genomics/data-analysis

### CODE REVIEW

**Comment by moahaegglund** [comment]
@karlnyr this change is only for novaseq, the thresholds for hiseqga and hiseqx should not be changed.

**Comment by karlnyr** [comment]
Flow cell added successfully into the system(no samples were below q30 threshold of 75%)
image

**Review by Mropat — APPROVED** [review]

**Comment by henrikstranneheim** [comment]
@karlnyr This looks good to go! Or is something blocking?

**Comment by moahaegglund** [comment]
Yes we should wait with this. We have discussed this and realised that these thresholds are too strict to set per sample.

**Comment by karlnyr** [comment]
The latest version however is not changing anything from the past version. All I have done is to set the previous qc-params into constants that can later be altered or used for further quality checking.

**Comment by karlnyr** [comment]
@henrikstranneheim @moahaegglund Can we merge this? The PR does not do a lot except add a test for dragen-demux-results as well as transfer the Q30 thresholds into a constant. Else we simply close this PR and delete the branch.

**Comment by henrikstranneheim** [comment]
@karlnyr I think it looks good to go!

**Comment by henrikstranneheim** [comment]
@karlnyr Do you fell ready to merge and deploy this one?

**Comment by karlnyr** [comment]
Installed ion prod:
image

**Pull request merged**
