### PR TITLE
Fix mutant libprep

### PR DESCRIPTION
**Pull request by talnor**
## Description
*This PR changes the method values in the mutant case config. This will now refer to the AM document numbers entered in lims.*

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] us
- [x] cg workflow mutant config-case rightimp
- [x] cg workflow mutant config-case clearhusky

### Expected test outcome
- [x] check that the created config file contains`"method_libprep": "2182:5 - Manual SARS-CoV-2 library preparation using Illumina COVIDseq Test"` and 
        `"method_sequencing": "1830:6 - NovaSeq 6000 Sequencing method"`.
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by
- [x] tests executed by
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by Mropat — APPROVED** [review]

**Comment by Mropat** [comment]
Just let me know when you want this deployed

**Review by mayabrandi — APPROVED** [review]

**Comment by Mropat** [comment]
Hi, it seems our job has been made easier for us in a sense that we can later aggregate the libpreps and sequencer info for each sample, and update the database when the API is finished on their side.
So the only thing we need to test is the method of getting the metadata from lims!
I will transfer some new data to lims stage to test the method later!

**Comment by Mropat** [comment]
```
    {
        "CG_ID_project": "336977",
        "CG_ID_sample": "ACC8232A19",
        "case_ID": "keysnake",
        "region_code": "01",
        "lab_code": "SE100",
        "priority": "priority",
        "Customer_ID_project": 336977,
        "Customer_ID_sample": "Pos-kontroll",
        "customer_id": "cust124",
        "application_tag": "VWGDPTR001",
        "date_arrival": "2021-07-20 00:00:00",
        "date_libprep": "2021-07-20 00:00:00",
        "date_sequencing": "2021-07-22 14:00:38",
        "method_libprep": "2182:8 - Manual SARS-CoV-2 library preparation using Illumina COVIDseq Test",
        "method_sequencing": "1830:7 - NovaSeq 6000 Sequencing method",
        "sequencing_qc_pass": true,
        "selection_criteria": "1. Allm\u00e4n \u00f6vervakning"
    }

```

**Comment by Mropat** [comment]
```
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
balsamic 6.0.0 requires colorclass, which is not installed.
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 22.15.0
housekeeper, version 3.2.0
demux, version 5.10.3
cglims, version 1.3.4
```

**Pull request merged**
