### PR TITLE
Remove unused sample sheet sample fields

### PR DESCRIPTION
**Pull request by seallard**
## Description
Resolves https://github.com/Clinical-Genomics/cg/issues/2459.
This PR removes some of the fields which are not referenced anywhere in cg for samples on the sample sheet model. To make the sample sheet parsing less brittle, it is better to only parse the needed information.

Should these remain? 
- sample_ref
- sample_name
- operator
- recipe
- control
- adapter_read_1
- adapter_read_2

### Fixed
- Remove some unused fields on the sample sheet sampel models

Currently working on an issue with fluffy sample sheets https://github.com/Clinical-Genomics/cg/issues/2456 where it might turn out that some of these are needed - so will hold off on merging until that issue is resolved.

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by ChrOertlin** [comment]
I think the demultiplexing software expects sample sheets to be in a specific format for them to work. That includes some of the columns that would be deleted in this PR.
If I am not mistaken, when we create sample sheets we validate the sample sheets to have a specific structure for the demultiplexing software (i.e. bcl2fastq or bclconvert). So then we would need those columns. @karlnyr , @diitaz93. Is this right?

**Comment by seallard** [comment]
> I think the demultiplexing software expects sample sheets to be in a specific format for them to work. That includes some of the columns that would be deleted in this PR. If I am not mistaken, when we create sample sheets we validate the sample sheets to have a specific structure for the demultiplexing software (i.e. bcl2fastq or bclconvert). So then we would need those columns. @karlnyr , @diitaz93. Is this right?

Ok, so it might be necessary to keep these fields in order for the validation to work correctly?

**Comment by ChrOertlin** [comment]
> 

I think so, yes. Here is the documentation for the BCL convert sample sheet as an example ( https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl_convert/bcl-convert-v3-7-5-software-guide-1000000163594-00.pdf)

**Review by diitaz93 — CHANGES_REQUESTED** [review]
Many columns of the sample sheet are not used, and they are even empty for all samples. But the Illumina software expects these fields to be there otherwise it would raise an error.

**Comment by diitaz93** [comment]
> > I think the demultiplexing software expects sample sheets to be in a specific format for them to work. That includes some of the columns that would be deleted in this PR. If I am not mistaken, when we create sample sheets we validate the sample sheets to have a specific structure for the demultiplexing software (i.e. bcl2fastq or bclconvert). So then we would need those columns. @karlnyr , @diitaz93. Is this right?
> 
> Ok, so it might be necessary to keep these fields in order for the validation to work correctly?

Exactly. Unfortunately we will have to keep those fields

**Comment by seallard** [comment]
> > > I think the demultiplexing software expects sample sheets to be in a specific format for them to work. That includes some of the columns that would be deleted in this PR. If I am not mistaken, when we create sample sheets we validate the sample sheets to have a specific structure for the demultiplexing software (i.e. bcl2fastq or bclconvert). So then we would need those columns. @karlnyr , @diitaz93. Is this right?
> > 
> > 
> > Ok, so it might be necessary to keep these fields in order for the validation to work correctly?
> 
> Exactly. Unfortunately we will have to keep those fields

Good 👍

**Pull request closed without merging**
