### PR TITLE
Small bug fix

### PR DESCRIPTION
**Pull request by mayabrandi**
Sample.no_invoice and Pool.no_invoice are boolean True/False, but can also have the value null.

no_invoice != True will exclude only samples/pools with no_invoice == True. Thats how it should be.

The bug "no_invoice == None" was introduced some PRs ago if I don't remember wrong..?

Pools that need to be invoiced now are not being shown in the invoicing view due to this bug, so pretty important this PR is being merged into prod soon.  

The changes have been tested on cg_stage today by me. 

@ingkebil @patrikgrenfeldt @emiliaol @vwirta

### CODE REVIEW

**Comment by emiliaol** [comment]
Before putting in production can you test the merged master on stage? I had issues logging in to stage api on this branch today

**Comment by mayabrandi** [comment]
Can I merge this one? @ingkebil

**Comment by ingkebil** [comment]
No. Discuss next steps in your meeting with parik later today.

**Comment by mayabrandi** [comment]
I suppose you are suggesting this:
 
Pool model key no_invoice is changed require_invoice. 
And then set models.Pool.require_invoice == True

?

Thats ok with me, but I sugest in a norther PR and that you put it into the next sprint. Don’t want to risk that this fix takes as long as pr #212 to get merged since Valtteri needs to get his invoices sent. What you say?

Best,

M

**Comment by ingkebil** [comment]
I understand that you feel we are slow Maya. Howevee, the result of adopting the cycle of reviewing code is a stable production and better code. Please consider fixing according to the suggestion, test it, deploy it, and adobting the habit :)
Postponing fixing code right away, leaves us with technical debt, which is a state that I want to avoid if possible.

**Comment by mayabrandi** [comment]
Im aware of that. I however didn’t think this cosmetic change was important enough to make any fuss about it. But you decide!

Can someone verify that the changes you want are the following:

Pool model key no_invoice is changed require_invoice. 
And then set models.Pool.require_invoice == True


Best,

Maya

**Comment by ingkebil** [comment]
It's two lines of code. Fix it here and now please

**Comment by mayabrandi** [comment]
Hehe. 

It includes changing the database key and updating all values by writing a sql script to.. So I just wanted to have confirmed that I understood Patrics suggestion correctly before doing that. But I talked to him in person so it is sorted out.

/M

**Comment by ingkebil** [comment]
;) :+1:

**Comment by mayabrandi** [comment]
@patrikgrenfeldt I now did the change we talked about. And added a small script to change Null to False in the database.

**Comment by patrikgrenfeldt** [comment]
We'll done! Have you tested it on stage as well?

**Comment by mayabrandi** [comment]
Okej! Now tested on stage:
https://clinical-api-stage.scilifelab.se/invoices/new/Pool
The expected pools are showing up.

**Comment by mayabrandi** [comment]
Can this be merged now?

**Comment by ingkebil** [comment]
I'll merge and deploy now

**Comment by ingkebil** [comment]
Is in production now!

**Comment by mayabrandi** [comment]
Great! And the pools that we expect now show up! Ill let VW know!

**Pull request merged**
