### PR TITLE
fix upload/conftest

### PR DESCRIPTION
**Pull request by adrosenbaum**
This PR mocks a housekeeper file object correctly, fixes a test, and cleans up unnecessary code in a contest file.

**How to test**:
This PR fixes a test, passing a travis build is a sufficient test.

**Review:**
- [x] code approved by @patrikgrenfeldt 
- [x] tests executed by travis
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This is patch **version bump** because it fixes a test

### CODE REVIEW

**Comment by adrosenbaum** [comment]
Fixes the test we talked about the other day @patrikgrenfeldt 😄

**Comment by patrikgrenfeldt** [comment]
Great, I'll have a look!

Den tors 12 dec. 2019 14:50adrosenbaum <notifications@github.com> skrev:

**Comment by patrikgrenfeldt** [comment]
Great that you removed those redundant mock classes Adam, this improves the maintainability a lot!

**Comment by patrikgrenfeldt** [comment]
deployed

**Pull request merged**
