### PR TITLE
BALSAMIC validation cases to ignore 

### PR DESCRIPTION
**Pull request by hassanfa**
## Description

Organizes validation cases constants to find them easier

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh balsamic_validation_Cases`

### How to test
- [x] do `for c in bosssponge civilsole fleetjay moralgoat sweetelf unitedbeagle; do cg compress fastq -d -c $c; done`

### Expected test outcome
- [x] check that cases are not compressed
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MR
- [x] tests executed by HFA
- [x] "Merge and deploy" approved by MR, HFA
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by Mropat — APPROVED** [review]

**Comment by hassanfa** [comment]
part1:

**Comment by hassanfa** [comment]
part3:
image

**Comment by henrikstranneheim** [comment]
@hassanfa and @Mropat Shall I deploy this one?

**Comment by hassanfa** [comment]
👍🏽  Go for it!

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:
```
[0|0|12] [henrik.stranneheim@hasta:~/git/cg] [P_main] master ± bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-prod.sh
on the host hasta.scilifelab.se, continue
This will install the latest version of clinical-genomics/cg on master in production, are you sure? y/[n]y
Collecting git+https://github.com/clinical-genomics/cg
  Cloning https://github.com/clinical-genomics/cg to /home/henrik.stranneheim/tmp/pip-req-build-o_t0suf_
  Running command git clone -q https://github.com/clinical-genomics/cg /home/henrik.stranneheim/tmp/pip-req-build-o_t0suf_
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: Flask-Admin in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.5.3)
Requirement already satisfied: packaging in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (20.9)
Requirement already satisfied: gunicorn in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (20.0.4)
Requirement already satisfied: typing-extensions in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (3.7.4.3)
Requirement already satisfied: paramiko in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.7.2)
Requirement already satisfied: Flask-Dance in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.3.0)
Requirement already satisfied: pyyaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (5.1)
Requirement already satisfied: marshmallow>3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (3.6.1)
Requirement already satisfied: tabulate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.8.3)
Requirement already satisfied: housekeeper>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (3.2.0)
Requirement already satisfied: colorclass in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.2.0)
Requirement already satisfied: genologics in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.4.3)
Requirement already satisfied: openpyxl in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.6.0)
Requirement already satisfied: cgmodels>=0.6 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.6.0)
Requirement already satisfied: Click<7.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (6.7)
Requirement already satisfied: lxml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (4.3.1)
Requirement already satisfied: Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.2.2)
Requirement already satisfied: requests[security] in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.21.0)
Requirement already satisfied: Flask>=1.1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.1.1)
Requirement already satisfied: coloredlogs in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (10.0)
Requirement already satisfied: setuptools>=39.2.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (40.6.2)
Requirement already satisfied: blinker in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.4)
Requirement already satisfied: werkzeug<1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.16.1)
Requirement already satisfied: Flask-Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.5.0)
Requirement already satisfied: requests-cache in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (0.4.13)
Requirement already satisfied: petname in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.2)
Requirement already satisfied: SQLAlchemy<1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.2.17)
Requirement already satisfied: pyschemes in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.0.0)
Requirement already satisfied: google-auth in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.6.2)
Requirement already satisfied: pydantic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.8.1)
Requirement already satisfied: python-dateutil in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.8.0)
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (2.1)
Requirement already satisfied: Flask-CORS in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (3.0.7)
Requirement already satisfied: email-validator in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.0.1) (1.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==22.0.1) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==22.0.1) (2.11.1)
Requirement already satisfied: ruamel.yaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==22.0.1) (0.15.88)
Requirement already satisfied: rich in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==22.0.1) (6.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.1.1->cg==22.0.1) (1.1.0)
Requirement already satisfied: pydash>=3.4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Alchy->cg==22.0.1) (4.7.4)
Requirement already satisfied: humanfriendly>=4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from coloredlogs->cg==22.0.1) (4.17)
Requirement already satisfied: idna>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==22.0.1) (2.8)
Requirement already satisfied: dnspython>=1.15.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==22.0.1) (2.1.0)
Requirement already satisfied: wtforms in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Admin->cg==22.0.1) (2.2.1)
Requirement already satisfied: Six in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-CORS->cg==22.0.1) (1.13.0)
Requirement already satisfied: urlobject in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.0.1) (2.4.3)
Requirement already satisfied: requests-oauthlib>=1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.0.1) (1.1.0)
Requirement already satisfied: oauthlib in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.0.1) (2.1.0)
Requirement already satisfied: lazy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.0.1) (1.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.0.1) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.0.1) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.0.1) (3.0.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.0.1) (0.2.4)
Requirement already satisfied: rsa>=3.1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.0.1) (4.0)
Requirement already satisfied: cachetools>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.0.1) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth->cg==22.0.1) (0.4.5)
Requirement already satisfied: et-xmlfile in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==22.0.1) (1.0.1)
Requirement already satisfied: jdcal in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==22.0.1) (1.4)
Requirement already satisfied: pyparsing>=2.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from packaging->cg==22.0.1) (2.4.7)
Requirement already satisfied: bcrypt>=3.1.3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.0.1) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.0.1) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.0.1) (2.5)
Requirement already satisfied: cffi>=1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from bcrypt>=3.1.3->paramiko->cg==22.0.1) (1.12.0)
Requirement already satisfied: pycparser in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->cg==22.0.1) (2.19)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=2.5->paramiko->cg==22.0.1) (0.24.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.0.1) (19.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.0.1) (2.6.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.0.1) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.0.1) (0.4.3)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-22.0.1-py3-none-any.whl size=471105 sha256=a07bb2420b24761bf1597c6e0eb3cf4a777b5c14c707e5014333d286b7030efd
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-xsctmb98/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 22.0.0
    Uninstalling cg-22.0.0:
      Successfully uninstalled cg-22.0.0
Successfully installed cg-22.0.1
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/proj/bin/conda/envs/P_main/bin/python -m pip install --upgrade pip' command.
remote: Enumerating objects: 1147, done.
remote: Counting objects: 100% (743/743), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 427 (delta 339), reused 298 (delta 218), pack-reused 0
Receiving objects: 100% (427/427), 46.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (339/339), completed with 132 local objects.
From https://github.com/Clinical-Genomics/cg
   da39efd..c4df595  master     -> origin/master
 * [new branch]      clean_fluffy_analysis_dir -> origin/clean_fluffy_analysis_dir
   c0afd17..77ef372  feat-case-avatar -> origin/feat-case-avatar
 * [new branch]      feat-new-mip-dna-json-for-starlims -> origin/feat-new-mip-dna-json-for-starlims
   440724d..bbed02a  gisaid_kompliteringsfil -> origin/gisaid_kompliteringsfil
   9850337..4736299  rsync_on_slurm -> origin/rsync_on_slurm
   ed6914e..c2a5a5a  slurm_constants -> origin/slurm_constants
 * [new tag]         v22.0.1    -> v22.0.1
Updating da39efd..c4df595
Fast-forward
 .bumpversion.cfg            |  2 +-
 CHANGELOG.md                |  7 +++++++
 cg/constants/compression.py | 54 ++++++++++++++++++++++++++++++++----------------------
 setup.py                    |  2 +-
 4 files changed, 41 insertions(+), 24 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 22.0.1
housekeeper, version 3.2.0
demux, version 5.9.2
cglims, version 1.3.4
```

**Pull request merged**
