### PR TITLE
Apptag vogue

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR adds cli to load applicationtags from status-db to vogue, using vogue CLI

**How to test**:

On hasta
cd /home/proj/stage/servers/resources/hasta.scilifelab.se

1. bash update-servers-stage.sh genotype_vogue

2. bash update-genotype-stage.sh trending

3. bash update-cg-stage.sh apptag-vogue

4. bash update-vogue-stage.sh dateutil

5.  run: 
usestage
export MONGO_URI=mongodb://localhost:27030
export MONGO_DBNAME=vogue-stage
export FLASK_DEBUG=1
export VOGUE_SECRET_KEY=hej
cg -c /home/proj/stage/servers/config/hasta.scilifelab.se/cg-stage.yaml upload trending apptags

**Expected outcome**:
Something like this:
----------------- UPLOAD ----------------------
----------------- TRENDING -----------------------
----------------- APPLICATION TAGS -----------------------
vogue output: INFO:vogue.adapter.plugin:Use database vogue-stage.
vogue output: INFO:vogue.commands.load.application_tag:Reading json.
vogue output: INFO:vogue.commands.load.application_tag:json is read.
vogue output: INFO:vogue.adapter.plugin:No updates for application_tag RMLP10R825.
vogue output: INFO:vogue.adapter.plugin:No updates for application_tag RMLP15R325.
vogue output: INFO:vogue.adapter.plugin:No updates for application_tag RMLP15R825.
vogue output: INFO:vogue.adapter.plugin:No updates for application_tag RMLP15S100.
vogue output: INFO:vogue.adapter.plugin:o updates for application_tag RMLP15S175.
...

**Review:**
- [ ] code approved by
- [x] tests executed by @mayabrandi 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This is a minor bump version since we are not making changes to existing functionality.

### CODE REVIEW

**Comment by ingkebil** [comment]
Can you let us know when we can review this? Your description says that we need to wait until #415 is done. Do you mean merged and in production?

**Comment by mayabrandi** [comment]
I just wanted to save you from reviewing the same code twice. But if you are happy with #415, you can just go ahead and review this one. Thanks

Skickat från min iPhone

**Comment by ingkebil** [comment]
I will wait until PR #415 is merged so we can rebase this PR and actually see the changes. It's hard to figure out what exactly you've added here.

Don't forget to add the suggested changes for cg.yaml and cg-stage.yaml to the servers repo.

Can you execute and document the test yourself? Thanks!

**Comment by mayabrandi** [comment]
I now swhitched branch for this PR and PR #415. @ingkebil

**Comment by ingkebil** [comment]
Yes?

**Comment by ingkebil** [comment]
So the plan would be to merge #415 as soon as it is ready for merging. Then we would see the changes you've made here more easily.

**Comment by mayabrandi** [comment]
Yes, as you suggested on the dev meeting. As far as I understood #415 has been ready for merging for a while already.

**Comment by ingkebil** [comment]
I just checked and there still are comments outstanding. I also just
removed .DS_Store which I asked to be removed.

Could you have another look?

**Comment by mayabrandi** [comment]
Ah. I missed the DS_Store. Not sure what you mean with ”comments outstanding”. And witch comments you are referring to. Perhaps we can sit together so sort this PR out?

> 22 okt. 2019 kl. 16:14 skrev Kenny Billiau <notifications@github.com>:
> 
> I just checked and there still are comments outstanding. I also just
> removed .DS_Store which I asked to be removed.
> 
> Could you have another look?
>

**Comment by ingkebil** [comment]
This can't be right: Coverage decreased 32%! :o

**Pull request closed without merging**
