### PR TITLE
feat(refactor): Use case id as positional arg in linking command

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:
- Use case id as positional arg in linking command
- Standardise mip-dna link and mip-rna link by removing sample id option
- Do not use sub get_links but use same calls as in mip-dna
- Fix mip-dna link help text

### How to prepare for test
- [x] ssh to relevant server hasta
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh fix-mip-link`

### How to test
- [x] do: ` cg workflow mip-rna link sharpparrot`

### Expected test outcome
- [x] check that the fastq files for sample ACC5963A2 are linked to the case sharpparrot
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MR
- [x] tests executed by HS
- [x] "Merge and deploy" approved by MR, HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] There is no current documentation in place for RNA data analysis workflow in production (this will be done as part of the rna-results-in-scout project)

### CODE REVIEW

**Review by Mropat — APPROVED** [review]
😻

**Comment by henrikstranneheim** [comment]
### How to test
` cg workflow mip-rna link sharpparrot`
Screenshot 2021-02-18 at 08 20 19

## Expected test outcome
- [x] check that the fastq files for sample ACC5963A2 are linked to the case sharpparrot ✅

**Comment by henrikstranneheim** [comment]
@jemten FYI

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
```
[0|0|76] [henrik.stranneheim@hasta:~/git/cg] [P_main] master ± bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-prod.sh
on the host hasta.scilifelab.se, continue
This will install the latest version of clinical-genomics/cg on master in production, are you sure? y/[n]y
Collecting git+https://github.com/clinical-genomics/cg
  Cloning https://github.com/clinical-genomics/cg to /home/henrik.stranneheim/tmp/pip-req-build-ht45rveg
  Running command git clone -q https://github.com/clinical-genomics/cg /home/henrik.stranneheim/tmp/pip-req-build-ht45rveg
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: dataclasses<0.8 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.6)
Requirement already satisfied: requests[security] in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.21.0)
Requirement already satisfied: python-dateutil in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.8.0)
Requirement already satisfied: housekeeper>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (3.2.0)
Requirement already satisfied: Flask-Dance in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.3.0)
Requirement already satisfied: setuptools>=39.2.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (40.6.2)
Requirement already satisfied: genologics in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.4.3)
Requirement already satisfied: marshmallow>3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (3.6.1)
Requirement already satisfied: ruamel.yaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.15.88)
Requirement already satisfied: Flask-Admin in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.5.3)
Requirement already satisfied: Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.2.2)
Requirement already satisfied: gunicorn in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (20.0.4)
Requirement already satisfied: openpyxl in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.6.0)
Requirement already satisfied: Click<7.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (6.7)
Requirement already satisfied: google-auth in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.6.2)
Requirement already satisfied: petname in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.2)
Requirement already satisfied: pydantic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pydantic-1.6.1-py3.7.egg (from cg==20.0.0) (1.6.1)
Requirement already satisfied: blinker in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.4)
Requirement already satisfied: lxml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (4.3.1)
Requirement already satisfied: Flask-Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.5.0)
Requirement already satisfied: coloredlogs in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (10.0)
Requirement already satisfied: Flask>=1.1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.1.1)
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.1)
Requirement already satisfied: cgstats>=1.1.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.2.2)
Requirement already satisfied: Flask-CORS in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (3.0.7)
Requirement already satisfied: werkzeug<1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.16.1)
Requirement already satisfied: colorclass in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (2.2.0)
Requirement already satisfied: requests-cache in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.4.13)
Requirement already satisfied: pyschemes in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.0.0)
Requirement already satisfied: typing-extensions in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (3.7.4.3)
Requirement already satisfied: tabulate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (0.8.3)
Requirement already satisfied: SQLAlchemy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.0.0) (1.2.17)
Requirement already satisfied: bumpversion in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (0.5.3)
Requirement already satisfied: alembic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (1.0.7)
Requirement already satisfied: pymysql in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (0.9.3)
Requirement already satisfied: Flask-Bootstrap in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (3.3.7.1)
Requirement already satisfied: bs4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (0.0.1)
Requirement already satisfied: pytest in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (4.2.1)
Requirement already satisfied: wheel in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (0.32.3)
Requirement already satisfied: path.py in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (11.5.0)
Requirement already satisfied: PyYAML in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.0.0) (5.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==20.0.0) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==20.0.0) (2.11.1)
Requirement already satisfied: rich in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==20.0.0) (6.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.1.1->cg==20.0.0) (1.1.0)
Requirement already satisfied: pydash>=3.4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Alchy->cg==20.0.0) (4.7.4)
Requirement already satisfied: python-editor>=0.3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from alembic->cgstats>=1.1.2->cg==20.0.0) (1.0.4)
Requirement already satisfied: Mako in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from alembic->cgstats>=1.1.2->cg==20.0.0) (1.0.7)
Requirement already satisfied: beautifulsoup4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from bs4->cgstats>=1.1.2->cg==20.0.0) (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from beautifulsoup4->bs4->cgstats>=1.1.2->cg==20.0.0) (1.7.3)
Requirement already satisfied: humanfriendly>=4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from coloredlogs->cg==20.0.0) (4.17)
Requirement already satisfied: wtforms in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Admin->cg==20.0.0) (2.2.1)
Requirement already satisfied: visitor in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Bootstrap->cgstats>=1.1.2->cg==20.0.0) (0.1.3)
Requirement already satisfied: dominate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Bootstrap->cgstats>=1.1.2->cg==20.0.0) (2.3.5)
Requirement already satisfied: Six in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-CORS->cg==20.0.0) (1.13.0)
Requirement already satisfied: urlobject in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.0.0) (2.4.3)
Requirement already satisfied: lazy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.0.0) (1.4)
Requirement already satisfied: requests-oauthlib>=1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.0.0) (1.1.0)
Requirement already satisfied: oauthlib in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.0.0) (2.1.0)
Requirement already satisfied: idna<2.9,>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (2018.10.15)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (3.0.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.0.0) (0.2.4)
Requirement already satisfied: cachetools>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.0.0) (3.1.0)
Requirement already satisfied: rsa>=3.1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.0.0) (4.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth->cg==20.0.0) (0.4.5)
Requirement already satisfied: et-xmlfile in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==20.0.0) (1.0.1)
Requirement already satisfied: jdcal in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==20.0.0) (1.4)
Requirement already satisfied: importlib-metadata>=0.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from path.py->cgstats>=1.1.2->cg==20.0.0) (0.8)
Requirement already satisfied: zipp>=0.3.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from importlib-metadata>=0.5->path.py->cgstats>=1.1.2->cg==20.0.0) (0.3.3)
Requirement already satisfied: atomicwrites>=1.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.0.0) (1.3.0)
Requirement already satisfied: py>=1.5.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.0.0) (1.7.0)
Requirement already satisfied: pluggy>=0.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.0.0) (0.8.1)
Requirement already satisfied: more-itertools>=4.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.0.0) (6.0.0)
Requirement already satisfied: attrs>=17.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.0.0) (18.2.0)
Requirement already satisfied: cryptography>=1.3.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (2.5)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.0.0) (19.0.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=1.3.4->requests[security]->cg==20.0.0) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=1.3.4->requests[security]->cg==20.0.0) (0.24.0)
Requirement already satisfied: pycparser in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4->requests[security]->cg==20.0.0) (2.19)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.0.0) (2.6.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.0.0) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.0.0) (0.4.3)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-20.0.0-py3-none-any.whl size=399346 sha256=045af0cdfc0d32a48d9805c6109fe12a32d462708308aaf4f6b354a0f3a7f9da
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-nwbgvveh/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 19.5.4
    Uninstalling cg-19.5.4:
      Successfully uninstalled cg-19.5.4
Successfully installed cg-20.0.0
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 80 (delta 63), reused 71 (delta 56), pack-reused 0
Unpacking objects: 100% (80/80), done.
From https://github.com/Clinical-Genomics/cg
   a0a7565..5867d6c  master     -> origin/master
 * [new branch]      feat-refactor-store-vol-1 -> origin/feat-refactor-store-vol-1
   656e81c..8513fff  pydantic-orderform-parsing -> origin/pydantic-orderform-parsing
 * [new tag]         v20.0.0    -> v20.0.0
Updating a0a7565..5867d6c
Fast-forward
 .bumpversion.cfg                                |  3 ++-
 CHANGELOG.md                                    |  5 +++++
 cg/cli/workflow/mip_dna/base.py                 |  2 +-
 cg/cli/workflow/mip_rna/base.py                 | 22 ++++++++++++----------
 setup.py                                        |  2 +-
 tests/cli/workflow/mip/test_cli_mip_rna_link.py |  2 +-
 6 files changed, 22 insertions(+), 14 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 20.0.0
housekeeper, version 3.2.0
demux, version 5.6.0
cglims, version 1.3.4
```

**Pull request merged**
