### PR TITLE
fest(sql): Refactor handler

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Refactor read handler to CRUD

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b refactor-sql-readhandler -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Looks good, is the `FindBasicData` next?

**Comment by henrikstranneheim** [comment]
> Looks good, is the `FindBasicData` next?

Absolutely 😄

**Comment by henrikstranneheim** [comment]
### cg get case justhusky 👍 
```
henrik.stranneheim@hasta:~] [S_base] 19s $ cg get case justhusky
+-----------+--------------------------------+------------+------------+-----------+----------+
| Case      | Name                           | Customer   | Priority   | Panels    | Action   |
|-----------+--------------------------------+------------+------------+-----------+----------|
| justhusky | SWEDAC-2019-HG-05-Trio-NovaSeq | cust000    | priority   | OMIM-AUTO | running  |
+-----------+--------------------------------+------------+------------+-----------+----------+
+-------------------+----------+----------+
| Sample            | Mother   | Father   |
|-------------------+----------+----------|
| earlycasualcaiman |          |          |
+-------------------+----------+----------+
+-----------------+----------+----------+
| Sample          | Mother   | Father   |
|-----------------+----------+----------|
| slowlycivilbuck |          |          |
+-----------------+----------+----------+
+----------------+-----------------+-------------------+
| Sample         | Mother          | Father            |
|----------------+-----------------+-------------------|
| hugelymodelbat | slowlycivilbuck | earlycasualcaiman |
+----------------+-----------------+-------------------+
+-------------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample            | Name            | Customer   | Application   | State              | Priority   | External?   |
|-------------------+-----------------+------------+---------------+--------------------+------------+-------------|
| earlycasualcaiman | ACC5339A2--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+-------------------+-----------------+------------+---------------+--------------------+------------+-------------+
+-----------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample          | Name            | Customer   | Application   | State              | Priority   | External?   |
|-----------------+-----------------+------------+---------------+--------------------+------------+-------------|
| slowlycivilbuck | ACC5339A3--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+-----------------+-----------------+------------+---------------+--------------------+------------+-------------+
+----------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample         | Name            | Customer   | Application   | State              | Priority   | External?   |
|----------------+-----------------+------------+---------------+--------------------+------------+-------------|
| hugelymodelbat | ACC5339A4--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+----------------+-----------------+------------+---------------+--------------------+------------+-------------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2023-12-07 10:32:30 | mip-dna    | 12.0.3    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2023-05-04 10:11:56 | mip-dna    | 11.2.0    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2023-03-29 14:55:02 | mip-dna    | 11.1.2    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2022-11-24 11:32:28 | mip-dna    | 11.0.3    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2021-08-18 14:19:23 | mip-dna    | 10.2.0    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2021-06-09 15:15:11 | mip-dna    | 10.0.1    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2020-02-20 14:47:52 | mip-dna    | v8.2.1    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Pipeline   | Version   |
|---------------------+------------+-----------|
| 2019-06-11 10:48:07 | mip-dna    | v6.0.20   |
+---------------------+------------+-----------+

```

**Comment by henrikstranneheim** [comment]
Deployed to production:
```
Log deploy... done.
cg, version 55.3.7
```

**Pull request merged**
