### PR TITLE
Filter mutacc cases by customer ID

### PR DESCRIPTION
**Pull request by adrosenbaum**
This PR adds a option to only process certain customers by mutacc

Added option `-C/--customers` to command 'cg upload process-solved' to filter cases by owning customer. Several customer IDs can be passed repeating the option, e.g. `... -C cust_1 -C cust_2`.

**How to test**:
1. install on stage : `bash /home/proj/stage/servers/resources/hasta.scilifelab.se/update-cg-stage.sh mutacc-cust-filter`
1. activate stage: `us`
1. run `cg upload process-solved --dry-run --days-ago 100 -C cust12345`
1. run `cg upload process-solved --dry-run --days-ago 100 -C cust000`
1. run `cg upload process-solved --dry-run --days-ago 100 -C cust002`
1. run `cg upload process-solved --dry-run --days-ago 100 -C cust000 -C cust002`
1. run `cg upload process-solved --dry-run --days-ago 100`

**Expected outcome**:
Running `cg upload process-solved --dry-run --days-ago 100 -C cust12345` should log that all cases that are found are skipped (since no case belongs to customer 'cust12345').

Running `cg upload process-solved --dry-run --days-ago 100 -C cust000` should log that only the cases belonging to cust000 would be processed, all other are skipped.

Running `cg upload process-solved --dry-run --days-ago 100 -C cust002` should log that only the cases belonging to cust002 would be processed, all other are skipped.

Running `cg upload process-solved --dry-run --days-ago 100 -C cust000 -C cust002` should log that only the cases belonging to cust002 or cust000 would be processed, all other are skipped.

Running `cg upload process-solved --dry-run --days-ago 100` Should log that all cases found would be processed

**outcome**
```
[S_main] 16s $ cg upload process-solved --dry-run --days-ago 100 -C cust12345
----------------- UPLOAD ----------------------
----------------- PROCESS-SOLVED ----------------
skipping casualgannet: Not valid customer cust000
skipping cuddlyoryx: Not valid customer cust002
skipping cust000-15026-miptest: Not valid customer cust000
skipping easybeetle: Not valid customer cust002
skipping epicasp: Not valid customer cust002
skipping firstfawn: Not valid customer cust002
skipping grownliger: Not valid customer cust002
skipping hotskink: Not valid customer cust002
skipping rightmacaw: Not valid customer cust002
skipping strongbison: Not valid customer cust000
skipping topsrhino: Not valid customer cust002
skipping usablemarten: Not valid customer cust002
skipping vitalmouse: Not valid customer cust002
[S_main] 15s $ cg upload process-solved --dry-run --days-ago 100 -C cust000
----------------- UPLOAD ----------------------
----------------- PROCESS-SOLVED ----------------
Would process case casualgannet with mutacc
skipping cuddlyoryx: Not valid customer cust002
Would process case cust000-15026-miptest with mutacc
skipping easybeetle: Not valid customer cust002
skipping epicasp: Not valid customer cust002
skipping firstfawn: Not valid customer cust002
skipping grownliger: Not valid customer cust002
skipping hotskink: Not valid customer cust002
skipping rightmacaw: Not valid customer cust002
Would process case strongbison with mutacc
skipping topsrhino: Not valid customer cust002
skipping usablemarten: Not valid customer cust002
skipping vitalmouse: Not valid customer cust002
[S_main] 4s $ cg upload process-solved --dry-run --days-ago 100 -C cust002
----------------- UPLOAD ----------------------
----------------- PROCESS-SOLVED ----------------
skipping casualgannet: Not valid customer cust000
Would process case cuddlyoryx with mutacc
skipping cust000-15026-miptest: Not valid customer cust000
Would process case easybeetle with mutacc
Would process case epicasp with mutacc
Would process case firstfawn with mutacc
Would process case grownliger with mutacc
Would process case hotskink with mutacc
Would process case rightmacaw with mutacc
skipping strongbison: Not valid customer cust000
Would process case topsrhino with mutacc
Would process case usablemarten with mutacc
Would process case vitalmouse with mutacc
[S_main] 2s $ cg upload process-solved --dry-run --days-ago 100 -C cust000 -C cust002
----------------- UPLOAD ----------------------
----------------- PROCESS-SOLVED ----------------
Would process case casualgannet with mutacc
Would process case cuddlyoryx with mutacc
Would process case cust000-15026-miptest with mutacc
Would process case easybeetle with mutacc
Would process case epicasp with mutacc
Would process case firstfawn with mutacc
Would process case grownliger with mutacc
Would process case hotskink with mutacc
Would process case rightmacaw with mutacc
Would process case strongbison with mutacc
Would process case topsrhino with mutacc
Would process case usablemarten with mutacc
Would process case vitalmouse with mutacc
[S_main] 17s $ cg upload process-solved --dry-run --days-ago 100
----------------- UPLOAD ----------------------
----------------- PROCESS-SOLVED ----------------
Would process case casualgannet with mutacc
Would process case cuddlyoryx with mutacc
Would process case cust000-15026-miptest with mutacc
Would process case easybeetle with mutacc
Would process case epicasp with mutacc
Would process case firstfawn with mutacc
Would process case grownliger with mutacc
Would process case hotskink with mutacc
Would process case rightmacaw with mutacc
Would process case strongbison with mutacc
Would process case topsrhino with mutacc
Would process case usablemarten with mutacc
Would process case vitalmouse with mutacc

```

**Review:**
- [x] code approved by @ingkebil 
- [x] tests executed by @adrosenbaum 
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because because a feature is added in a backwards compatible manner

### CODE REVIEW

**Comment by adrosenbaum** [comment]
Hi guys. Added a small change to the CLI, allowing the user to specify what customers should be processed by mutacc. Would be great if you have time to look at this.

**Comment by ingkebil** [comment]
Nice going!

My first remark would be that we have named what you call institutes customers throughout the code, e.g. in invoicing. I would rename that. What do yuo think?

**Comment by ingkebil** [comment]
Code looks good! :rocket:

**Comment by adrosenbaum** [comment]
> My first remark would be that we have named what you call institutes customers throughout the code, e.g. in invoicing.

Sounds good, will rename option to `-C/--customers` 

thanks!

**Comment by adrosenbaum** [comment]
Tested. Works fine. 👍

**Comment by ingkebil** [comment]
Perfect! approved.

I can push it to production

**Comment by ingkebil** [comment]
deployed

**Comment by barrystokman** [comment]
3e73kv

Good job guys :bat:

**Pull request merged**
