### PR TITLE
Update PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes some challenges in using the current PR-template

**How to test**:
- [x] Read the PR-template

**Expected test outcome**:
- [x] check that it makes sense and feels better the previous one
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [x] tests executed by @henrikstranneheim 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Screenshot: 
bild

👍

**Comment by patrikgrenfeldt** [comment]
@barrystokman could you merge & bump this PR?

**Comment by barrystokman** [comment]
Merged, bumped and ready to rock :metal:

**Comment by patrikgrenfeldt** [comment]
Awesome. Thanks!

Den mån 17 feb. 2020 11:50Barry Stokman <notifications@github.com> skrev:

**Pull request merged**
