### PR TITLE
Add data archive location to Customer table

### PR DESCRIPTION
**Pull request by islean**
## Description

We need to deliver and archive data for different customers at different locations.

For instance K customers should get data to Ks' Ceph storage while KI customers should use PDC.

### Added

- Field to Customer table called "data_archive_location" with type str(32).
- Alembic revision to reflect the change.

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b add-data-archive-location-to-customer-table -a
    ```

### How to test

- [x] Verify that the table "customer" now has a column called "data_archive_location" with type str(32).
- [x] Redeploy master.
- [x] Verify that the table "customer" no longer has the added column.

### Expected test outcome

- [x] customer table is modified successfully.
- [x] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by islean** [comment]
Main thing to discuss is type and default value. My thought is that 32 characters will be enough but feel free to give input. I will probably modify to give a default value of "PDC" also.

**Review by ChrOertlin — APPROVED** [review]
Looks good, is this column supposed to be viewable in statusdb? if so, you might need to make changes in the view of this table.

**Comment by Vince-janv** [comment]
> > Looks good, is this column supposed to be viewable in statusdb? if so, you might need to make changes in the view of this table.
> 
> Good question - any input @Vince-janv ?

Yep, that would be nice but feel free to have that in a separate PR later

**Comment by islean** [comment]
image
image

```
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 84 (delta 49), reused 69 (delta 44), pack-reused 0
Unpacking objects: 100% (84/84), done.
From github.com:Clinical-Genomics/cg
   dfa78ff..e471be8  add-data-archive-location-to-customer-table -> origin/add-data-archive-location-to-customer-table
   b55c3e5..bb6346a  delete-flow-cell-slsm -> origin/delete-flow-cell-slsm
Already on 'add-data-archive-location-to-customer-table'
Your branch is behind 'origin/add-data-archive-location-to-customer-table' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating dfa78ff..e471be8
Fast-forward
 alembic/versions/c3fdf3a8a5b3_add_data_archive_location.py | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)
/home/isak.ohlsson
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade ffb9f8ab8e62 -> c3fdf3a8a5b3, add data archive location
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 38.0.2
```

```
Switched to branch 'master'
Your branch is behind 'origin/master' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating f01dc22..57ec7a8
Fast-forward
 .bumpversion.cfg                                         |   2 +-
 cg/__init__.py                                           |   2 +-
 cg/apps/scout/scoutapi.py                                |   4 +-
 cg/meta/demultiplex/demux_post_processing.py             | 307 +++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------------------------------
 cg/meta/demultiplex/utils.py                             | 131 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 cg/meta/demultiplex/validation.py                        |  70 ++++++++++++++++++++++++++++++
 cg/meta/upload/scout/uploadscoutapi.py                   | 237 +++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 setup.py                                                 |   2 +-
 tests/meta/demultiplex/conftest.py                       |   2 +-
 tests/meta/demultiplex/test_demux_post_processing.py     | 266 ++++++++++++++++++++++------------------------------------------------------------------------------------------
 tests/meta/demultiplex/test_utils.py                     | 325 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/meta/demultiplex/test_validation.py                | 159 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/meta/upload/scout/test_meta_upload_scoutapi_rna.py | 146 ++++++++++++++++++++++++--------------------------------------
 13 files changed, 1040 insertions(+), 613 deletions(-)
 create mode 100644 cg/meta/demultiplex/utils.py
 create mode 100644 cg/meta/demultiplex/validation.py
 create mode 100644 tests/meta/demultiplex/test_utils.py
 create mode 100644 tests/meta/demultiplex/test_validation.py
/home/isak.ohlsson
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 38.0.2
```

**Comment by islean** [comment]
Both upgrade and downgrade worked as expected with the column being populated with PDC and being non-nullable:

image

**Review by Vince-janv — APPROVED** [review]
Looks great! ⭐

**Comment by islean** [comment]
Deployed to stage and production by IO, 2023-07-06.

**Pull request merged**
