### PR TITLE
Remove remnant sars-cov-2 workflow occurence in order table (Fix #3179)

### LINKED ISSUE #3179: sars-cov-2 still available as option in order table
## Description

The sars-cov-2 pipeline is reportedly refactored into the mutant pipeline, and should not be available in the database structure for StatusDB. It is still available in the order table though.

## How to see it

1. Dump out the database structure for StatusDB into a a file `cg-stage.structure.sql`:
```
mysqldump -u stageuser -p -h 127.0.0.1 -P 18002 cg-stage --no-data > cg-stage.structure.sql
```
2. Grep the file for some pipeline that occurs in all relevant fields:
```
grep microsalt cg-stage.structure.sql
```

### Actual outcome

The output includes `sars-cov-2` in one field:
```
  `workflow` enum('balsamic','balsamic-pon','balsamic-qc','balsamic-umi','demultiplex','fastq','fluffy','microsalt','mip-dna','mip-rna','mutant','raredisease','rnafusion','rsync','spring','taxprofiler','tomte') DEFAULT NULL,
  `workflow` enum('balsamic','balsamic-pon','balsamic-qc','balsamic-umi','demultiplex','fastq','fluffy','microsalt','mip-dna','mip-rna','mutant','raredisease','rnafusion','rsync','spring','taxprofiler','tomte') DEFAULT NULL,
  `data_analysis` enum('balsamic','balsamic-pon','balsamic-qc','balsamic-umi','demultiplex','fastq','fluffy','microsalt','mip-dna','mip-rna','mutant','raredisease','rnafusion','rsync','spring','taxprofiler','tomte') DEFAULT NULL,
  `workflow` enum('balsamic','balsamic-pon','balsamic-qc','balsamic-umi','demultiplex','fastq','fluffy','microsalt','mip-dna','mip-rna','mutant','raredisease','rnafusion','rsync','spring','taxprofiler','sars-cov-2','tomte') DEFAULT NULL,
```

### Expected outcome

`sars-cov-2` should not be included there.

## Suggested solution

Create an alembic script for removing that, or update the mutant refactoring script to remove it there, if possible.

## This can be closed when

The `sars-cov-2` workflow is no longer present in the database structure of the StatusDB.

### PR DESCRIPTION
**Pull request by samuell**
### Fixed

- See #3179 

### How to prepare for test

- [x] Ssh to hasta (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [x] Dump structure of hasta database
  ```
  mysqldump -u <user> -p -h 127.0.0.1 -P 18002 <dbname> --no-data > <dbname>.structure.sql
  ```
- [x] Grep for `sars-cov-2`:
  ```
  grep sars-cov-2 <dbname>.structure.sql
  ```

### Expected test outcome

- [x] Ensure that no occurence of the `sars-cov-2` string appears.
- [x] Take a screenshot and attach or copy/paste the output:

image

- [x] Ensure that the removed `sars-cov-2` is the only thing changed by doing a diff between the database structure before and after
- [x] Take a screenshot and attach or copy/paste the output:

image

## Review

- [x] Tests executed by SHL
- [ ] "Merge and deploy" approved by

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] ~Document in ...~
- [ ] Deploy this branch on hasta
- [ ] Inform to `#cg-core-dev`

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Nice, 👍 . I also think we should do a separate script (not alembic) to change sars-cov-2 to mutant. @Vince-janv We have changed to mutant in the order form, right?

**Comment by samuell** [comment]
Thank you @henrikstranneheim !

> @Vince-janv We have changed to mutant in the order form, right?

Exactly. This seems to have been just a remnant from that.

> I also think we should do a separate script (not alembic) to change sars-cov-2 to mutant.

Aha, you mean occurences in the code?

**Comment by henrikstranneheim** [comment]
> > I also think we should do a separate script (not alembic) to change sars-cov-2 to mutant.
> 
> Aha, you mean occurences in the code?

Yes, if there are any and also the database values.

**Comment by samuell** [comment]
> > > I also think we should do a separate script (not alembic) to change sars-cov-2 to mutant.
> > 
> > 
> > Aha, you mean occurences in the code?
> 
> Yes, if there are any and also the database values.

Right! But we'd do that in a separate PR right?

**Pull request merged**
