### PR TITLE
Add downsampled case to same order as original

### PR DESCRIPTION
**Pull request by islean**
## Description

We now expect every order to have at least one entry in the order_case table, tying it to an order. This does not happen when samples are downsampled which eventually leads to crashes, for example when trying to add analyses to Trailblazer. This PR ties the downsampled case to the latest order the original case was included in.

### Fixed

- Downsampled cases are added to the same order as the latest order for the original case.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b patch-order-case-downsample -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by islean** [comment]
Do we know that the latest order of the original case is the correct one?

**Comment by islean** [comment]
> Do we know that the latest order of the original case is the correct one?

That is the current behaviour so I say yes. See how ticket is set below:

image

**Review by ChrOertlin — APPROVED** [review]
Looks good!

**Comment by islean** [comment]
Tested in stage:

`justhusky` was downsampled and new case `luckytermite` was created. It was coupled to `justhusky`'s latest ticket via order_case:

image

**Pull request merged**
