### PR TITLE
feat(gene_panel): Update master list with "DIAB" and "NBS-M"

### PR DESCRIPTION
**Pull request by karlnyr**
## Description
*This PR adds/fixes:*
- DIAB and NBS-M to master list of gene panels
- Orders the master list alphabetically 

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh update_master_list`

### How to test
- [x] `cg workflow mip-dna panel -d vitalmouse`

### Expected test outcome
- [x] cg tries to connect to scout with the new panels
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS, MR
- [x] tests executed by HS
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by Mropat — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
- `cg workflow mip-dna panel -d vitalmouse`: ✅ 
```
[0|0|49] [henrik.stranneheim@hasta:~] [S_main] 33s $ cg workflow mip-dna panel -d vitalmouse > gene_panel.bed
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
2021-03-11 08:11:48 hasta.scilifelab.se cg.utils.commands[182514] INFO Running command /home/proj/bin/conda/envs/S_scout/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml export panel --bed BRAIN Cardiology CTD DIAB ENDO EP IBMFS IEM IF mcarta MHT MIT MOVE mtDNA NBS-M NEURODEG NMD PEDHEP PID PIDCAD OMIM-AUTO SKD
```

- Exported panels DIAB and NBS-M ✅ 
```
[0|0|49] [henrik.stranneheim@hasta:~] [S_main] $ head -100 gene_panel.bed
##genome_build=37
##gene_panel=BRAIN,version=1.0,updated_at=2020-02-14,display_name=BRAIN
##gene_panel=Cardiology,version=1.0,updated_at=2020-01-21,display_name=Cardiology
##gene_panel=CTD,version=55.0,updated_at=2017-11-27,display_name=Connective Tissue Diseases
##gene_panel=DIAB,version=17.0,updated_at=2021-03-10,display_name=DIAB
##gene_panel=ENDO,version=12.0,updated_at=2018-02-05,display_name=Endocrinology
##gene_panel=EP,version=14.0,updated_at=2020-01-29,display_name=Epilepsy
##gene_panel=IBMFS,version=13.0,updated_at=2018-01-31,display_name=Inherited Bone Marrow Failure Syndromes
##gene_panel=IEM,version=16.0,updated_at=2020-02-17,display_name=Inborn Errors of Metabolism
##gene_panel=IF,version=1.0,updated_at=2018-10-31,display_name=Intellektuell funktionsnedsättning
##gene_panel=mcarta,version=1.0,updated_at=2019-11-27,display_name=Mitocarta
##gene_panel=MHT,version=1.0,updated_at=2021-02-05,display_name=Malign Hypertermi
##gene_panel=MIT,version=12.0,updated_at=2018-02-05,display_name=Mitochondrial nuclear
##gene_panel=MOVE,version=1.0,updated_at=2020-08-21,display_name=Movement disorders
##gene_panel=mtDNA,version=8.0,updated_at=2015-11-30,display_name=Mitochondrial DNA
##gene_panel=NBS-M,version=17.0,updated_at=2021-03-10,display_name=NBS-M
##gene_panel=NEURODEG,version=1.0,updated_at=2019-05-27,display_name=Neurodegeneration
##gene_panel=NMD,version=66.0,updated_at=2018-12-18,display_name=Neuromuscular diseases
##gene_panel=PEDHEP,version=12.0,updated_at=2018-02-16,display_name=Pediatric Hepatology
##gene_panel=PID,version=14.0,updated_at=2018-01-02,display_name=Primary Immune Deficiency
##gene_panel=PIDCAD,version=11.1,updated_at=2016-09-28,display_name=PID Candidates
##gene_panel=OMIM-AUTO,version=8.0,updated_at=2021-02-08,display_name=OMIM-AUTO
##gene_panel=SKD,version=65.0,updated_at=2018-05-07,display_name=Skeletal dysplasia
##contig=1
##contig=2
##contig=3
##contig=4
##contig=5
##contig=6
##contig=7
##contig=8
##contig=9
##contig=10
##contig=11
##contig=12
##contig=13
##contig=14
##contig=15
##contig=16
##contig=17
##contig=18
##contig=19
##contig=20
##contig=21
##contig=22
##contig=X
##contig=Y
##contig=MT
#chromosome	gene_start	gene_stop	hgnc_id	hgnc_symbol
1	948803	949920	4053	ISG15
```

**Comment by henrikstranneheim** [comment]
@karlnyr Good to go!

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:
```
[0|0|22] θ60° [henrik.stranneheim@hasta:/home/proj/production/servers/resources/hasta.scilifelab.se] [P_main] master(6)* 4s ± bash update-cg-prod.sh
on the host hasta.scilifelab.se, continue
This will install the latest version of clinical-genomics/cg on master in production, are you sure? y/[n]y
Collecting git+https://github.com/clinical-genomics/cg
  Cloning https://github.com/clinical-genomics/cg to /home/henrik.stranneheim/tmp/pip-req-build-gg6eyp14
  Running command git clone -q https://github.com/clinical-genomics/cg /home/henrik.stranneheim/tmp/pip-req-build-gg6eyp14
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: Flask>=1.1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.1.1)
Requirement already satisfied: petname in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.2)
Requirement already satisfied: tabulate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.8.3)
Requirement already satisfied: Flask-Dance in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.3.0)
Requirement already satisfied: SQLAlchemy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.2.17)
Requirement already satisfied: python-dateutil in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.8.0)
Requirement already satisfied: lxml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (4.3.1)
Requirement already satisfied: gunicorn in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (20.0.4)
Requirement already satisfied: Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.2.2)
Requirement already satisfied: Click<7.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (6.7)
Requirement already satisfied: google-auth in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.6.2)
Requirement already satisfied: ruamel.yaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.15.88)
Requirement already satisfied: colorclass in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.2.0)
Requirement already satisfied: requests[security] in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.21.0)
Requirement already satisfied: setuptools>=39.2.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (40.6.2)
Requirement already satisfied: coloredlogs in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (10.0)
Requirement already satisfied: marshmallow>3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (3.6.1)
Requirement already satisfied: openpyxl in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.6.0)
Requirement already satisfied: Flask-Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.5.0)
Requirement already satisfied: dataclasses<0.8 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.6)
Requirement already satisfied: cgmodels in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.2.1)
Requirement already satisfied: Flask-CORS in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (3.0.7)
Requirement already satisfied: Flask-Admin in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.5.3)
Requirement already satisfied: genologics in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.4.3)
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (2.1)
Requirement already satisfied: pyschemes in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.0.0)
Requirement already satisfied: blinker in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.4)
Requirement already satisfied: housekeeper>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (3.2.0)
Requirement already satisfied: pydantic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.8.1)
Requirement already satisfied: typing-extensions in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (3.7.4.3)
Requirement already satisfied: requests-cache in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.4.13)
Requirement already satisfied: cgstats>=1.1.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (1.2.2)
Requirement already satisfied: werkzeug<1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==20.7.0) (0.16.1)
Requirement already satisfied: bs4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (0.0.1)
Requirement already satisfied: pytest in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (4.2.1)
Requirement already satisfied: PyYAML in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (5.1)
Requirement already satisfied: alembic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (1.0.7)
Requirement already satisfied: pymysql in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (0.9.3)
Requirement already satisfied: wheel in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (0.32.3)
Requirement already satisfied: bumpversion in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (0.5.3)
Requirement already satisfied: Flask-Bootstrap in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (3.3.7.1)
Requirement already satisfied: path.py in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cgstats>=1.1.2->cg==20.7.0) (11.5.0)
Requirement already satisfied: itsdangerous>=0.24 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==20.7.0) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==20.7.0) (2.11.1)
Requirement already satisfied: rich in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==20.7.0) (6.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.1.1->cg==20.7.0) (1.1.0)
Requirement already satisfied: pydash>=3.4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Alchy->cg==20.7.0) (4.7.4)
Requirement already satisfied: python-editor>=0.3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from alembic->cgstats>=1.1.2->cg==20.7.0) (1.0.4)
Requirement already satisfied: Mako in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from alembic->cgstats>=1.1.2->cg==20.7.0) (1.0.7)
Requirement already satisfied: beautifulsoup4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from bs4->cgstats>=1.1.2->cg==20.7.0) (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from beautifulsoup4->bs4->cgstats>=1.1.2->cg==20.7.0) (1.7.3)
Requirement already satisfied: humanfriendly>=4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from coloredlogs->cg==20.7.0) (4.17)
Requirement already satisfied: wtforms in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Admin->cg==20.7.0) (2.2.1)
Requirement already satisfied: dominate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Bootstrap->cgstats>=1.1.2->cg==20.7.0) (2.3.5)
Requirement already satisfied: visitor in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Bootstrap->cgstats>=1.1.2->cg==20.7.0) (0.1.3)
Requirement already satisfied: Six in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-CORS->cg==20.7.0) (1.13.0)
Requirement already satisfied: requests-oauthlib>=1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.7.0) (1.1.0)
Requirement already satisfied: oauthlib in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.7.0) (2.1.0)
Requirement already satisfied: lazy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.7.0) (1.4)
Requirement already satisfied: urlobject in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==20.7.0) (2.4.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (2018.10.15)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (1.24.1)
Requirement already satisfied: cachetools>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.7.0) (3.1.0)
Requirement already satisfied: rsa>=3.1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.7.0) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==20.7.0) (0.2.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth->cg==20.7.0) (0.4.5)
Requirement already satisfied: et-xmlfile in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==20.7.0) (1.0.1)
Requirement already satisfied: jdcal in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==20.7.0) (1.4)
Requirement already satisfied: importlib-metadata>=0.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from path.py->cgstats>=1.1.2->cg==20.7.0) (0.8)
Requirement already satisfied: zipp>=0.3.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from importlib-metadata>=0.5->path.py->cgstats>=1.1.2->cg==20.7.0) (0.3.3)
Requirement already satisfied: more-itertools>=4.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.7.0) (6.0.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.7.0) (1.3.0)
Requirement already satisfied: pluggy>=0.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.7.0) (0.8.1)
Requirement already satisfied: attrs>=17.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.7.0) (18.2.0)
Requirement already satisfied: py>=1.5.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pytest->cgstats>=1.1.2->cg==20.7.0) (1.7.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (19.0.0)
Requirement already satisfied: cryptography>=1.3.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==20.7.0) (2.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=1.3.4->requests[security]->cg==20.7.0) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=1.3.4->requests[security]->cg==20.7.0) (1.12.0)
Requirement already satisfied: pycparser in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4->requests[security]->cg==20.7.0) (2.19)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.7.0) (2.6.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.7.0) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.7.0) (0.4.3)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-20.7.0-py3-none-any.whl size=398790 sha256=304b91a0e1b9799f9481998916354c8084769dcf5789dad1e4d4a47b4f5ece56
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-4hlhtx3_/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 20.6.0
    Uninstalling cg-20.6.0:
      Successfully uninstalled cg-20.6.0
Successfully installed cg-20.7.0
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 358 (delta 248), reused 245 (delta 238), pack-reused 93
Receiving objects: 100% (358/358), 68.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (292/292), completed with 124 local objects.
From https://github.com/Clinical-Genomics/cg
   3828836..5d82d0e  master     -> origin/master
   5e3f7e6..952ef90  feat/create-old-delivery-reports -> origin/feat/create-old-delivery-reports
 * [new tag]         v20.7.0    -> v20.7.0
Updating 3828836..5d82d0e
Fast-forward
 .bumpversion.cfg           | 3 ++-
 CHANGELOG.md               | 8 +++++++-
 cg/constants/gene_panel.py | 6 ++++--
 setup.py                   | 2 +-
 4 files changed, 14 insertions(+), 5 deletions(-)
/home/proj/production/servers/resources/hasta.scilifelab.se
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is dirty
# On branch master
# Your branch is ahead of 'origin/master' by 6 commits.
#   (use "git push" to publish your local commits)
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	cg/
nothing added to commit but untracked files present (use "git add" to track)
This deletes any changed/untracked files, are you sure? y/[n]y
HEAD is now at 75919df Merge branch 'master' of https://github.com/Clinical-Genomics/servers
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/proj/production/servers/resources/hasta.scilifelab.se
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 20.7.0
housekeeper, version 3.2.0
demux, version 5.6.1
cglims, version 1.3.4
```

**Pull request merged**
