### PR TITLE
remove dead dependency blinker

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
*This PR adds/fixes ...*
- remove dead dependency blinker 

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [x] pip uninstall blinker
- [x] pip uninstall colorclass, leftover from #1196 

### How to test
- [x] ssh hasta
- [x] us
- [x] cg --version

### Expected test outcome
- [x] check that the command works
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] pip uninstall blinker in production
- [ ] pip uninstall colorclass in production, leftover from #1196
- [ ] Inform to ES

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍! It was not even used in the code, 👿 ?

**Comment by patrikgrenfeldt** [comment]
Test result:
image
🆗 CLI still works

**Comment by moonso** [comment]
Really nice that you remove these packages @patrikgrenfeldt ! 
I suggest to add one line to the *how to prepare for test*, namely after `us`

- `pip uninstall <package>`

And make sure that the manual tests work. Otherwise we have not really tested the remove of the package since it will exist in the environment.

**Comment by patrikgrenfeldt** [comment]
> 👍! It was not even used in the code, 👿 ?

nope

**Comment by patrikgrenfeldt** [comment]
Test result after colorclass removal:
image
🆗 no missing dependencies reported

**Comment by patrikgrenfeldt** [comment]
Installation on clinical-db:
image
🚫 blinker is needed by FLASK and cannot be uninstalled

**Pull request merged**
