### PR TITLE
Fix volume type

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR fixes an issue for the parsing of a volume for a sample in a order.

### Fixed
-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by diitaz93** [comment]
Im not 100% sure this will solve the issue

**Comment by diitaz93** [comment]
what if we add a validator that turns ints into strings or vice versa?

**Review by diitaz93 — APPROVED** [review]
Let's give it a try as it is urgent for the customer, but I say this needs further investigation

**Review by islean — APPROVED** [review]
Should probably work! What I did for another field (but I must have missed this one) is to use a BeforeValidator(lambda x: str(x)) to coerce the int to a string

**Comment by diitaz93** [comment]
> Should probably work! What I did for another field (but I must have missed this one) is to use a BeforeValidator(lambda x: str(x)) to coerce the int to a string

That would be better, right?

**Comment by islean** [comment]
> > Should probably work! What I did for another field (but I must have missed this one) is to use a BeforeValidator(lambda x: str(x)) to coerce the int to a string
> 
> That would be better, right?

Potentially, if the volume is not necessarily an int

**Comment by diitaz93** [comment]
there is a validation in teh excel order like this:
```python
volume: Annotated[str, AfterValidator(numeric_value)] = Field(None, alias="UDF/Volume (uL)")
```
but is not present in the jason sample. Should we do it too?

**Comment by seallard** [comment]
> there is a validation in teh excel order like this:
> 
> ```python
> volume: Annotated[str, AfterValidator(numeric_value)] = Field(None, alias="UDF/Volume (uL)")
> ```
> 
> but is not present in the jason sample. Should we do it too?

Yes, I think @islean is adding it now

**Comment by Vince-janv** [comment]
Nice patch. Testing should be quite easy given that she sent us the json file 👍

**Comment by islean** [comment]
> there is a validation in the excel sample like this:
> 
> ```python
> volume: Annotated[str, AfterValidator(numeric_value)] = Field(None, alias="UDF/Volume (uL)")
> ```
> 
> but is not present in the jason sample. Should we do it too?

An AfterValidator will not work in this case since that would be performed after Pydantics type check (I think), but I added a before validator with string coercion now

**Pull request merged**
