### PR TITLE
post process files

### PR DESCRIPTION
**Pull request by moonso**
## Description
- Copy sample sheet to demux results dir
- Create copycomplete.txt

### Expected test outcome
- [ ] check that `copycomplete.txt` and `SampleSheet.csv` exists after demuxed flowcell has been post processed
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS, BS
- [x] "Merge and deploy" approved by MM
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by barrystokman — APPROVED** [review]

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by barrystokman** [comment]
@moonso was this deployed?

**Comment by henrikstranneheim** [comment]
```
Thu May 20 15:54:09 CEST 2021	mans.magnusson	clinical-genomics/cg	cg, version 21.7.1	cg, version 21.7.2	Bump version: 21.7.1 → 21.7.2	fd36a2277ff30c903d4f2f926936a5834872e6a8	current_version = 5.36.4
```

**Comment by moonso** [comment]
Yes!

**Pull request merged**
