### PR TITLE
feat(RNA): Add more positive controls to VALIDATION_CASES

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description
*This PR adds/fixes ...*

- Add more positive controls to VALIDATION_CASES

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh rna_positive_controls`

### How to test
- [x] do `housekeeper get bundle -v merelyvitalfrog`
- [x] do `housekeeper get bundle -v jollyboldraven`
- [x] do `housekeeper get bundle -v earlyamuseddane`
- [x] do `cg compress fastq -d -c expertmole`
- [x] do `cg compress fastq -d -c drivenmolly`
- [x] do `cg compress fastq -d -c smoothboa`

### Expected test outcome
- [x] check that the files are not compressed
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by HS
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to rare disease team

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
- Fastq files exist
```
[0|0|219] θ84° 1d [henrik.stranneheim@hasta:~] [S_main] 19s $ housekeeper get bundle -v merelyvitalfrog
2021-04-19 19:35:38 hasta.scilifelab.se housekeeper.cli.core[134308] INFO Use database mysql+pymysql://stageuser:userstage@localhost:3308/housekeeper-stage
2021-04-19 19:35:38 hasta.scilifelab.se housekeeper.cli.core[134308] INFO Use root path /home/proj/stage/housekeeper-bundles
2021-04-19 19:35:38 hasta.scilifelab.se housekeeper.store.api.find[134308] INFO Fetching all bundles
2021-04-19 19:35:38 hasta.scilifelab.se housekeeper.store.api.find[134308] INFO Fetching bundle with name: merelyvitalfrog
                  📦 Bundle table 📦
┏━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID    ┃ Bundle name     ┃ Version IDs ┃ Created    ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 33988 │ merelyvitalfrog │ 35821       │ 2021-04-13 │
└───────┴─────────────────┴─────────────┴────────────┘
2021-04-19 19:35:43 hasta.scilifelab.se housekeeper.store.api.find[134308] INFO Fetching bundle with id: 33988
                                📕 Version table 📕
┏━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┓
┃ ID    ┃ Bundle name     ┃ Nr files ┃ Included ┃ Archived ┃ Created    ┃ Expires ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━┩
│ 35821 │ merelyvitalfrog │ 2        │          │          │ 2021-04-13 │         │
└───────┴─────────────────┴──────────┴──────────┴──────────┴────────────┴─────────┘
2021-04-19 19:35:43 hasta.scilifelab.se housekeeper.store.api.find[134308] INFO Fetching files from version 35821
                                                      📜 Files table 📜
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ ID     ┃ File name                                                                                                 ┃ Tags  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ 848396 │ /home/proj/production/external-data/cust000/merelyvitalfrog/2_20010101_D1W4DACXX_05-182_GATCAG_1.fastq.gz │ fastq │
│ 848397 │ /home/proj/production/external-data/cust000/merelyvitalfrog/2_20010101_D1W4DACXX_05-182_GATCAG_2.fastq.gz │ fastq │
└────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘
[0|0|216] θ85° 1d [henrik.stranneheim@hasta:~] [S_main] 12s $ housekeeper get bundle -v jollyboldraven
2021-04-19 19:35:59 hasta.scilifelab.se housekeeper.cli.core[134395] INFO Use database mysql+pymysql://stageuser:userstage@localhost:3308/housekeeper-stage
2021-04-19 19:35:59 hasta.scilifelab.se housekeeper.cli.core[134395] INFO Use root path /home/proj/stage/housekeeper-bundles
2021-04-19 19:35:59 hasta.scilifelab.se housekeeper.store.api.find[134395] INFO Fetching all bundles
2021-04-19 19:35:59 hasta.scilifelab.se housekeeper.store.api.find[134395] INFO Fetching bundle with name: jollyboldraven
                 📦 Bundle table 📦
┏━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID    ┃ Bundle name    ┃ Version IDs ┃ Created    ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 33987 │ jollyboldraven │ 35820       │ 2021-04-13 │
└───────┴────────────────┴─────────────┴────────────┘
2021-04-19 19:36:01 hasta.scilifelab.se housekeeper.store.api.find[134395] INFO Fetching bundle with id: 33987
                               📕 Version table 📕
┏━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┓
┃ ID    ┃ Bundle name    ┃ Nr files ┃ Included ┃ Archived ┃ Created    ┃ Expires ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━┩
│ 35820 │ jollyboldraven │ 2        │          │          │ 2021-04-13 │         │
└───────┴────────────────┴──────────┴──────────┴──────────┴────────────┴─────────┘
2021-04-19 19:36:01 hasta.scilifelab.se housekeeper.store.api.find[134395] INFO Fetching files from version 35820
                                                      📜 Files table 📜
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ ID     ┃ File name                                                                                                ┃ Tags  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ 848394 │ /home/proj/production/external-data/cust000/jollyboldraven/3_20010101_D1W4DACXX_08-247_GCCAAT_1.fastq.gz │ fastq │
│ 848395 │ /home/proj/production/external-data/cust000/jollyboldraven/3_20010101_D1W4DACXX_08-247_GCCAAT_2.fastq.gz │ fastq │
└────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘
[0|0|216] θ84° 1d [henrik.stranneheim@hasta:~] [S_main] 2s $ housekeeper get bundle -v earlyamuseddane
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.cli.core[134485] INFO Use database mysql+pymysql://stageuser:userstage@localhost:3308/housekeeper-stage
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.cli.core[134485] INFO Use root path /home/proj/stage/housekeeper-bundles
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.store.api.find[134485] INFO Fetching all bundles
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.store.api.find[134485] INFO Fetching bundle with name: earlyamuseddane
                  📦 Bundle table 📦
┏━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID    ┃ Bundle name     ┃ Version IDs ┃ Created    ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 33986 │ earlyamuseddane │ 35819       │ 2021-04-13 │
└───────┴─────────────────┴─────────────┴────────────┘
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.store.api.find[134485] INFO Fetching bundle with id: 33986
                                📕 Version table 📕
┏━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┓
┃ ID    ┃ Bundle name     ┃ Nr files ┃ Included ┃ Archived ┃ Created    ┃ Expires ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━┩
│ 35819 │ earlyamuseddane │ 2        │          │          │ 2021-04-13 │         │
└───────┴─────────────────┴──────────┴──────────┴──────────┴────────────┴─────────┘
2021-04-19 19:36:11 hasta.scilifelab.se housekeeper.store.api.find[134485] INFO Fetching files from version 35819
                                                      📜 Files table 📜
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ ID     ┃ File name                                                                                                 ┃ Tags  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ 848392 │ /home/proj/production/external-data/cust000/earlyamuseddane/5_20010101_C1LY4ACXX_08-304_CGATGT_1.fastq.gz │ fastq │
│ 848393 │ /home/proj/production/external-data/cust000/earlyamuseddane/5_20010101_C1LY4ACXX_08-304_CGATGT_2.fastq.gz │ fastq │
└────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘
```

- Cases are not compressed
```
[0|0|221] θ86° 1d [henrik.stranneheim@hasta:~] [S_main] 2m17s $ cg compress fastq -d -c expertmole
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running compress FASTQ
Updating compress api
Set dry run to True
Set ntasks to 12
Set mem to 12
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Skipping case expertmole
0 Individuals in 0 (completed) cases where compressed
[0|0|221] θ84° 1d [henrik.stranneheim@hasta:~] [S_main] 15s $ cg compress fastq -d -c drivenmolly
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running compress FASTQ
Updating compress api
Set dry run to True
Set ntasks to 12
Set mem to 12
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Skipping case drivenmolly
0 Individuals in 0 (completed) cases where compressed
[0|0|219] θ85° 1d [henrik.stranneheim@hasta:~] [S_main] 19s $ cg compress fastq -d -c smoothboa
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running compress FASTQ
Updating compress api
Set dry run to True
Set ntasks to 12
Set mem to 12
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Skipping case smoothboa
0 Individuals in 0 (completed) cases where compressed
```

**Review by patrikgrenfeldt — APPROVED** [review]
I think it might be good to describe on the line of the case-name, why the case is good to have so we can have a clue about what cases to remove in the future

**Comment by henrikstranneheim** [comment]
Sure no problem. What should it be? Something like: [Macromolecule Focus area purpose] e.g. `# DNA rare disease positive control`
More in-depth information on each case can be found in StatusDB (obviously) and in the AM doc Standard set of validation samples.

**Comment by patrikgrenfeldt** [comment]
Please write whatever you think will help us judge if we can remove it in the future

**Comment by patrikgrenfeldt** [comment]
It seems do be around 47 validation cases if i count correctly. How come we need that many?

**Comment by henrikstranneheim** [comment]
- They are form different focus areas: cancer, rare disease, micro.
- They represent different macromolecules (DNA, RNA)
- They represent different genetic variations  like snv/indels,SV, STR, UPD, MT etc
- They represent different annotations such as snv/SV compound heterozygotes, cryptic splice sites etc
- They are prepared and sequenced using different technologies (we need to validate this for backwards compatibility with the pipeline analysis for reruns)

**Comment by henrikstranneheim** [comment]
We are also using 802 causative variants collected from Mutacc (to re-verify previous clinical findings from Scout) and some of these positive controls might not be needed anymore due to this ever growing Mutacc dataset. However, something for MIP 11 validations I think.

**Comment by patrikgrenfeldt** [comment]
>     * They are form different focus areas: cancer, rare disease, micro.
> 
>     * They represent different macromolecules (DNA, RNA)
> 
>     * They represent different genetic variations  like snv/indels,SV, STR, UPD, MT etc
> 
>     * They represent different annotations such as snv/SV compound heterozygotes, cryptic splice sites etc
> 
>     * They are prepared and sequenced using different technologies (we need to validate this for backwards compatibility with the pipeline analysis for reruns)

Could these attributes be specified on the case-rows or is it problematic somehow?

**Comment by henrikstranneheim** [comment]
It is too long and recorded elsewhere (AM and validations). I think it is not justified nor interesting to add more information than this  to the code base. Feel free to add it in another PR if you like.

**Comment by patrikgrenfeldt** [comment]
nah, if you think you have the situation under control then I'm fine 👍

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:
```
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==20.26.2) (0.9.1)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-20.26.2-py3-none-any.whl size=438053 sha256=9f2eb6e546e2c2994d804e8f0fc8fbf4f8aa3a2ba549539992c938cb6d1e0850
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-751bm8f7/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 20.26.1
    Uninstalling cg-20.26.1:
      Successfully uninstalled cg-20.26.1
Successfully installed cg-20.26.2
remote: Enumerating objects: 567, done.
remote: Counting objects: 100% (491/491), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 350 (delta 279), reused 272 (delta 210), pack-reused 0
Receiving objects: 100% (350/350), 38.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (279/279), completed with 75 local objects.
From https://github.com/Clinical-Genomics/cg
   cbfb7c3..14f471a  master     -> origin/master
   55011bd..2f85a48  feat-case-avatar -> origin/feat-case-avatar
   c80932f..a4b0854  feat-trended-cases -> origin/feat-trended-cases
 * [new branch]      polish-delivery -> origin/polish-delivery
 * [new tag]         v20.26.2   -> v20.26.2
Updating cbfb7c3..14f471a
Fast-forward
 .bumpversion.cfg            |  3 ++-
 CHANGELOG.md                |  8 +++-----
 cg/constants/compression.py | 62 +++++++++++++++++++++++++++++++++++++-------------------------
 setup.py                    |  2 +-
 4 files changed, 43 insertions(+), 32 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 20.26.2
housekeeper, version 3.2.0
demux, version 5.8.0
cglims, version 1.3.4
```

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/rare-disease FYI!

**Pull request merged**
