### PR TITLE
Update order report templates to reads_updated_at

### PR DESCRIPTION
**Pull request by islean**
## Description

Addresses issue #2520 where it was highlighted that in #2414, templates were not updated accordingly.

### Fixed

- Templates now references sample.reads_updated_at

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b update-report-templates -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by seallard — APPROVED** [review]
👍

**Review by diitaz93 — APPROVED** [review]
👍

**Review by ivadym — APPROVED** [review]
Nice! Thanks for the fix @islean!

**Comment by islean** [comment]
Tested on stage and the delivery report was generated with "Sekvenserad" filled in.

**Comment by henrikstranneheim** [comment]
Thx @islean 🎉

**Comment by islean** [comment]
Deployed to production 2023-09-26 by IO:

```
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 50.1.3
θ61° [isak.ohlsson@hasta:~] [P_base] 2m50s $ 
```

**Pull request merged**
