### PR TITLE
#2456: Fix fluffy config generation wip

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR adresses https://github.com/Clinical-Genomics/cg/issues/2456. The error message indicates that the header was not identified correctly. The logic could probably use a complete refactoring and also an overview of which fields actually are used in the fluffy repo.

The bug has not been reproduced in stage, so I can't test it. Trying to reproduce it with an automated test instead, digging for a sample sheet which causes the error.

### Fixed
- Fix extraction of header in fluffy sample sheet generation

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Looks good! This should make the header line count identification work for both sample sheet versions.

**Comment by seallard** [comment]
This will fix the reported error, but the actual issue is that fluffy relies on the bcl2fastq sample sheet structure. So the output fluffy sample sheet need to follow the bcl2fastq structure.

**Review by henrikstranneheim — APPROVED** [review]
Nice 👍

**Comment by henrikstranneheim** [comment]
> This will fix the reported error, but the actual issue is that fluffy relies on the bcl2fastq sample sheet structure. So the output fluffy sample sheet need to follow the bcl2fastq structure.

@J35P312 It would be great to decouple Fluffy from this. Do you think it is worth changing this for the current version of Fluffy or do we wait for the NF-version?

**Comment by seallard** [comment]
> > This will fix the reported error, but the actual issue is that fluffy relies on the bcl2fastq sample sheet structure. So the output fluffy sample sheet need to follow the bcl2fastq structure.
> 
> @J35P312 It would be great to decouple Fluffy from this. Do you think it is worth changing this for the current version of Fluffy or do we wait for the NF-version?

According to @karlnyr we should just do a quick fix and refactor later. So I'm closing this in favour of resolving https://github.com/Clinical-Genomics/cg/issues/2465

**Comment by J35P312** [comment]
Perfect! Good luck =P.

In theory we could perhaps even skip the samplesheet.... The samplesheet is used to transfer various data from the orderportal into fluffy (concentration and index for instance). This data is not used by fluffy, but Visulized in Statina or printed in the final output CSV. Maybe we could provide this data to Statina directly? Then we can drop the samplesheet in some future fluffy release.

**Comment by henrikstranneheim** [comment]
@J35P312 Sounds good then we can create a separate file for this in HK instead and not couple this to Fluffy.

**Pull request closed without merging**
