### PR TITLE
Test Balsamic config options

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds tests for the balsamic config options

**How to test**:
1. install on stage of the hastamachine: `bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh balsamic-options-like-mip`
1. activate stage: `us`
1. run following command: `cg analysis balsamic config --dry [CASEID-WITHOUT-TUMOUR-SAMPLES]`

**Expected outcome**:
- [x] `cg` should give you a `Must have exactly one tumor sample! Found 0 samples.`
- [x] the Travis build TESTS should succeed
 - [ ] the Travis pr-build  linting should not contain anything we want to fix
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [x] tests executed by @barrystokman 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This is patch **version bump** because it fixes a faulty log message in the command but other than that adds tests

### CODE REVIEW

**Comment by emiliaol** [comment]
Tested the non-tumor case:
Skärmavbild 2019-10-30 kl  14 36 00
👍

**Comment by ingkebil** [comment]
Can you still fix the linting errors?

```
Linting file: tests/cli/analysis/conftest.py

line 10, col 17: Warning: [redefined-outer-name]: base_context: Redefining name 'analysis_store' from outer scope (line 18)

line 36, col 13: Warning: [redefined-outer-name]: dna_case: Redefining name 'analysis_store' from outer scope (line 18)

line 43, col 13: Warning: [redefined-outer-name]: rna_case: Redefining name 'analysis_store' from outer scope (line 18)

```

**Comment by barrystokman** [comment]
retest:
image
:champagne:

**Comment by barrystokman** [comment]
>the Travis pr-build linting should not contain anything we want to fix
Take a screenshot and attach or copy/paste the output.

Travis CI build failed:
image

@patrikgrenfeldt Can this be fixed or are we leaving it?

**Comment by patrikgrenfeldt** [comment]
@barrystokman I fixed what I thought was relevant

**Comment by patrikgrenfeldt** [comment]
deployed

**Pull request merged**
