### PR TITLE
Add filter to wes samples

### PR DESCRIPTION
**Pull request by adrosenbaum**
Add filter so that no observations from WES analysis are uploaded

**How to test**:
1. Go to hasta
1. install feature branch on stage `$ bash /home/proj/stage/servers/resources/hasta.scilifelab.se/update-cg-stage.sh observations-wes-filter`
1. activate stage environment `$ us`
1. reset observations in status-db `$ cg reset observations`
1. upload observations  `$ cg upload observations`

**Expected outcome**:
`cg` will try to upload all cases into loqusdb. For the cases that
- contain non WGS samples
- come from customer ...
- from non MIP analysis
- Cases where files can not be found (should be most cases, since only the housekeeper bundles for a few files are available in stage)
- cases that are already in loqusdb (Make sure at least one of the cases in stage is not in loqusdb)

`cg` should log that the observations will not be uploaded. 

**Review:**
- [x] code approved by @barrystokman 
- [x] ~~tests executed by @adrosenbaum~~ See validation report 1999:1
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because it adds the new WES filtering feature in a backwards compatible manner.

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@adrosenbaum Please add a motivation in the `"This is minor version bump because ... (add motivation)"`

**Comment by barrystokman** [comment]
Code reviewed, no comments!

**Comment by adrosenbaum** [comment]
Added option in last commit to limit number of cases to upload to loqusdb e.g.```cg upload observations --case-limit 100``` will stop after uploading 100 cases. This is to be used as an initial test when reloading loqusdb in production, making sure clinical-db handles reloading a large number of cases. What do you think @ingkebil? If it looks ok I'll try it in stage and then we can implement it.

**Comment by ingkebil** [comment]
Looks good!

**Pull request merged**
