### PR TITLE
adding rna tags to deliver

### PR DESCRIPTION
**Pull request by jemten**
## Description
This PR adds more files to the mip-rna delivery

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh deliver_rna`

### How to test
- [x] run `cg deliver analysis -d mip-rna  -c finequagga --dry-run`

### Expected test outcome
- [x] check that the following files would be linked to the inbox
  - [x] sample cram files
  - [x] case fusion vcf
  - [x] sample fusion vcf
  - [x] case clinical fusion report
  - [x] case research fusion report
  - [x] case clinical ASE vcf
  - [x] case research ASE vcf
  - [x] sample quant files
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS
- [x] tests executed by AJ
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to data analysis

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by jemten** [comment]
```Console
[0|0|315] [anders.jemt@hasta:~] [S_main] $ cg deliver analysis -d mip-rna -c finequagga
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Running CG deliver
Set dry run to False
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Fetch latest version from bundle finequagga
Setting ticket_id to 154988
Setting customer_id to cust000
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_fusion_report.vcf.gz to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_fusion_report.vcf.gz
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_fusion_report.vcf.gz.tbi to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_fusion_report.vcf.gz.tbi
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_report.selected.pdf to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_report.selected.pdf
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_report.pdf to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_report.pdf
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_comb_norm_vep_parsed.all.vcf.gz to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_comb_norm_vep_parsed.all.vcf.gz
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_comb_norm_vep_parsed.all.vcf.gz.tbi to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_comb_norm_vep_parsed.all.vcf.gz.tbi
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_comb_norm_vep_parsed.selected.vcf.gz to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_comb_norm_vep_parsed.selected.vcf.gz
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/finequagga_comb_norm_vep_parsed.selected.vcf.gz.tbi to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902_comb_norm_vep_parsed.selected.vcf.gz.tbi
Linked 8 files for case finequagga
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/ACC5963A1_lanes_1234_quant.sf to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902/RNA-MixedTissue-190902_lanes_1234_quant.sf
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/ACC5963A1_fusion_comb.vcf.gz to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902/RNA-MixedTissue-190902_fusion_comb.vcf.gz
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/ACC5963A1_fusion_comb.vcf.gz.tbi to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902/RNA-MixedTissue-190902_fusion_comb.vcf.gz.tbi
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902/RNA-MixedTissue-190902_lanes_1234_trim_star_sorted_merged_md.cram
Hard link file /home/proj/stage/housekeeper-bundles/finequagga/2021-06-08/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram.crai to /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/RNA-MixedTissue-190902/RNA-MixedTissue-190902_lanes_1234_trim_star_sorted_merged_md.cram.crai
Linked 5 files for sample ACC5963A1, case finequagga
```
```Console
[0|0|311] [anders.jemt@hasta:~] [S_main] $ tree  /home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/
/home/proj/stage/customers/cust000/inbox/154988/RNA-MixedTissue-190902/
|-- RNA-MixedTissue-190902
|   |-- RNA-MixedTissue-190902_fusion_comb.vcf.gz
|   |-- RNA-MixedTissue-190902_fusion_comb.vcf.gz.tbi
|   |-- RNA-MixedTissue-190902_lanes_1234_quant.sf
|   |-- RNA-MixedTissue-190902_lanes_1234_trim_star_sorted_merged_md.cram
|   `-- RNA-MixedTissue-190902_lanes_1234_trim_star_sorted_merged_md.cram.crai
|-- RNA-MixedTissue-190902_comb_norm_vep_parsed.all.vcf.gz
|-- RNA-MixedTissue-190902_comb_norm_vep_parsed.all.vcf.gz.tbi
|-- RNA-MixedTissue-190902_comb_norm_vep_parsed.selected.vcf.gz
|-- RNA-MixedTissue-190902_comb_norm_vep_parsed.selected.vcf.gz.tbi
|-- RNA-MixedTissue-190902_fusion_report.vcf.gz
|-- RNA-MixedTissue-190902_fusion_report.vcf.gz.tbi
|-- RNA-MixedTissue-190902_report.pdf
`-- RNA-MixedTissue-190902_report.selected.pdf

1 directories, 13 files
[0|0|310] [anders.jemt@hasta:~] [S_main] $~] [S_main] 20s $
```

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
```
[0|0|1059] θ63° [henrik.stranneheim@hasta:~/git/cg] [P_main] master ± bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-prod.sh
on the host hasta.scilifelab.se, continue
This will install the latest version of clinical-genomics/cg on master in production, are you sure? y/[n]y
Collecting git+https://github.com/clinical-genomics/cg
  Cloning https://github.com/clinical-genomics/cg to /home/henrik.stranneheim/tmp/pip-req-build-x4s7a5zx
  Running command git clone -q https://github.com/clinical-genomics/cg /home/henrik.stranneheim/tmp/pip-req-build-x4s7a5zx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.2.2)
Requirement already satisfied: tabulate in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.8.3)
Requirement already satisfied: Flask-Alchy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.5.0)
Requirement already satisfied: cgmodels>=0.6 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.6.0)
Requirement already satisfied: Click<7.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (6.7)
Requirement already satisfied: Flask-CORS in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (3.0.7)
Requirement already satisfied: pyschemes in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.0.0)
Requirement already satisfied: gunicorn in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (20.0.4)
Requirement already satisfied: typing-extensions in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (3.7.4.3)
Requirement already satisfied: pydantic in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.8.1)
Requirement already satisfied: setuptools>=39.2.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (40.6.2)
Requirement already satisfied: python-dateutil in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.8.0)
Requirement already satisfied: ansi in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.2.0)
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.1)
Requirement already satisfied: email-validator in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.1.2)
Requirement already satisfied: SQLAlchemy<1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.2.17)
Requirement already satisfied: google-auth in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.6.2)
Requirement already satisfied: requests-cache in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.4.13)
Requirement already satisfied: Flask>=1.1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.1.1)
Requirement already satisfied: genologics in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.4.3)
Requirement already satisfied: packaging in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (20.9)
Requirement already satisfied: paramiko in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.7.2)
Requirement already satisfied: coloredlogs in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (10.0)
Requirement already satisfied: werkzeug<1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (0.16.1)
Collecting blinker
  Using cached blinker-1.4-py3-none-any.whl
Requirement already satisfied: petname in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.2)
Requirement already satisfied: marshmallow>3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (3.6.1)
Requirement already satisfied: requests[security] in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.21.0)
Requirement already satisfied: Flask-Admin in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.5.3)
Requirement already satisfied: housekeeper>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (3.2.0)
Requirement already satisfied: openpyxl in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (2.6.0)
Requirement already satisfied: Flask-Dance in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (1.3.0)
Requirement already satisfied: pyyaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (5.1)
Requirement already satisfied: lxml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cg==22.2.1) (4.3.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==22.2.1) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==22.2.1) (2.11.1)
Requirement already satisfied: rich in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==22.2.1) (6.2.0)
Requirement already satisfied: ruamel.yaml in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==22.2.1) (0.15.88)
Requirement already satisfied: MarkupSafe>=0.23 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.1.1->cg==22.2.1) (1.1.0)
Requirement already satisfied: pydash>=3.4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Alchy->cg==22.2.1) (4.7.4)
Requirement already satisfied: humanfriendly>=4.7 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from coloredlogs->cg==22.2.1) (4.17)
Requirement already satisfied: idna>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==22.2.1) (2.8)
Requirement already satisfied: dnspython>=1.15.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==22.2.1) (2.1.0)
Requirement already satisfied: wtforms in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Admin->cg==22.2.1) (2.2.1)
Requirement already satisfied: Six in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-CORS->cg==22.2.1) (1.13.0)
Requirement already satisfied: urlobject in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.2.1) (2.4.3)
Requirement already satisfied: oauthlib in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.2.1) (2.1.0)
Requirement already satisfied: lazy in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.2.1) (1.4)
Requirement already satisfied: requests-oauthlib>=1.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==22.2.1) (1.1.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.2.1) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.2.1) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.2.1) (3.0.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.2.1) (0.2.4)
Requirement already satisfied: cachetools>=2.0.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.2.1) (3.1.0)
Requirement already satisfied: rsa>=3.1.4 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==22.2.1) (4.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth->cg==22.2.1) (0.4.5)
Requirement already satisfied: et-xmlfile in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==22.2.1) (1.0.1)
Requirement already satisfied: jdcal in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from openpyxl->cg==22.2.1) (1.4)
Requirement already satisfied: pyparsing>=2.0.2 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from packaging->cg==22.2.1) (2.4.7)
Requirement already satisfied: pynacl>=1.0.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.2.1) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.2.1) (2.5)
Requirement already satisfied: bcrypt>=3.1.3 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==22.2.1) (3.2.0)
Requirement already satisfied: cffi>=1.1 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from bcrypt>=3.1.3->paramiko->cg==22.2.1) (1.12.0)
Requirement already satisfied: pycparser in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->cg==22.2.1) (2.19)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from cryptography>=2.5->paramiko->cg==22.2.1) (0.24.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==22.2.1) (19.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.2.1) (2.6.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.2.1) (0.4.3)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==22.2.1) (0.9.1)
Installing collected packages: blinker
Successfully installed blinker-1.4
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 93 (delta 63), reused 75 (delta 48), pack-reused 0
Unpacking objects: 100% (93/93), done.
From https://github.com/Clinical-Genomics/cg
   490ced9..d7db827  master     -> origin/master
   4de2384..5977d24  fohm-delivery -> origin/fohm-delivery
   c108ddd..342e55a  gisaid_kompliteringsfil -> origin/gisaid_kompliteringsfil
Updating 490ced9..d7db827
Fast-forward
 .bumpversion.cfg         |  1 +
 CHANGELOG.md             |  4 ++--
 cg/constants/delivery.py | 16 +++++++++++++---
 requirements.txt         |  1 +
 4 files changed, 17 insertions(+), 5 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
balsamic 6.0.0 requires colorclass, which is not installed.
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 22.2.1
housekeeper, version 3.2.0
demux, version 5.10.0
cglims, version 1.3.4
```

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/data-analysis cg deliver analysis -d mip-rna can now deliver more files

**Pull request merged**
