### PR TITLE
Added Field Primer in Lims

### PR DESCRIPTION
**Pull request by Vince-janv**
## Description
[Linked to this issue](https://github.com/Clinical-Genomics/project-planning/issues/358). Related to [this PR](https://github.com/Clinical-Genomics/cgweb/pull/404). Adds Primer options in lims for the mutant pipeline to use.

### Added
- New UDF in lims

### How to prepare for test
- [x] Install the cgweb and cg branch on stage (feat-add-primer-2184).

### How to test
- [x] Create a sarscov2 order. Attempt to save the order without primers
- [x] Add Primers and save the order

### Expected test outcome
- [x] Without Primers the order should be rejected.
- [x] Check in lims-stage that the new samples have the Primer/UDF
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by VJ
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Get go ahead from @henningonsbring
- [x] Get new OF approved in AM (ready to be published)
- [x] Upload new OF to SuSy 
- [x] Create the new Primer UDF in LIMS
- [ ] Merge and deploy this branch on cg-prod-services
- [ ] Merge/deploy [cgweb PR](https://github.com/Clinical-Genomics/cgweb/pull/404)
- [ ] Inform to @annagellerbring and @henningonsbring

### CODE REVIEW

**Comment by Vince-janv** [comment]
### Not Providing Primer:
Screenshot 2022-05-17 at 10 54 23
### Primer info stored in lims-stage
Screenshot 2022-05-17 at 10 55 34

**Review by patrikgrenfeldt — COMMENTED** [review]
Great work so far!

**Review by patrikgrenfeldt — APPROVED** [review]
👍 Nice, really to the point!

**Comment by Vince-janv** [comment]
### Still working:
Screenshot 2022-06-03 at 16 36 57
### And LIMS
Screenshot 2022-06-03 at 16 35 56

**Pull request merged**
