### PR TITLE
remove unused flags from base command

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...
- Removes flags (which had no function other than being displayed in a help message) from `cg workflow balsamic base` command 

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta atage
- [x] do cg workflow balsamic <..> --dry-run commands 

### Expected test outcome
- [x] check that functionality was not lost
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MM, HFA
- [x] tests executed by MR
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Mropat** [comment]
Options removed
image

Balsamic workflow command group not broken
image

**Review by moonso — APPROVED** [review]
Better ⭐

**Review by hassanfa — APPROVED** [review]
👍🏽

**Comment by Mropat** [comment]
Deployed on prod
image

**Pull request merged**
