### PR TITLE
Patch setting reference genome for existing samples

### PR DESCRIPTION
**Pull request by islean**
## Description

Existing samples are not updated with the reference genome even though it is sent in the order. This prevents new Tomte orders with existing samples from being run. Addresses #3228.

### Fixed

- Reference genome is updated for existing samples if set in a new order.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by islean** [comment]
This is an improvement but ideally maybe the reference genome should be placed in the case_sample table so that it can be set per order? Now any new order will override the old value.

**Comment by islean** [comment]
Tested submitting an order in stage setting the reference genome for a sample with it previously not set. After submission it was set:

image

**Review by diitaz93 — APPROVED** [review]
Looks good 👍

**Comment by diitaz93** [comment]
> This is an improvement but ideally maybe the reference genome should be placed in the case_sample table so that it can be set per order? Now any new order will override the old value.

Yeah good point, maybe lets consult with someone more familiar to pipelines before merging this

**Comment by diitaz93** [comment]
@islean Talking to @ivadym we decided that it is better to set this for refinement until we have a better understanding of the reference genome usage.

**Comment by fevac** [comment]
We need a quick fix for this. We could then refine a more permanent solution.

My suggestion:
- Add reference genome information in an old sample information if this information is missing (not overwrite if it was added)
- I had previously talked about this with @karlnyr 

We can then refine the reference_genome information with a bit more time. 

We cannot have this bug in prod for too long as it is a pain in the butt and we are still modifying (just manually) the old sample information

My point is, that the workaround for production is still modifying the old sample. There is no other workaround. Setting a default genome version is not an option, because they already provide that information in the order and is not always 19 or always 38. So that cannot be an option.

We could also add a comment also if you want to keep traceability

**Comment by fevac** [comment]
Decision from meeting 20240520 with @karlnyr @Vince-janv @ivadym @fevac :

- Short term:
  -  @Vince-janv confirm with customers about updating the reference genome for their already existing samples. 
  - @Vince-janv update statusDB for customers involved for all their already existing RNA samples:
    - set reference genome (this field was previously not used for any logic, so it should not entail a problem in the data flow. However it does become a bit misleading at the "information level" since the reference genome might differ from what it was previously ran)
    - append a comment informing about the changes done and the date

- Long term:
  - Move reference genome information to a case level. This requires a bit of refactoring and it's a bigger project. @Vince-janv will create or link an issue to track this. The priority will depend on whether other workflows will require setting these fields or not

**Comment by diitaz93** [comment]
Does this still need refinement? @fevac @Vince-janv ?

**Comment by seallard** [comment]
> Decision from meeting 20240520 with @karlnyr @Vince-janv @ivadym @fevac :
> 
>     * Short term:
>       
>       * @Vince-janv confirm with customers about updating the reference genome for their already existing samples.
>       * @Vince-janv update statusDB for customers involved for all their already existing RNA samples:
>         
>         * set reference genome (this field was previously not used for any logic, so it should not entail a problem in the data flow. However it does become a bit misleading at the "information level" since the reference genome might differ from what it was previously ran)
>         * append a comment informing about the changes done and the date
> 
>     * Long term:
>       
>       * Move reference genome information to a case level. This requires a bit of refactoring and it's a bigger project. @Vince-janv will create or link an issue to track this. The priority will depend on whether other workflows will require setting these fields or not

I don't quite understand the role of a reference genome, but it sounds like it is more of a setting for a specific analysis of the case? As such, would it not make more sense to introduce a separate model for it than to store it on the case?

Or is it not likely that we will re-run cases with different reference genomes?
@Vince-janv, @fevac

**Comment by henrikstranneheim** [comment]
Reanalysis using a different reference genome would yield a completely different result and I think it is more than a rerun and warrants a separate case. Or we have to refine a lot of logic.

**Comment by islean** [comment]
Closing due to the work done in https://github.com/Clinical-Genomics/cg/issues/3243 and the outcome of the refinement meetings.

**Pull request closed without merging**
