### PR TITLE
Add tissue type when creating scout config file

### LINKED ISSUE #497: Tissue type should be passed on from lims (is it there?) to Scout.
So that is saved and displayed in the case page.
Maybe the option is already there, I don't know. To be checked and eventually implemented.

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR should add a field `tissue_type` for each individual when creating a scout config file.
fix #497 

**How to prepare for test**:
- [ ] install on hasta stage `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh pass_tissue_type`
- [ ] activate stage: `us`

**How to test**:
- [ ] `cg upload scout bosscod`

**Expected test outcome**:
- [ ] The load command should create a yaml config file containing a tissue type set to 'unknown' for the case sample. (this happens because the sample is not in lims stage database, but in the lims one). Maybe there is a better case to test the command with?

**Review:**
- [x] code approved by @patrikgrenfeldt 
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This is a minor version update because it adds a new functionality.

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'm sure it's because I don't have much experience with it, but it's 2 days that I'm literally getting crazy over linting problems: the more I fix them, the more pop up at the next build. 

Tried reformatting the file with black but I still get new errors every build. Any help would be very appreciated. I'm going to leave this PR for when I will have more time otherwise.

**Comment by barrystokman** [comment]
See last comment on this issue: https://github.com/PyCQA/pylint/issues/2944, the indentation message might be caused by `black`

>line 221, col 4: Refactor: [no-self-use]: MockLims.lims_samples: Method could be a function

```
    def lims_samples(self):
        lims_family = json.load(open("tests/fixtures/report/lims_family.json"))
        return lims_family["samples"]
```

This method/function doesn't touch the class at all so maybe use @staticmethod?

**Comment by northwestwitch** [comment]
> PyCQA/pylint#2944

**Comment by northwestwitch** [comment]
> See last comment on this issue: [PyCQA/pylint#2944](https://github.com/PyCQA/pylint/issues/2944), the indentation message might be caused by `black`

Very likely, the error showed immediately after I reformatted with black, I'll try to revert to a version before. Thanks!

**Comment by northwestwitch** [comment]
Thanks @hassanfa, the 4 spaces message are gone now!

**Comment by northwestwitch** [comment]
YESSS IT PASSED!!! 
Thank you so much @barrystokman and @hassanfa! 
I might start crying now (happy tears), so good thing I'm working from home so I'll spare you the scene!! XD

**Comment by hassanfa** [comment]
@northwestwitch worthy of adding to resume 🤣

**Comment by northwestwitch** [comment]
> @northwestwitch worthy of adding to resume 🤣

Indeed! :D

**Comment by northwestwitch** [comment]
This is ready for review, anybody?

**Comment by patrikgrenfeldt** [comment]
I have reviewed the code, looked good, seems like there is some conflicts that needs relolution: 
image

**Comment by northwestwitch** [comment]
Thanks @patrikgrenfeldt, I'll fix them asap!

**Comment by northwestwitch** [comment]
I worked on this PR a month ago and many things have changed since then, I'll try to fix it here but it might take longer than I prevented..!

**Comment by northwestwitch** [comment]
Closing this and opening a new PR with the same code from the updated master. Otherwise it was conflict hell!

**Pull request closed without merging**
