### PR TITLE
Decouple beacon

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR removes beacon-related commands from cg.

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/stage/servers/resources/hasta.scilifelab.se/update-cg-stage.sh deacouple_beacon`
- [x] use the stage environment with the `us` command

### How to test
beacon-related commands that are on current master branch should not be present any more. Specifically:
- `cg upload --help`

image

- `cg clean --help`

image

- cg upload beacon --help

image

- cg clean beacon --help

image

### Expected test outcome
- [x] The commands above should not be found
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by CR
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moonso** [comment]
Wow you are just wiping everything 😄 could you explain a little bit more, are we not supposed to upload to beacon?

**Comment by northwestwitch** [comment]
> Wow you are just wiping everything 😄 could you explain a little bit more, are we not supposed to upload to beacon?

Yes, I'm wiping out it completely. As far as I know the beacon functionality has never been used. There is a new beacon software now (cgbeacon2) with an API that will be communicating directly with Scout

**Comment by northwestwitch** [comment]
Increasing the coverage by more than 1% 🎉

**Comment by northwestwitch** [comment]
Tests:
cg upload --help 🆗 

image


cg clean --help 🆗 

image


cg upload beacon --help 🆗 

image


cg clean beacon --help 🆗 
image

**Review by moonso — APPROVED** [review]
Super 🦹

**Comment by moonso** [comment]
I guess this would be classified as a major @henrikstranneheim @patrikgrenfeldt ? Since cli functions are removed?

**Comment by henrikstranneheim** [comment]
Yes, definitely if there are AM docs or Cron tabs using this. If not then I think we can communicate this and be done

**Comment by northwestwitch** [comment]
> Yes, definitely if there are AM docs or Cron tabs using this. If not then I think we can communicate this and be done

A major then! I'll fix the AM docs relative scripts (on Servers). Is it ok to deploy?

**Comment by henrikstranneheim** [comment]
> A major then! I'll fix the AM docs relative scripts (on Servers). Is it ok to deploy?
Yes, and let's merge the servers PR and this one together

**Comment by northwestwitch** [comment]
> Yes, and let's merge the servers PR and this one together

Opened https://github.com/Clinical-Genomics/servers/pull/399 to remove the beacon server from the servers

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Comment by moonso** [comment]
Skärmavbild 2020-09-02 kl  17 16 25

Merged and deployed on hasta

**Pull request merged**
