### PR TITLE
Missing prep method

### PR DESCRIPTION
**Pull request by mayabrandi**
Prep method and sequencing method are missing in some delivery reports. Below is an example. 

Screenshot 2020-03-11 at 11 33 36

This PR should solve the problem. I want to test the change by running 

`cg upload delivery-report maindrum -p`

The command gives this error:

Skärmavbild 2020-03-17 kl  09 18 19

**How to prepare for test**:
- [x] ssh to clinical-db and become hiseq.clinical user:
then run the folowing to copy the housekeeper database from prod to stage:
bash /home/proj/stage/servers/resources/clinical-db.scilifelab.se/dbcopy-prod-to-stage.sh housekeeper
- [x] ssh to hasta 
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh update_constants`
activate stage: `usestage`
- [x] change the lims host to "https://clinical-lims.scilifelab.se" in 
/home/proj/stage/servers/config/hasta.scilifelab.se/cg-stage.yaml

**How to test**:
run `cg upload delivery-report maindrum -p`

**Expected test outcome**:
Sequencing and prep methods should be given for the two samples from 2020. 

**Review:**
- [x] code approved by @henrikstranneheim 
- [x] tests executed by @mayabrandi 
- [x] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
How to test:
- [x] change the lims host to "https://clinical-lims-stage.scilifelab.se" in
/home/proj/stage/servers/config/hasta.scilifelab.se/cg-stage.yaml
- [x] cg upload delivery-report maindrum -p ✅ 

Expected test outcome:
Screenshot 2020-03-17 at 13 36 13 ✅ 

Screenshot 2020-03-17 at 13 52 29 FAIL - No sequencing method recorded

**Comment by mayabrandi** [comment]
I just performed the test described above. The outcome was as expected: Both samples 2020-05005-02 and 2020-05006-02 got "Biblioteksberedning" and "Sekvensering" methods populated. See screen shot

Skärmavbild 2020-03-18 kl  10 28 12

The reasons why Henriks test above failed was:
1) He looked in the lims-stage database instead of lims
2) The sequencing step method udf was not given. After setting the the method and version in the sequencing step, the delivery report generator picked up the values.

**Comment by henrikstranneheim** [comment]
👍 Great!

**Comment by henrikstranneheim** [comment]
@barry or @patrikgrenfeldt : Looks ready for a merge and deploy whenever you have time.

**Comment by barrystokman** [comment]
> @barry or @patrikgrenfeldt : Looks ready for a merge and deploy whenever you have time.

As a side note, I'm @barrystokman :)

**Comment by barrystokman** [comment]
Deployed on Hasta

**Pull request merged**
