### PR TITLE
Add support for OF 1508:24

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
*This PR adds support for OF 1508:24*

### How to prepare for test
- [x] ssh to clinical-db
- [x] Use stage: `us`
- [x] paxa the environments: `paxa`
- [x] install on stage:
`cd  /home/proj/production/servers/resources/clinical-db.scilifelab.se/; bash update-clinical-api-stage.sh feat-of-1508-23`
- [x] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh feat-of-1508-23`

---

### How to test balsamic:
- [x] login to the clinical-stage.scilifelab.se
- [x] do submit cg/tests/fixtures/orderforms/1508.24.balsamic.xlsx as order #111111

### Expected test outcome
- [x] check that submission was successful 

---

### How to test mip-dna:
- [x] login to the clinical-stage.scilifelab.se
- [x] do submit cg/tests/fixtures/orderforms/1508.24.mip.xlsx as order #222222

### Expected test outcome
- [x] check that submission was successful 

---

### How to test mip-rna:
- [x] login to the clinical-stage.scilifelab.se
- [x] do submit cg/tests/fixtures/orderforms/1508.24.mip_rna.xlsx as order #333333

### Expected test outcome
- [x] check that submission was successful 

---

### How to test fastq:
- [x] login to the clinical-stage.scilifelab.se
- [x] do submit cg/tests/fixtures/orderforms/1508.24.fastq.xlsx as order #444444

### Expected test outcome
- [x] check that submission was successful 

---

### How to test external:
- [x] login to the clinical-stage.scilifelab.se
- [x] do submit cg/tests/fixtures/orderforms/1541.6.external.xlsx as order #555555

### Expected test outcome
- [x] check that submission was successful 
- [x] Take a screenshot and attach or copy/paste the output.

---

## Review
- [ ] code approved by
- [x] tests executed by PG
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to AG, AZ

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
# Test results

## Balsamic
image

## MIP-DNA
image

## RNA
image

## Fastq
image

**Comment by patrikgrenfeldt** [comment]
# Test result

## External 
image
🆗 All test cases as expected

**Comment by patrikgrenfeldt** [comment]
@Mropat or @henningonsbring do you have the possibility to take a look at the code of this PR?

**Review by Mropat — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
deployed to clinical-db: 
image

**Pull request merged**
