### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by islean**
## Description

This PR was generated by running `poetry update fastapi` and `poetry update cryptography` and should resolve the dependabot alerts.

### Fixed

- fastapi, cryptography and starlette have all been bumped.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b bump-dependencies -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
Great 👍 Im thinking if you should include starlette too #2903

**Comment by islean** [comment]
> Great 👍 Im thinking if you should include starlette too #2903

Starlette was updated as part of the fastapi update.

**Review by henrikstranneheim — APPROVED** [review]
Great! 👍

**Comment by islean** [comment]
Deployed on stage to both Hasta and cg-vm1 without failure. This concludes testing.

**Comment by islean** [comment]
Deployed to Hasta and the vms:

```
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 56.3.6
[isak.ohlsson@hasta:~] [P_base] 2m14s $ 
```

**Pull request merged**
