### PR TITLE
balsamic workflow confition

### PR DESCRIPTION
**Pull request by Mropat**
## Description
*This PR adds/fixes ...*
Fixes bug where workflow would try to start cases without tumor sample automatically. This is the old behavior that was accidentally lost in recent refactor

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by moonso — APPROVED** [review]
👍

**Comment by hassanfa** [comment]
@Mropat wait with this fix.

**Comment by Mropat** [comment]
@hassanfa if you wish I can just close this PR as the measure added in this is "redundant"
Cases like this are not possible to create currently via OF.

**Comment by hassanfa** [comment]
> @hassanfa if you wish I can just close this PR as the measure added in this is "redundant"
> Cases like this are not possible to create currently via OF.

It'd be great if this can be handled outside `cg`. As data flow should and must be correct. If a case doesn't start because of a malformed order form, then we inform customer and fix the order according to our requirements.

I vote to close this.

**Pull request closed without merging**
