### PR TITLE
Remove check of analysisrunstatus in MIP store

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...
Removes requirement of finished analysis in mip config when storing

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] do cg workflow mip-dna store

### Expected test outcome
- [x] check that files with analysisrunstatus == failed are stored if finished in Trailblazer
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by MR
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MINOR** - when you add functionality in a backwards compatible manner

### CODE REVIEW

**Comment by Mropat** [comment]
Tb-stage
image
Set case to completed
image

Storage fails because of missing file, no longer fails because of analysisrunstatus!
image

**Comment by barrystokman** [comment]
What happens if data["analysisrunstatus"] == "not finished"?

**Comment by Mropat** [comment]
@barrystokman CG checks with Trailblazer if analysis is finished. The trailblazer status can be manually set to finished now. This removed the need to edit config. CG store analysis will now store anything you ask it to - and if tags arent all there it will complain about that instead

**Review by moonso — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]
Looks good! One less manual step to do in production, 👍. To leave the mip config "analysisrunstatus=not_finished" and go ahead and store is fine I think - it is a record of what actually happened and that the decision was taken to go ahead anyway with a comment.

**Comment by Mropat** [comment]
@karlnyr @emmser @Clinical-Genomics/production 

Deployed on stage
image


Deployed in production
image

**Pull request merged**
