### PR TITLE
handeling clinical trials

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR translates the new priority "clinical trials" to "research"

**How to test**:
1. install the cg master branch and go to invoice 285: http://127.0.0.1:5000/invoices/285. The page gives an error: AttributeError: 'ApplicationVersion' object has no attribute 'price_clinical trials'
2. Then  install this branch and go to the same page. Error gone!

**Expected outcome**:
After update:

Skärmavbild 2019-10-09 kl  10 30 27

**Review:**
- [x] code approved by @ingkebil 
- [x] tests executed by @mayabrandi 
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

Regarding Version bump: this looks like a patch as it doesn't add any new functionality :)

### CODE REVIEW

**Comment by ingkebil** [comment]
Code looks good! If the screenshot in the expected outcome was taken from stage, I would move the screenshot to a comment and use that as proof that you have tested it. Then it's already done.

Can you motivate your version bump? e.g. this looks like a patch as it doesn't add any new functionality.

**Comment by ingkebil** [comment]
Tests fail which is not because of the added code.

**Comment by mayabrandi** [comment]
Testen on stage.

Skärmavbild 2019-10-09 kl  12 31 45

**Comment by ingkebil** [comment]
I fixed the tests now ;)

**Comment by mayabrandi** [comment]
Thanks a lot.

> 9 okt. 2019 kl. 13:06 skrev Kenny Billiau <notifications@github.com>:
> 
> I fixed the tests now ;)
> 
>

**Comment by emiliaol** [comment]
Time to deploy?

**Comment by ingkebil** [comment]
> Can you motivate your version bump? e.g. this looks like a patch as it doesn't add any new functionality.

I'm waiting for this.

**Comment by patrikgrenfeldt** [comment]
@mayabrandi could you fill in  if this is a patch|minor|major in "This is patch|minor|major version bump because ..." sentence above?

**Comment by mayabrandi** [comment]
can be merged now? @patrikgrenfeldt

**Comment by ingkebil** [comment]
approving. I'll bump and deploy

**Comment by ingkebil** [comment]
deployed

**Pull request merged**
