### PR TITLE
Fix(automation): skip analysis for external cases until action is "analyze"

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
### Fixed
- skip analysis for external cases until the action is set to "analyze"

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do create a new external case on stage
- [ ] run `cg workflow PIPELINE start-available --dry-run`

### Expected test outcome
- [ ] check that it is not included 
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MR, @Vince-janv 
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch
- [ ] Inform to @Vince-janv , @moahaegglund

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@Vince-janv I made this fix but I think we should change the behavior to be more explicit? Maybe as you suggested to set the action to hold when we create the external cases?

**Comment by Mropat** [comment]
This will prevent all external cases from being started automatically. Is this desired behavior?

**Comment by Vince-janv** [comment]
@patrikgrenfeldt I think you know best where it would make most sense, but the query is getting pretty hard to comprehend 😅  I for example am having a hard time distinguishing when an external case will be started.

To answer you question @Mropat: The external cases should only be started if their action is "analyze".

**Review by Mropat — APPROVED** [review]

**Review by Vince-janv — APPROVED** [review]
Nice! I read up a bit on SQLAlchemy queries and this seems to do the trick.

**Comment by patrikgrenfeldt** [comment]
Without fix:
```
[0|0|0] [patrik.grenfeldt@hasta:~] [S_main] 31s 1 $ cg workflow mip-dna start-available --dry-run | grep warmcat
2021-12-14 08:44:26 hasta.scilifelab.se cg.meta.workflow.analysis[21659] INFO Case warmcat exists in status db
2021-12-14 08:44:26 hasta.scilifelab.se cg.cli.workflow.mip.base[21659] INFO Starting full MIP analysis workflow for case warmcat
2021-12-14 08:44:26 hasta.scilifelab.se cg.meta.workflow.analysis[21659] INFO Case warmcat exists in status db
2021-12-14 08:44:26 hasta.scilifelab.se cg.cli.workflow.commands[21659] INFO All flowcells present on disk
2021-12-14 08:44:26 hasta.scilifelab.se cg.meta.workflow.analysis[21659] INFO Case warmcat exists in status db
```
👎 the external case is picked up for analysis

Test result:
```
[0|0|0] θ61° [patrik.grenfeldt@hasta:~] [S_main] master 2m0s 130 ± cg workflow mip-dna start-available --dry-run | grep warmcat
....
[0|0|0] θ61° [patrik.grenfeldt@hasta:~] [S_main] master 130 ±
```
🆗 no mention of the external case

**Comment by patrikgrenfeldt** [comment]
Upgraded pip and deployed: 
```
[0|0|0] θ61° [patrik.grenfeldt@hasta:] [S_main] master 130 ± python -m pip install --upgrade pip
Requirement already satisfied: pip in python3.7/site-packages (21.1.2)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 17.9 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.2
    Uninstalling pip-21.1.2:
      Successfully uninstalled pip-21.1.2
Successfully installed pip-21.3.1

bash update-cg-stage.sh master
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 22.37.0
    Uninstalling cg-22.37.0:
      Successfully uninstalled cg-22.37.0
Successfully installed cg-22.37.0

up
python -m pip install --upgrade pip
Requirement already satisfied: pip in site-packages (21.1.2)
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.2
    Uninstalling pip-21.1.2:
      Successfully uninstalled pip-21.1.2
Successfully installed pip-21.3.1

bash update-cg-prod.sh
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 22.37.0
    Uninstalling cg-22.37.0:
      Successfully uninstalled cg-22.37.0
Successfully installed cg-22.37.1
```

**Comment by patrikgrenfeldt** [comment]
@Vince-janv @moahaegglund This fix to not automatically start external cases (i.e. samples) until action has been set to "analyze" has been deployed to production

**Pull request merged**
