### PR TITLE
Fix error when compressing fastqs in dry run mode

### PR DESCRIPTION
**Pull request by barrystokman**
## Description
Fixes `cg compress --dry-run`

### Fixed
Don't set backup api dry run if there is none

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by barrystokman** [comment]
> 100 I would suggest to try and run `cg compress fastq -n 40 --dry-run` for test of function +1

Patience, young padawan :)

**Comment by barrystokman** [comment]
`cg compress fastq -n 40 --dry-run`:
image

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Comment by barrystokman** [comment]
deployed on hasta
image

**Pull request merged**
