### PR TITLE
fix(wrong return type from query caller)

### PR DESCRIPTION
**Pull request by ChrOertlin**
## Description

A query caller returned the actual query causing a None check to pass when it should not. This caused that a log message was produced that should have been reached.

### Changed

- Return of a query caller function to return the query object instead of the query

- Added a LOG input informing that there are no cases to compress in the scenario when there are no cases to compress

- Changed to test to pick up the newly added LOG input instead of the one that should not be reached.

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b hotfix_query_bug -a
    ```

### How to test

- [x] Do `cg compress fastq` on 1) non-existing case and existing case

### Expected test outcome

- [x] Check that the log produces the expected outcome "no cases to compress"
- [x] Take a screenshot and attach or copy/paste the output.

## Review

- [x] Tests executed by @ChrOertlin 
- [x] "Merge and deploy" approved by @henrikstranneheim 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [x] Deploy this branch on production

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Good catch  💯

**Comment by ChrOertlin** [comment]
test for not existing case

```
θ66° 10d [hiseq.clinical@hasta:~] [S_base] 19s $ cg compress fastq -c test -d
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Called undefined __fields__ on HousekeeperAPI, please wrap
Running compress FASTQ
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Could not find case test
No cases to compress
```

test case for existing case:

```
θ62° 10d [hiseq.clinical@hasta:~] [S_base] 3m3s $ cg compress fastq -c usefulmammal -d
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Called undefined __fields__ on HousekeeperAPI, please wrap
Running compress FASTQ
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Searching for FASTQ files in case usefulmammal
Updating compress api
Set dry run to True
Set Crunchy API SLURM mem to 173
Check if FASTQ compression is possible for ACC9997A1
Fetch latest version from bundle ACC9997A1
Could not find FASTQ files for ACC9997A1
skipping individual ACC9997A1
Set Crunchy API SLURM mem to 55
Check if FASTQ compression is possible for ACC9997A2
Fetch latest version from bundle ACC9997A2
Could not find FASTQ files for ACC9997A2
skipping individual ACC9997A2
0 individuals in 0 (completed) cases where compressed
```

**Comment by ChrOertlin** [comment]
bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-prod.sh -e P_main -t cg -b master -a
/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))

Collecting git+https://github.com/Clinical-Genomics/cg@master
  Running command git clone --quiet https://github.com/Clinical-Genomics/cg /home/hiseq.clinical/tmp/pip-req-build-3c93dykp
  Cloning https://github.com/Clinical-Genomics/cg (to revision master) to ./tmp/pip-req-build-3c93dykp
  Resolved https://github.com/Clinical-Genomics/cg to commit a2d6c9fccd033c60d784cccfad1c95159af2cd4d
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: cg
  Building wheel for cg (pyproject.toml): started
  Building wheel for cg (pyproject.toml): finished with status 'done'
  Created wheel for cg: filename=cg-26.6.0-py3-none-any.whl size=674936 sha256=eb31aeb405416d75cf5abbd63174e050e3f5e21481f130a894e4bd8545019a78
  Stored in directory: /home/hiseq.clinical/tmp/pip-ephem-wheel-cache-0d1j8tfx/wheels/4b/55/66/90c6ed137f9153944f27209bd5c3790044b15cf24d2c7f573b
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 26.5.1
    Uninstalling cg-26.5.1:
      Successfully uninstalled cg-26.5.1
Successfully installed cg-26.6.0
Collecting git+https://github.com/Clinical-Genomics/cg@master
  Running command git clone --quiet https://github.com/Clinical-Genomics/cg /home/hiseq.clinical/tmp/pip-req-build-7r_fvryc
  Cloning https://github.com/Clinical-Genomics/cg (to revision master) to ./tmp/pip-req-build-7r_fvryc
  Resolved https://github.com/Clinical-Genomics/cg to commit a2d6c9fccd033c60d784cccfad1c95159af2cd4d
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: blinker in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.5)
Requirement already satisfied: Flask-Alchy in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.5.0)
Requirement already satisfied: openpyxl==3.0.10 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (3.0.10)
Requirement already satisfied: pyyaml in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (6.0)
Requirement already satisfied: pandas in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.3.5)
Requirement already satisfied: tabulate in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.9.0)
Requirement already satisfied: typing-extensions in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (4.4.0)
Requirement already satisfied: setuptools>=39.2.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (65.5.0)
Requirement already satisfied: markupsafe<2.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.0.1)
Requirement already satisfied: requests-cache in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.9.6)
Requirement already satisfied: marshmallow>3 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (3.18.0)
Requirement already satisfied: packaging in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (21.3)
Requirement already satisfied: gunicorn in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (20.1.0)
Requirement already satisfied: requests[security] in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.28.1)
Requirement already satisfied: SQLAlchemy<1.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.3.24)
Requirement already satisfied: google-auth in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.13.0)
Requirement already satisfied: cgmodels>=0.10.5 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.10.5)
Requirement already satisfied: ansi in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.3.6)
Requirement already satisfied: lxml in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (4.9.1)
Requirement already satisfied: wtforms<3.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.3.3)
Requirement already satisfied: python-dateutil in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.8.2)
Requirement already satisfied: pymysql in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.0.2)
Requirement already satisfied: housekeeper>=2.5 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (3.2.0)
Requirement already satisfied: Flask-Dance in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (5.1.0)
Requirement already satisfied: alembic in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.8.1)
Requirement already satisfied: werkzeug<1.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.16.1)
Requirement already satisfied: coloredlogs in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (15.0.1)
Requirement already satisfied: Flask>=1.1.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.1.4)
Requirement already satisfied: flask-wtf in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.1.1)
Requirement already satisfied: Flask-CORS in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (3.0.10)
Requirement already satisfied: sendmail-container in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.2.0)
Requirement already satisfied: paramiko in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.11.0)
Requirement already satisfied: pydantic in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.10.2)
Requirement already satisfied: Click<7.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (6.7)
Requirement already satisfied: Flask-Admin in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.6.0)
Requirement already satisfied: genologics in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (0.4.6)
Requirement already satisfied: Alchy in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.2.2)
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.1)
Requirement already satisfied: petname in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (2.6)
Requirement already satisfied: email-validator in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cg==26.6.0) (1.3.0)
Requirement already satisfied: et-xmlfile in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from openpyxl==3.0.10->cg==26.6.0) (1.1.0)
Requirement already satisfied: pytest-cov in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (4.0.0)
Requirement already satisfied: atomicwrites in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (1.4.1)
Requirement already satisfied: zipp in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (3.9.0)
Requirement already satisfied: attrs in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (22.1.0)
Requirement already satisfied: dataclasses in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (0.6)
Requirement already satisfied: coverage in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (6.5.0)
Requirement already satisfied: py in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (1.11.0)
Requirement already satisfied: pytest in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (7.1.3)
Requirement already satisfied: wcwidth in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (0.2.5)
Requirement already satisfied: colorama in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (0.4.5)
Requirement already satisfied: more-itertools in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (8.14.0)
Requirement already satisfied: importlib-metadata in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (5.0.0)
Requirement already satisfied: pyparsing in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (2.4.7)
Requirement already satisfied: pluggy in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cgmodels>=0.10.5->cg==26.6.0) (1.0.0)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==26.6.0) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask>=1.1.1->cg==26.6.0) (1.1.0)
Requirement already satisfied: rich in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==26.6.0) (12.6.0)
Requirement already satisfied: ruamel.yaml in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from housekeeper>=2.5->cg==26.6.0) (0.17.21)
Requirement already satisfied: pydash>=3.4.7 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Alchy->cg==26.6.0) (5.1.1)
Requirement already satisfied: importlib-resources in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from alembic->cg==26.6.0) (5.10.0)
Requirement already satisfied: Mako in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from alembic->cg==26.6.0) (1.2.3)
Requirement already satisfied: humanfriendly>=9.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from coloredlogs->cg==26.6.0) (10.0)
Requirement already satisfied: idna>=2.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==26.6.0) (3.4)
Requirement already satisfied: dnspython>=1.15.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from email-validator->cg==26.6.0) (2.2.1)
Requirement already satisfied: Six in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask-CORS->cg==26.6.0) (1.16.0)
Requirement already satisfied: oauthlib in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==26.6.0) (3.2.2)
Requirement already satisfied: requests-oauthlib>=1.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==26.6.0) (1.3.1)
Requirement already satisfied: urlobject in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from Flask-Dance->cg==26.6.0) (2.4.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==26.6.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==26.6.0) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from google-auth->cg==26.6.0) (5.2.0)
Requirement already satisfied: pytz>=2017.3 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pandas->cg==26.6.0) (2022.4)
Requirement already satisfied: numpy>=1.17.3 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pandas->cg==26.6.0) (1.21.6)
Requirement already satisfied: pynacl>=1.0.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==26.6.0) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==26.6.0) (38.0.1)
Requirement already satisfied: bcrypt>=3.1.3 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from paramiko->cg==26.6.0) (4.0.1)
Requirement already satisfied: cattrs>=1.8 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests-cache->cg==26.6.0) (22.2.0)
Requirement already satisfied: url-normalize>=1.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests-cache->cg==26.6.0) (1.4.3)
Requirement already satisfied: appdirs>=1.4.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests-cache->cg==26.6.0) (1.4.4)
Requirement already satisfied: urllib3>=1.25.5 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests-cache->cg==26.6.0) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==26.6.0) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from requests[security]->cg==26.6.0) (2022.9.24)
Requirement already satisfied: fastapi in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from sendmail-container->cg==26.6.0) (0.85.1)
Requirement already satisfied: uvicorn in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from sendmail-container->cg==26.6.0) (0.5.1)
Requirement already satisfied: python-multipart in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from sendmail-container->cg==26.6.0) (0.0.5)
Requirement already satisfied: exceptiongroup in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cattrs>=1.8->requests-cache->cg==26.6.0) (1.0.0rc9)
Requirement already satisfied: cffi>=1.12 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cryptography>=2.5->paramiko->cg==26.6.0) (1.15.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth->cg==26.6.0) (0.4.8)
Requirement already satisfied: starlette==0.20.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from fastapi->sendmail-container->cg==26.6.0) (0.20.4)
Requirement already satisfied: anyio<5,>=3.4.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from starlette==0.20.4->fastapi->sendmail-container->cg==26.6.0) (3.6.1)
Requirement already satisfied: python-dotenv>=0.10.4 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pydantic->cg==26.6.0) (0.21.0)
Requirement already satisfied: tomli>=1.0.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pytest->cgmodels>=0.10.5->cg==26.6.0) (2.0.1)
Requirement already satisfied: iniconfig in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from pytest->cgmodels>=0.10.5->cg==26.6.0) (1.1.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==26.6.0) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==26.6.0) (2.13.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from ruamel.yaml->housekeeper>=2.5->cg==26.6.0) (0.2.6)
Requirement already satisfied: h11 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from uvicorn->sendmail-container->cg==26.6.0) (0.14.0)
Requirement already satisfied: httptools in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from uvicorn->sendmail-container->cg==26.6.0) (0.5.0)
Requirement already satisfied: uvloop in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from uvicorn->sendmail-container->cg==26.6.0) (0.17.0)
Requirement already satisfied: websockets>=6.0 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from uvicorn->sendmail-container->cg==26.6.0) (10.3)
Requirement already satisfied: pycparser in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->cg==26.6.0) (2.21)
Requirement already satisfied: sniffio>=1.1 in /home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages (from anyio<5,>=3.4.0->starlette==0.20.4->fastapi->sendmail-container->cg==26.6.0) (1.3.0)
/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))

remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 15 (delta 5), reused 9 (delta 5), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/Clinical-Genomics/cg
   03e7557..a2d6c9f  master     -> origin/master
 * [new tag]         v26.6.0    -> v26.6.0
Already on 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating 03e7557..a2d6c9f
Fast-forward
 .bumpversion.cfg                              | 2 +-
 cg/__init__.py                                | 2 +-
 cg/cli/compress/fastq.py                      | 3 ++-
 cg/store/api/status.py                        | 2 +-
 setup.py                                      | 2 +-
 tests/cli/compress/test_cli_compress_fastq.py | 2 +-
 6 files changed, 7 insertions(+), 6 deletions(-)
/home/hiseq.clinical
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/hiseq.clinical
done.
Log deploy... done.
cg, version 26.6.0

**Comment by ChrOertlin** [comment]
Part of: https://github.com/Clinical-Genomics/project-planning/issues/474

**Pull request merged**
