### PR TITLE
Only include uploaded analyses with matching workflow

### PR DESCRIPTION
**Pull request by islean**
## Description

When generating the delivery message for an order, we are currently including all analyses with a completed status in the order. On top of this, errors are given due to RSYNC analyses fulfilling the criteria but having no matching case in the database. This PR adds validation that the analyses should
- be uploaded
- match the same workflow.

### Fixed

- Validation in the order delivery message includes checks for uploaded_at and correct workflow.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
👍

**Review by seallard — APPROVED** [review]
This works 👍 
We can remove all of it once we have removed rsync analyses

**Comment by islean** [comment]
Tested on stage and only uploaded analyses with the matching workflow are included now.

**Comment by islean** [comment]
Deployed to cg-services-prod.

**Pull request merged**
