### PR TITLE
json orderform validation error

### PR DESCRIPTION
**Pull request by moonso**
This PR fixes some validation problems with json orderforms

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do submit mip-json.json

### Expected test outcome
- [ ] check that orderform is accepted and order is saved in database
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to lab, production, MM

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result: 
image
🆗 json properly parsed and validated
image
🆗 order saved in database

**Review by patrikgrenfeldt — COMMENTED** [review]
⚡

**Comment by patrikgrenfeldt** [comment]
Deployed to clinical-db:
image

**Comment by henrikstranneheim** [comment]
Well done!

**Comment by patrikgrenfeldt** [comment]
> Well done!

Thanks and thank you for having the discussion on how we could solve it!

**Pull request merged**
