### PR TITLE
add/BALSAMIC AscatNgs tags for delivery

### PR DESCRIPTION
**Pull request by ivadym**
## Description

Deliver BALSAMIC AscatNgs & Delly files:
- `[ascat/delly].all.filtered.pass.vcf.gz`
- `[ascat/delly].all.filtered.pass.vcf.gz.tbi`
- Ascat `PDF` report

CNVkit filtered:
- `cnvkit.all.filtered.pass.vcf.gz`
- `cnvkit.all.filtered.pass.vcf.gz.tbi`

[*] Since `Delly` and `AscatNgs` share the same tags (BALSAMIC issue), they will be delivered together under the `["vcf-sv-research", "filtered"]` labels.

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] `cg deliver analysis -d balsamic -c CASE_ID`

### Expected test outcome
- [x] check that `manta`, `ascat`, `cnvkit`, and `delly` vcfs are delivered
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by ashwini06 — COMMENTED** [review]
👍🏼 
@ivadym: Additionally for panel cases, we need to deliver the cnvkit vcf file (.cnvkit.all.filtered.pass.vcf.gz), please correct those cnvkit tags as well. (Right now cnvkit vcf files are not delivered, only tumor.merged.cnr, tumor.merged-diagram.pdf, tumor.merged-scatter.pdf is delivered)

Also, for panel cases we have `.TNscope_umi.all.filtered.pass.vcf.gz` and in the current list, it is not mentioned. We need to discuss with the prod team (after holidays) if we need to deliver this file by default or how?

**Review by ashwini06 — APPROVED** [review]
👍🏼

**Review by Mropat — APPROVED** [review]

**Comment by ivadym** [comment]
Succsesful delivery for a `TN_WGS` case:
Screen Shot 2021-12-31 at 13 21 46

**Comment by ivadym** [comment]
Delivery for TN_panel case:

Screen Shot 2021-12-31 at 13 46 46

**Pull request merged**
