### PR TITLE
add/Automatic fastq delivery for cases where no analysis is run

### PR DESCRIPTION
**Pull request by Vince-janv**
## Description
For tickets from eg cust001 no analysis is run and they only want fastq files sent to them. As this is time-critical for them automation would prevent prod-bioinfo from late deliveries and long hasta wait time for rsync jobs. The function is intended to be run by a cron-tab
### Added

- A new minimalistic workflow for delivering fastq files to caesar. Mimicking the structure of our current workflows.

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh add/Automatic-upload-of-fastq`
- [x] Makes sure all fastq cases except livingsatyr are set to `hold` (else you can run `/home/hiseq.clinical/VJ_area51/set_status_db_stage/set_stat_db_stage.py)`

#### Starting jobs
- [x] do `cg workflow fastq start-available`
- [x] Optional: Test one of the rsync commands in the sbatch script created as` hiseq.clinical`.
#### Storing analysis
- [x] Manually set the tb-analysis to `completed`
- [x] run `cg workflow fastq store-available`

#### After starting jobs
- [x] Check trailblazer in cigrid-stage and make sure the analysis has started and failed (might have to run `trailblazer scan`)
- [x] Optional: Check that the rsync went trough.
#### After storing analysis
- [x] Check that an analysis for `livingsatyr` has been stored

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by Vince-janv** [comment]
After running `cg workflow fastq start-available`:

Screenshot 2022-03-28 at 16 37 59
Screenshot 2022-03-28 at 17 05 23

**Comment by Vince-janv** [comment]
Testing the first rsync command in the .sh file:

Screenshot 2022-03-28 at 17 14 26
Screenshot 2022-03-29 at 08 35 19

**Comment by Vince-janv** [comment]
Testing `cg workflow fastq store-available`:

Screenshot 2022-03-28 at 17 10 37

**Comment by henrikstranneheim** [comment]
@Vince-janv What is the status of this one?

**Comment by Vince-janv** [comment]
> @Vince-janv What is the status of this one?

@henrikstranneheim This can be closed. I got some feedback on this one from @Mropat to rework the structure, so I started from scratch with a new PR (the one merged earlier).

**Comment by henrikstranneheim** [comment]
@Vince-janv Great! Closing

**Pull request closed without merging**
