### PR TITLE
Remove is uploaded to vogue

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Remove is uploaded to vogue from db

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b Remove-is-uploaded-to-vogue -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
💯

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@islean Could you help me remove:

´´´
  uploaded_to_vogue_at: string | null
```
in  clinical-genomics-ui src/services/interfaces.ts ?

CLI and alembic works!

**Comment by islean** [comment]
@henrikstranneheim Should I merge this PR https://github.com/Clinical-Genomics/clinical-genomics-ui/pull/379 one prior to this one then?

**Comment by henrikstranneheim** [comment]
@islean Yes, Thx that would be great!

**Comment by islean** [comment]
@henrikstranneheim It is deployed now!

**Pull request closed without merging**
