### PR TITLE
feat, prio order for balsamic

### PR DESCRIPTION
**Pull request by hassanfa**
This PR suggests a reformed priority order for BALSAMIC runs:

The oder is:
1. Check if priority is provided by user
2. Check if case_obj has job priority
3. take from BALSAMIC `qos` value in `cg.yaml`

Also a bit of code formatting and linting.

**How to prepare for test**:
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [ ] login to ...
- [ ] do ...

**Expected test outcome**:
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by barrystokman** [comment]
Can you add the information about the test cases/expected outcome and so on?

**Comment by barrystokman** [comment]
Something to discuss in general: it took me a while to find the actual code change. In the future, can we put the blacking in separate commits?

**Comment by hassanfa** [comment]
> Can you add the information about the test cases/expected outcome and so on?

I'm on it. Hasta was down and I couldn't test it yet. Thus couldn't propose a good test scenario. 

> Something to discuss in general: it took me a while to find the actual code change. In the future, can we put the blacking in separate commits?

Good point. I actually thought I did commit `black` and code change but I made a mistake there... if it is hard to review without distinct code change, I can try to fix it: revert changes and commit code again from scratch or open a new PR.

**Comment by barrystokman** [comment]
> I can try to fix it: revert changes and commit code again from scratch or open a new PR.

No it's fine, but it's something for all of us to consider for future commits.

**Comment by Mropat** [comment]
This feature is also added in #687

**Pull request closed without merging**
