### PR TITLE
Balsamic config case to send lims id of samples

### PR DESCRIPTION
**Pull request by Mropat**
Added:
New CLI options sent to BALSAMIC during case config:
```
--normal-sample-name
--tumor-sample-name
```
These options are also added in BALSAMIC, however they are optional in BALSAMIC. 

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat/balsamic-cofig-sample-id`

### How to test
- [x] login to hasta
- [x] do us and cg balsamic config-case fleetjay

### Expected test outcome
- [x] check that case config (crackpanda.json) contains values for LIMS ID of each sample 
- [x] Take a screenshot and attach or copy/paste the output.

image

## Review
- [x] code approved by MM
- [x] tests executed by MR
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes

## Depends on
https://github.com/Clinical-Genomics/BALSAMIC/pull/520

## Implementation Plan
- [x] Deploy this branch
- [x] Inform cancer bioinfo and production

(No documentation update since the change is backwards compatible, new arguments are optional, and the effect of this, although a major CLI change, are internal only)

### CODE REVIEW

**Comment by Mropat** [comment]
Storing new deliverables works on stage
image

**Comment by Mropat** [comment]
"New" bundle tags 
oneel
image

**Comment by Mropat** [comment]
Bundle looks good for panels
image

**Comment by Mropat** [comment]
unitedbeagle stored successfully with new tags
image

**Comment by Mropat** [comment]
moralgoat stored successfully with new tags
image

**Comment by hassanfa** [comment]
BASLAMIC updated to `6.0.3` this can merged I guess.

**Review by hassanfa — APPROVED** [review]
ok from balsamic PoV :-D

**Comment by Mropat** [comment]
installed on stage
image

**Comment by Mropat** [comment]
Deployed on prod
image

**Pull request merged**
