### PR TITLE
Clinical delivery to balsamic upload

### PR DESCRIPTION
**Pull request by GustavLagneborgScilifelab**
## Description
This PR serves to automate the clinical delivery for Balsamic case uploads. It uses the feature built in this PR:
https://github.com/Clinical-Genomics/cg/pull/1537 

### Added

- Adding clinical delivery to the balsamic upload

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by GustavLagneborgScilifelab** [comment]
Test to upload balsamic case modernferret with command `cg upload -f modernferret -r`: 
Screenshot 2022-11-09 at 09 53 36

**Comment by GustavLagneborgScilifelab** [comment]
Test to upload balsamic-umi case equalbug with command `cg upload -f keensnake -r`:
Screenshot 2022-11-09 at 11 35 27

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by GustavLagneborgScilifelab** [comment]
Test to upload a balsamic case that shouldn't be uploaded to caesar with command `cg upload -f sweetmidge -r`:
Screenshot 2022-11-09 at 13 29 38

**Comment by GustavLagneborgScilifelab** [comment]
Upload modernferret again when the inbox folder is already created:
Screenshot 2022-11-09 at 13 33 17

**Comment by GustavLagneborgScilifelab** [comment]
Successfully deployed in production 🥂 
Screenshot 2022-11-09 at 13 58 46

**Pull request merged**
