### PR TITLE
making percent_kth requiered

### PR DESCRIPTION
**Pull request by mayabrandi**
We have a problem that the %kth field in the application tag table in the database, often is empty. Valtteri has now filled in the field for all tags that are not archived. The archived tags will not be touched or used in the future, so I suppose we can ignore those? Can we make the field not nullable in the database as soon as this PR is approved, or is there anything else that could be affected by this that needs to be fixed first? @patrikgrenfeldt 

Script was added to update the database. It has been tested on cg-stage

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@mayabrandi tests fail, Will you have a look?

**Comment by mayabrandi** [comment]
The problem is that add_application now needs to require percent_kth as swell. It has lots of impact on several tests etc. Im working on it. Maybe we should have a quick chat about it.

**Comment by patrikgrenfeldt** [comment]
seems like the PR-check is failing?

**Comment by mayabrandi** [comment]
Its the long string (pathes) that we decided on to ignore. You remember?

**Comment by mayabrandi** [comment]
This one is just waiting for to be deployed. Can me and @adrosenbaum  do that? Since you are busy @patrikgrenfeldt ?

**Comment by barrystokman** [comment]
I'd recommend looking at the merge confilcts first :)

**Comment by ingkebil** [comment]
Is there any reason why the PR template has not been used? E.g. where are the sign offs, the test case, the documented test, the motivation off the version bump? It's a bit of a stretch to consider this "ready for deploy', don't you think?

**Comment by adrosenbaum** [comment]
I can look at it. But agree with Barry that the merge conflicts should be resolved first! Also finding the 'true' changes in a bunch of blacked code is like finding a needle in a haystack hehe, so maybe we can look at this together once the conflicts are resolved 😄

**Comment by mayabrandi** [comment]
So me and Patrik have already gone through the code changes I made (three lines in total) and he also approved on the black changes in the same PR. That is why I directed my question to Patrik and not to Barry or Kenny. The merge conflicts obviously need to be fixed. They were not there before when I committed the black changes. Ill look into them now. Then maybe Adam and me kan deploy instead of Patrik and me as we talked about on slack the other day. @patrikgrenfeldt

**Pull request closed without merging**
