### PR TITLE
Migrate crunchy models

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR migrates the crunchy pydantic models to v2, part of project https://github.com/Clinical-Genomics/project-planning/issues/514.

### Fixed
- Use `BaseModel` and `conlist` from Pydantic v2
- Add `Optional` type hints to fields initialised as `None`

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by islean — APPROVED** [review]
🔥 🔥 🔥

**Review by diitaz93 — APPROVED** [review]
neat 👍

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by seallard** [comment]
Deployed to stage and tested with `cg decompress sample whollypickedeel`

**Pull request merged**
