### PR TITLE
Fix/add concentration dragen sheet

### PR DESCRIPTION
**Pull request by karlnyr**
## Description
Currently one is unable to create a samplesheet through `cg workflow fluffy create-samplesheet case_id` if the header is following the new samplesheet header structure used in [dragen demultiplexing](https://github.com/Clinical-Genomics/cg/pull/1261). Changes where [made to fluffy](https://github.com/Clinical-Genomics/fluffy/pull/32) to account for this, however cg also adds concentration and sequence date (extracted from LIMS) which was not updated accordingly.

### Added

- The option to read the new samplesheet header used in Dragen demultiplexing

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh fix/add-concentration-dragen-sheet`

### How to test
- [x] do `cg workflow fluffy create-samplesheet closeparrot`

### Expected test outcome
- [x] Check for correct information in stamplesheet
    - [x] `head -n 10 /home/proj/"${ENVIRONMENT}"/nipt/cases/closeparrot/SampleSheet_2115619_NIPT.csv`
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @barrystokman 
- [x] tests executed by @karlnyr 
- [x] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [x] Inform to @Clinical-Genomics/data-analysis

### CODE REVIEW

**Review by barrystokman — APPROVED** [review]
great fix 👍🏻 

The Fluffy workflow should really be decoupled from the sample sheet, which is a demultiplexing artifact. Something for the (near) future :)

**Comment by karlnyr** [comment]
Tests excecuted:
image

**Comment by karlnyr** [comment]
@barrystokman Can I merge and deploy this?

**Comment by barrystokman** [comment]
@karlnyr go for it!

**Comment by karlnyr** [comment]
Installed in prod:
image

**Pull request merged**
