### PR TITLE
Hide development analyses

### PR DESCRIPTION
**Pull request by islean**
## Description

Part of https://github.com/Clinical-Genomics/cigrid-ui/issues/493 together with https://github.com/Clinical-Genomics/trailblazer/pull/490. Ensures that development analyses are added in TB hidden by default.

### Added

-

### Changed

- Analyses by cust000 are sent to TB with is_hidden set to True.

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b hide-development-analyses -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by islean** [comment]
Test successful in stage:

`cg workflow mip-dna start justhusky`

Excluding hidden analyses:
image

Including hidden analyses:
image

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by islean** [comment]
Final test with a not internal customer gave a visible analysis: 
image

**Comment by islean** [comment]
Deployed to Hasta:

```
Log deploy... done.
cg, version 62.2.12
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 56 (delta 35), reused 49 (delta 33), pack-reused 0 (from 0)
Unpacking objects: 100% (56/56), done.
From https://github.com/Clinical-Genomics/cg
   a0bce49..234f273  master     -> origin/master
   f9aaac4..379b0b8  add-raredisease-scout-upload -> origin/add-raredisease-scout-upload
   124ba20..32992a7  fix-clinical-delivery -> origin/fix-clinical-delivery
   ba4f52c..360d38f  improve-order-flow-main -> origin/improve-order-flow-main
   fa232c8..3c6742b  refactor-fastq-workflow -> origin/refactor-fastq-workflow
 * [new tag]         v62.2.12   -> v62.2.12
Already on 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating a0bce49..234f273
Fast-forward
 .bumpversion.cfg             | 2 +-
 cg/__init__.py               | 2 +-
 cg/apps/tb/api.py            | 2 ++
 cg/meta/workflow/analysis.py | 7 +++++++
 pyproject.toml               | 2 +-
 5 files changed, 12 insertions(+), 3 deletions(-)
/home/isak.ohlsson
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[isak.ohlsson@hasta:~] [P_base] $ 
```

**Pull request merged**
