### PR TITLE
set bait set udf

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds possibility to set bait set in lims

**How to prepare for test**:
- [x] ssh to hasta
- [x] us
- [x] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat/set-bait-set`

**How to test**:
1. Run: `cg workflow mip-dna config-case -d usablestud`
1. Run: `cg set sample BIL2299A1 -kv bait_set agilent_sureselect_cre_11.1`
1. Run: `cg set sample BIL2299A2 -kv bait_set agilent_sureselect_cre_11.1`
1. Run: `cg set sample BIL2299A3 -kv bait_set agilent_sureselect_cre_11.1`
1. Run: `cg workflow mip-dna config-case -d usablestud`

**Expected test outcome**:
- [x]  cg workflow mip-dna config-case -d usablestud` should fail with a LIMS error
- [x] Check in lims that the expected value was set for the samples
- [x]  cg workflow mip-dna config-case -d usablestud` should print a config since the lims bait set is set for each sample

**Review:**
- [x] code approved by @henrikstranneheim 
- [x] tests executed by @henrikstranneheim 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
**Results**
1. Run: `cg workflow mip-dna config-case -d usablestud` ✅ 

Screenshot 2020-04-17 at 15 11 11

1. Run: `cg set sample BIL2299A1 -kv bait_set agilent_sureselect_cre_11.1` - FAIL

Screenshot 2020-04-17 at 15 11 52

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt We get a `requests.exceptions.HTTPError: 400: Invalid UDF: Bait Set`

**Comment by patrikgrenfeldt** [comment]
@mayabrandi We can't set the Bait Set the way we thought, do you know how it's supposed to be done?

**Comment by mayabrandi** [comment]
Bait Set was not avalible as UDF on sample level until recently. It seems the test was performed before the UDF was added. Redo the test and see if it works. @patrikgrenfeldt

**Comment by henrikstranneheim** [comment]
@mayabrandi Do we need to copy lims prod to stage for this? I redid the tests this morning with the same results.

**Comment by mayabrandi** [comment]
:) I added Bait Set to sample on stage now! So used to tests performed on production, so I forgot you were testing against stage. Redo it now!

**Comment by henrikstranneheim** [comment]
@mayabrandi Great! I will redo the tests

**Comment by henrikstranneheim** [comment]
**Results**
1. Run: `cg workflow mip-dna config-case -d usablestud` ✅ 

Screenshot 2020-04-20 at 11 48 46

1. Run: `cg set sample BIL2299A1 -kv bait_set agilent_sureselect_cre_11.1`  ✅ 

Screenshot 2020-04-20 at 11 49 32


1. Run: `cg set sample BIL2299A2 -kv bait_set agilent_sureselect_cre_11.1` ✅ 

Screenshot 2020-04-20 at 11 49 48


1. Run: `cg set sample BIL2299A3 -kv bait_set agilent_sureselect_cre_11.1` ✅ 

Screenshot 2020-04-20 at 11 50 06

1. Run: `cg workflow mip-dna config-case -d usablestud` ✅ 

Screenshot 2020-04-20 at 11 50 32

**Comment by henrikstranneheim** [comment]
@mayabrandi and @patrikgrenfeldt Seems to work. It does complain about "bait_set is not a property of sample", but it then seems to sets it correctly.

**Comment by patrikgrenfeldt** [comment]
Deployed on hasta:
image

**Comment by annaengstrom** [comment]
Any plan for documentation regarding `cg set sample`?

**Comment by henrikstranneheim** [comment]
@moahaegglund @emmser @annaengstrom Where would you like it to be in AM? You are the one that will use this the most and most likely know the best place to put it. Recommend a place and I can write a short description

**Comment by annaengstrom** [comment]
Where do you normally put this kind of documentation?

**Comment by moahaegglund** [comment]
What do you think about 1713, "Handling of files sequenced outside Clinical Genomics"?

**Comment by henrikstranneheim** [comment]
For production: If a process (automated or human) uses this as a required command it should be placed in the corresponding AM document. 
Codewise: This is part of the cli and most (if not all) develeoper will run the cli or look into the code before reading docs (we are lazy people by nature letting the computer do the work for us 😄 )

**Comment by henrikstranneheim** [comment]
@moahaegglund I will take a look

**Comment by annaengstrom** [comment]
This is a general functionality, not only for 1713, so shouldn't it be in a "cg" document?
@AnnaLeinfelt

**Comment by annaengstrom** [comment]
Document 1713 could refer to the other document

**Comment by annaengstrom** [comment]
How about updating the PR template to also include "Documentation"?

**Comment by henrikstranneheim** [comment]
> How about updating the PR template to also include "Documentation"?

Yes, that sounds like a good idea.

**Comment by moahaegglund** [comment]
> This is a general functionality, not only for 1713, so shouldn't it be in a "cg" document?
> @AnnaLeinfelt

Yes, this sounds better

**Comment by henrikstranneheim** [comment]
Yes, maybe some of the more general commands of cg should be in a "method" or "tool" documentation.

**Comment by annaengstrom** [comment]
Do we have a "cg" document?

**Comment by henrikstranneheim** [comment]
I will have a look and if not I will create one

**Pull request merged**
