### PR TITLE
Fetch flowcell from PDC: update destination server for novaseq flowcells

### PR DESCRIPTION
**Pull request by barrystokman**
This PR updates the destination server in the PdcAPI so that archived novaseq flowcells will be sent to the correct server, after the migration of novaseq demultiplexing from thalamus to hasta.

As an added bonus, the status for the flowcell will be set to `retrieved` after retrieval from PDC, instead of `ondisk`.
Setting the status to `ondisk` after retrieval from PDC was implemented to prevent the PDC retrieval queue from getting stuck: flowcells would still have the status of  `processing`, preventing the start of the retrieval process for the next flowcell. However, the status `ondisk` is reserved for flowcells that have been demultiplexed and moved to `/home/proj/production/demultiplexed-runs/`. The status `ondisk` with is set with `cg transfer flowcell <flowcell_id>`. Fortunately, this situation has not lead to issues in production!

### How to prepare for test
- [x] ssh to hasta
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat/novaseq-pdc-to-hasta`

### How to test
- [x] select an archived flowcell. An archived flowcell has the `status` `removed` on status-db
- [x] run the command `cg backup fetch-flowcell -f <flowcell_id>`

### Expected test outcome
- [x] check that the flowcell has the `status` `requested` (queued for retrieval) or `processing` (retrieval in progress)
- [x] check that when the retrieval is done the `status` changes to `retrieved`
- [x] check that the flowcell has a run directory in `/home/proj/stage/flowcells/novaseq/runs/`
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by @barrystokman 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MINOR** - when you add functionality in a backwards compatible manner

## Implementation Plan
- [ ] To be deployed together with https://github.com/Clinical-Genomics/servers/pull/483

### CODE REVIEW

**Comment by moonso** [comment]
Hi @barrystokman , could we do the sql migrations with [alembic](https://alembic.sqlalchemy.org/en/latest/) as noted [here](https://github.com/orgs/Clinical-Genomics/projects/30#card-53653130). I'm sure @Mropat can help you if needed.

**Comment by barrystokman** [comment]
@moonso sure!

**Comment by barrystokman** [comment]
## Alembic tests:

### Precondictions:
image
image
image

### TC1 Run first upgrade:
`alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini upgrade 6d7`

image

Result:
image
image

`retrieved` added to status column enum in flowcell table, `alembic_version` table updated with `version_number` 👍🏻 

### TC2 Run second upgrade:
`alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini upgrade 37e`
image

Result:
image

image

`test` table created, `alembic_version` table updated with `version_number` 👍🏻 

### TC3 Downgrade one version:
`alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini downgrade -1`
image

image
image
image

Result:
`test` table dropped, `retrieved` still in `status` column enum in `flowcell` table, `alembic_version` table updated with `version_number` 👍🏻 

### TC3 Upgrade to head:
`alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini downgrade -1` (back to no revisions, or preconditions situation)

`alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini upgrade head`

image
image
image
image

Result:
Both upgrades executed 👍🏻 

### TC4 Alembic upgrade script ran with `bash update-cg-stage.sh`
Back to reconditions `alembic --config /home/proj/stage/servers/alembic/cg/alembic-stage.ini downgrade base`

update cg-stage using the script that contains `alembic --config "${PROJECT_HOME}/servers/alembic/cg/alembic-prod.ini upgrade head"`

`bash /home/proj/stage/servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat/novaseq-pdc-to-hasta`


Result:
image FAILED!

**Comment by barrystokman** [comment]
Checks fail on the installation of `cryptography`, which had a new version released yesterday? Can't be a coincidence... Any ideas how to fix it?

**Review by Mropat — APPROVED** [review]
:1st_place_medal:  awesome work Barry!
Finally we use alembic :fire:

**Comment by barrystokman** [comment]
image

**Pull request merged**
