### PR TITLE
Date functions

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR changes the datefunctions in cg to fetch data fom sample level udfs instead of searching processes related to a specific saple id. 

**How to prepare for test**:
- [x] ssh to hasta 
- [x] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh date_functions`

**How to test**:
- [x] run 
```
us
cg transfer lims --status prepared --sample-id <some sample>
cg transfer lims --status recieved --sample-id <some sample>
cg transfer lims --status delivered --sample-id <some sample>

```

**Expected test outcome**:
- [x] see if the missing dates for the samples in [this](https://github.com/Clinical-Genomics/cg/issues/636) issue have been loaded to the database

**Before Deploy**
The  code can not be put in production before:

- [x] Old samples have been loaded with data with [this](https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/one_time_scripts/set_old_dates.py) script.
- [x] New Epps are set up to populate the new udfs from within lims in the relevant steps.

**Review:**
- [x] code approved by @barrystokman
- [x] tests executed by @mayabrandi 
- [x] "Merge and deploy" approved by @barrystokman 

Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by mayabrandi** [comment]
Testing according to above:

Chose a sample with the new sample udfs set in lims:

Skärmavbild 2020-05-19 kl  13 25 15


Cleaned the date fields for the sample in the database:

Skärmavbild 2020-05-19 kl  13 23 27


Ran cg transfer for the sample:

Skärmavbild 2020-05-19 kl  13 41 03


Dates were added:

Skärmavbild 2020-05-19 kl  13 40 56

**Comment by barrystokman** [comment]
`_get_all_step_dates_from_input` and `_get_all_step_dates` are not in use anymore now, they could be removed.

**Comment by barrystokman** [comment]
the imported `PROCESSES` is also not in use anymore

**Comment by barrystokman** [comment]
Bumped:
image
Deployed:
image

**Pull request merged**
