### PR TITLE
Update mip-rna delivery

### PR DESCRIPTION
**Pull request by moahaegglund**
### Added

- Add files to mip-rna delivery

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh update_rna_delivery`

### How to test
- [x] do `cg deliver analysis --dry-run -d mip-rna -c setghoul`

### Expected test outcome
- [x] check that the files `ACC9030A4_lanes_1234_starfusion.tsv` and `ACC9030A4_lanes_1234_arriba.tsv` is included in delivery.
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by @moahaegglund 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [X] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moahaegglund** [comment]
The files are linked, test successful: 
Screenshot 2022-03-02 at 20 40 26

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by barrystokman — APPROVED** [review]
👍🏻

**Comment by moahaegglund** [comment]
Stage:
Screenshot 2022-03-03 at 13 48 40
Production:
Screenshot 2022-03-03 at 14 01 00

**Pull request merged**
