### PR TITLE
Set priority for tower compute environment

### PR DESCRIPTION
**Pull request by fevac**
## Description

Closes https://github.com/Clinical-Genomics/MTP-RNAFUSION/issues/17

### Changed

- Set compute environment according the case priority

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b comp_env_prio -a

   bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-servers-stage.sh update_comp_env
    ```

### How to test

- [x] `cg workflow rnafusion run -d CASE`. Make sure that the --compute-env has the suffix _$priority (e.g -normal)
- [x] `cg workflow taxprofiler run -d CASE`. Make sure that the --compute-env has the suffix _$priority (e.g -normal)

### Expected test outcome

- [x] image

- [x] image
 

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by fevac** [comment]
tests are passing

**Comment by fevac** [comment]
test for taxprofiler passing now

**Review by henrikstranneheim — APPROVED** [review]
LGTM 👍 ! What is the current issue and how will this be used?

**Comment by fevac** [comment]
the current issue is that currently the head job priority for Tower runs is fixed by the compute environment so all cases get the same priority for the head job (the priority of the other jobs is properly set). As we cannot dynamically change the headjob priority, Seqera support recommended to use different compute environments with different priorities. Anders created compute environments that are identical with the exception of the `qos` (so hasta-low, hasta-normal, hasta-high, hasta-express) but we are currently not using it. This will set the automatically the corresponding environment according to the priority of the case.

**Comment by henrikstranneheim** [comment]
> the current issue is that currently the head job priority for Tower runs is fixed by the compute environment so all cases get the same priority for the head job (the priority of the other jobs is properly set). As we cannot dynamically change the headjob priority, Seqera support recommended to use different compute environments with different priorities. Anders created compute environments that are identical with the exception of the `qos` (so hasta-low, hasta-normal, hasta-high, hasta-express) but we are currently not using it. This will set the automatically the corresponding environment according to the priority of the case.

Nice! Then I understand. 😄 Thx!

**Comment by fevac** [comment]
- Deploy to stage
image

- Deploy to prod
image

**Pull request merged**
