### PR TITLE
add MHT to the panel masterlist

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds MHT to the panel masterlist

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- us
- cg workflow mip-dna analysis panel -p wiredbass

### Expected test outcome
- [ ] check that the top part of the output printed to screen beginning with "Fetching gene panels" should contain the panels MHT.
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to production

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by moonso — APPROVED** [review]
👍 heavy review!

**Review by Mropat — APPROVED** [review]
:+1:

**Comment by patrikgrenfeldt** [comment]
Test result:
image
🆗

**Comment by patrikgrenfeldt** [comment]
Deployed to Hasta:
image

Deployed to clinical-db:
image

**Pull request merged**
