### PR TITLE
feat(store): updates tags for housekeeper

### PR DESCRIPTION
**Pull request by jemten**
Updates tags for housekeeper relating to chromograph and upd tracks. 
Relates to [housekeeper/#76](https://github.com/Clinical-Genomics/housekeeper/issues/76)

The following tags should be added to housekeeper:
| File type | Tags|
| --------- | ---- |
|\<file-prefix\>.regions.bb | upd, regions|
|\<file-prefix\>.sites.bb | upd, sites|
|\<file-prefix\>.regions_\<contig\>.png | chromograph, upd, regions|
|\<file-prefix\>.sites_\<contig\>.png | chromograph, upd, sites|
|\<file-prefix\>_\<contig\>.png | chromograph, tcov|
|\<file-prefix\>.\<sample\>.bw | rhocall-viz|

### How to prepare for test
- [x] run justhusky with the config changes in [servers/pull/#427](https://github.com/Clinical-Genomics/servers/pull/427)
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh mip_9.0.3`

### How to test
- [x] cg workflow mip-dna store analysis
- [x] housekeeper get file -v \<bundle-version\>

### Expected test outcome
- [x] check that the files are added together with their respective tags ✅ 
- [x] Take a screenshot and attach or copy/paste the output. ✅ 

## Review
- [x] code approved by HS
- [x] tests executed by AJ
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by jemten** [comment]
@dnil - With this PR housekeeper should store the big bed file from upd and the big wig file from rhocall viz. Was there a plan to display these tracks in scouts IGV view?

**Comment by Mropat** [comment]
:+1:  Just need to post a validation screenshot to merge!

**Comment by dnil** [comment]
> @dnil - With this PR housekeeper should store the big bed file from upd and the big wig file from rhocall viz. Was there a plan to display these tracks in scouts IGV view?

Nicely done! Yes, absolutely! There are keys for them in Scout; let me know if you want a list for the load config!

**Comment by jemten** [comment]
cg workflow mip-dna store analysis analysis/justhusky_config.yaml ✔️ 
image

housekeeper get file -v 24966 justhusky ✔️ 
image

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
Screenshot 2020-10-23 at 15 24 46

**Pull request merged**
