### PR TITLE
Feat always get samples related flowcell

### PR DESCRIPTION
**Pull request by karlnyr**
## Description
This is a very small PR to make the usage of `cg get sample` more relatable to production. There are seldom cases were we use this commando without the current flag `-f` and thus I change it to be its defaults instead and added the option to hide it if so needed.

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat-always-get-samples-related-flowcell`

### How to test
- [x] do `cg get sample <sample_id>`
- [x] do `cg get sample -hf <sample_id>`

### Expected test outcome
- [x] check that related flowcells are retrieved when asked to
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS
- [x] tests executed by @karlnyr 
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in [Atlas documentation
MIP analysis for Whole genome and Exome](https://clinical-genomics.github.io/atlas/infrastructure/production/workflows/MIP_analysis/)
- [ ] Deploy this branch
- [x] Inform to @Clinical-Genomics/production

### CODE REVIEW

**Comment by karlnyr** [comment]
Executing tests
image

**Review by henrikstranneheim — APPROVED** [review]
Looks good!

**Comment by henrikstranneheim** [comment]
@karlnyr Just a test that is failing. If you could fix that and then we can merge and deploy

**Comment by karlnyr** [comment]
> @karlnyr Just a test that is failing. If you could fix that and then we can merge and deploy

Done and done I believe

**Review by Mropat — APPROVED** [review]

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
```
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages (from rich->housekeeper>=2.5->cg==21.5.1) (2.6.1)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-21.5.1-py3-none-any.whl size=459630 sha256=9cd2c72221d8ec098d1c1a23db7738873dbfc7c470f6178f16b2a3872ff0f405
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-s1bqriyo/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 21.5.0
    Uninstalling cg-21.5.0:
      Successfully uninstalled cg-21.5.0
Successfully installed cg-21.5.1
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/home/proj/bin/conda/envs/P_main/bin/python -m pip install --upgrade pip' command.
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 14 (delta 12), reused 8 (delta 7), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/Clinical-Genomics/cg
   15cb110..2dd7902  master     -> origin/master
 * [new tag]         v21.5.1    -> v21.5.1
Updating 15cb110..2dd7902
Fast-forward
 .bumpversion.cfg                     |  3 ++-
 CHANGELOG.md                         |  5 +++++
 cg/cli/get.py                        |  6 +++---
 setup.py                             |  2 +-
 tests/cli/get/test_cli_get_sample.py | 14 +++++++-------
 5 files changed, 18 insertions(+), 12 deletions(-)
/home/henrik.stranneheim/git/cg
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim/git/cg
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
argcomplete 1.12.1 has requirement importlib-metadata<3,>=0.23, but you have importlib-metadata 0.8.
cg, version 21.5.1
housekeeper, version 3.2.0
demux, version 5.9.0
cglims, version 1.3.4
```

**Comment by henrikstranneheim** [comment]
@karlnyr Do you want to mention this to production?

**Comment by karlnyr** [comment]
> @karlnyr Do you want to mention this to production?

Can do, can I merge https://github.com/Clinical-Genomics/atlas/pull/135/ as well?

**Comment by henrikstranneheim** [comment]
@karlnyr Go ahead. Well done!

**Pull request merged**
