### PR TITLE
support current orderform

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes the support for the current RML OF. Support for NG-OF was accidentally pushed to prod.

### How to prepare for test
- [x] ssh to clinical-db (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to upload OF 1604:09

### Expected test outcome
- [x] check that the OF is accepted
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by DB
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by b4ckm4n — APPROVED** [review]
this looks correct 👍

**Comment by patrikgrenfeldt** [comment]
Tested on stage: 
image
👍

**Comment by moonso** [comment]
Great! Could you fill the boxes if the test is completed and don't forget to update the changelog!

**Review by moonso — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Pull request merged**
