### PR TITLE
Fix/scout upload api

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...
- Fixes bug where  upload_started_at and uploaded_at timestamps were not being updated in StatusDB upon successful Scout upload. This bug was happening because several instances of Store were instantiated in the same context

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [x] ssh to clinical-db (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta
- [x] cg upload -f civiltick

### Expected test outcome
- [x] check that Uploaded at timestamp is updated in StatusDB
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @patrikgrenfeldt 
- [x] tests executed by @karlnyr 
- [x] "Merge and deploy" approved by @moonso 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by moonso — COMMENTED** [review]
I do not understand what has been changed...

**Comment by patrikgrenfeldt** [comment]
A test would be nice that checks that the date was set upon success ☺️

**Comment by Mropat** [comment]
@patrikgrenfeldt @moonso 
The only thing that changed, is that I'm reusing context.obj["status"] for StatusDB in AnalysisAPI. 
Previously AnalysisAPI had its own instance of StatusDB. Perhaps multiple instances of an api + whatever alchy magic is beneath it, is causing the error.
I will try and reproduce this on stage, when that is available.

I will most likely not be writing a test for upload at this moment, because it is a monumental project, given the 12 API in the context.

**Comment by patrikgrenfeldt** [comment]
I'm suggesting a test that tests the date-logic only, mocking out all 'invoke's in the code below, thus only testing the code *in* the function `def upload(...)` not code outside of it

image

does it seem doable then?

**Comment by Mropat** [comment]
> I'm suggesting a test that tests the date-logic only, mocking out all 'invoke's in the code below, thus only testing the code _in_ the function `def upload(...)` not code outside of it
> 
> image
> 
> does it seem doable then?

Ill give it a shot

**Comment by Mropat** [comment]
After installing cg on master branch on STAGE, and asking Kalle to run cg upload -f civiltick (because I dont have permissions to upload civiltick files on Stage)
State of civiltick analysis:
image

After installing cg on fix/scout-upload-api branch on STAGE, and asking Kalle to run cg upload -f civiltick (because I dont have permissions to upload civiltick files on Stage)
image

Problem is resolved.

**Comment by Mropat** [comment]
Recap of conversation with @patrikgrenfeldt 

The source of the problem is function `cg upload`.
The function in question created multiple objects of class Store, which were sharing the same session due to how Alchy operates.
Re-using the object of Store already present in context, solves the problem (screenshots provided)

Why it is difficult to make tests for this:

`upload` function does multiple things:

It creates an instance of Store and checks if family exists in StatusDB
image

It creates the upload context, including all the API, storing them in context.obj
image

It also invokes all the upload commands for a family, if provided:
image

This particular block, is where the error would happen. When we try to update upload_started_at, the session of context.obj["status"] has been flushed, because we instantiated a new Store "api" as part of AnalysisAPI.

A typical test would import the command upload, invoke it, and test if upload_started_at has been changed from None to a timestamp.
This test is particularly challenging to implement, because the context of Upload is created directly in upload function, and can't be given to cli runner. So upload function both creates context, by calling real API classes as defined in the function, and performs logic using those classes.
This makes it challenging to create an instance of Store with mock family and analysis to test on, to be available both inside upload function and test scope, because what upload function does is create a store instance using defined objects.

I've gotten recommendation to learn to use monkeypatch to work around this, which I will definitely do, but learning to implement monkeypatch solution, and refactoring upload function would be very time consuming at the moment. I hope the stage test will be sufficient to bring production back to normal, and I can work on this in the next PR.

**Review by moonso — APPROVED** [review]
👍

**Comment by Mropat** [comment]
deployed on stage
image

**Comment by Mropat** [comment]
deployed on prod:
image

**Pull request merged**
