### PR TITLE
remove dead dependency colorclass

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
*This PR adds/fixes ...*
- remove dead dependency colorclass and its usage

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] ssh hasta
- [x] us
- [x] cg status cases

### Expected test outcome
- [x] check that the command works
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to ES

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
I think it looks good. Will they all have the same color now independent of tat_number? No good replacement lib for colorclass?

**Comment by patrikgrenfeldt** [comment]
> I think it looks good. Will they all have the same color now independent of tat_number? No good replacement lib for colorclass?

replaced with the package ansi

**Comment by patrikgrenfeldt** [comment]
Health status of ansi:
image
🆗 healthy

**Comment by patrikgrenfeldt** [comment]
Test result:
image
🆗 coloring works

**Comment by patrikgrenfeldt** [comment]
Deploy to stage:
image

Deploy to prod on Hasta:
image
image

**Comment by patrikgrenfeldt** [comment]
FYI @emmser I have deployed a new version of cg in production

**Pull request merged**
