### PR TITLE
Fix session in upload auto

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
*This PR adds/fixes ...*

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@Mropat I made Housekeeper into a Sinlgeton 😄 Some tests are still unhappy because of this.. Feel free to use if you want

**Comment by Mropat** [comment]
@patrikgrenfeldt only 10 - not too scary. Probably would need to update. But does it fix the upload? Isnt it still possible to init more than one instance of this?

**Comment by patrikgrenfeldt** [comment]
Test result:
image
🆗 multiple uploads to scout on the same invocation of cg upload auto

**Comment by patrikgrenfeldt** [comment]
> @patrikgrenfeldt only 10 - not too scary. Probably would need to update. But does it fix the upload? Isnt it still possible to init more than one instance of this?

I don't think it is thread safe if that is your question no. But this seems to be multiple instances within the same process (both instances being instantiated by process ID 121325 in the example i slacked you).

**Comment by Mropat** [comment]
Ah! This looks fantastic! 🎉
We should use this for all classes which query databases directly!

**Review by Mropat — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
Is this still a problem or should we perhaps close this PR?

**Comment by henrikstranneheim** [comment]
To my knowledge it is not. I think it can be closed

**Comment by patrikgrenfeldt** [comment]
closing since the problem seems to have been solved by other means

**Pull request closed without merging**
