### PR TITLE
Fix problematic spring paths

### PR DESCRIPTION
**Pull request by moonso**
This PR adds a cli command `cg compress clean fix-spring`that fixes a problem where spring archives ended up in the wrong places.

For some cases the fastq paths in housekeeper are symbolic links to fastq files. When these files where compressed the spring archive ended up in the same place as the original fastq files. This PR adds a command that fixes this issue by moving the spring archive (and it's metadata file) to the place that housekeeper is pointing to.

### How to prepare for test
There is no real way to test the functionality on stage unfortunately (as is the case with most things that deals with fastq files) We can make a small and stupid test case that more or less runs the code.

- [x] ssh to hasta 
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh fix-problematic-spring-paths`

### How to test
- [x] Run the command with a individual `cg compress clean fix-spring --bundle-name ADM1059A4`
- [x] The program should not have found any spring files so nothing much to test

### How to prepare for test
We can make a test in production, unfortunately we will have to deploy first
- [ ] ssh to hasta 
- [ ] deploy on prod
### How to test
- [ ] Run the command in dry run mode with a individual id `cg compress clean fix-spring --bundle-name SVE2645A5 --dry-run`
- [ ] The program should have found some spring files and symlinked fastqs and will tell what files would be moved to where

**Expected test outcome**:
- [ ] check that the files would be moved to expected location
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [ ] tests executed by
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moonso** [comment]
Could you have a quick look at this @barrystokman ?

**Comment by moonso** [comment]
If you have time and interest, please have a look @henningonsbring

**Comment by barrystokman** [comment]
Bumped:
image

Deployed:
image

Tested in prod:
image

@moonso Can you have a look at this stack trace?

**Comment by moonso** [comment]
Sure I'll fix that, thanks for testing

**Pull request merged**
