### PR TITLE
Update constants.py

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR adds updates lims konstants with steps from the new twist v3 workflow.

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by
- [ ] tests executed by
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by moonso — APPROVED** [review]
Hi, could you put this in a new file in `cg/constants/lims.py`? It would be nice to collect all constants in the same place

**Comment by moonso** [comment]
I'm approving anyway but would be nice if you can move them

**Comment by mayabrandi** [comment]
Sure, but we will soon decouple lims from cg and all lims code will disappear. So maybe just let it be? You decide.

/M

**Comment by moonso** [comment]
I think you should move it!

**Comment by mayabrandi** [comment]
😛

Skickat från min iPhone

**Review by Mropat — APPROVED** [review]
:+1:

**Comment by Mropat** [comment]
Deployed on stage
image

Deployed on prod
image

**Pull request merged**
