### PR TITLE
upgrade memory demux

### PR DESCRIPTION
**Pull request by moonso**
## Description

- Upgrade memory allocation for demux

### Expected outcome
- [ ] Demuxing should not fail on lack of memory 

## Review
- [ ] code approved by
- [x] "Merge and deploy" approved by MM
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by karlnyr — APPROVED** [review]
👍

**Review by barrystokman — APPROVED** [review]
What's the reason for setting it to 95?

**Comment by moonso** [comment]
Kalles suggestion based on previous batch settings

**Comment by moonso** [comment]
Screen Shot 2021-05-24 at 10 17 28

deployed on hasta

**Comment by karlnyr** [comment]
@barrystokman I was going of the memory size per node.

**Comment by moonso** [comment]
Let's change again if needed. And now I think both of you could also change :)

**Pull request merged**
