### PR TITLE
cg transfer pools: skip samples with no pool name

### PR DESCRIPTION
**Pull request by barrystokman**
## Description

The cronjob `transfer-pools-received` started failing due to samples in pools missing the udf `pool name`. This PR skips and logs the offending samples so the cron job can continue.

### Fixed

- Fixes https://github.com/Clinical-Genomics/cg/issues/1295

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] do `cg transfer pools --status received`

### Expected test outcome
- [x] check that the sample swithout the `pool name` udf are skipped in the process, and logged
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @patrikgrenfeldt 
- [x] tests executed by @barrystokman 
- [x] "Merge and deploy" approved by @patrikgrenfeldt
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch

### CODE REVIEW

**Comment by barrystokman** [comment]
Output snippet:
image

Full log here:
[transfer-pools-received.log](https://github.com/Clinical-Genomics/cg/files/7303704/transfer-pools-received.log)

**Comment by barrystokman** [comment]
thanks to @patrikgrenfeldt  for some outstanding detective work

**Review by patrikgrenfeldt — APPROVED** [review]
nice! 👍

**Comment by barrystokman** [comment]
@patrikgrenfeldt do you think this is ready to be deployed?

**Review by patrikgrenfeldt — APPROVED** [review]
Clean! 🥇

**Comment by barrystokman** [comment]
image

**Pull request merged**
