### PR TITLE
reset upload_started_at date after upload is complete

### PR DESCRIPTION
**Pull request by barrystokman**
This PR adds/fixes https://github.com/Clinical-Genomics/cg/issues/691

**How to prepare for test**:
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh reset_upload_started_date`
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh reset_upload_started_date`

**How to test**:
- [ ] login to hasta
- [ ] do `cg upload -f worthyraptor`

**Expected test outcome**:
- [ ] check that the upload succeeds and no exception is raised
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by barrystokman** [comment]
`cg upload -f worthyraptor` fails because `upload_started_at` is not empty when starting the upload:
image
image

Remove `upload_started_at` and restart `cg upload -f worthyraptor`:

**Comment by barrystokman** [comment]
I'm a bit confused about where and why the `upload_started_at` date is set, but according to https://github.com/Clinical-Genomics/cg/issues/279 and https://github.com/Clinical-Genomics/cg/pull/281 it's for a good reason.

Maybe we should NOT reset this date and see how we can prevent the errors. @patrikgrenfeldt any thoughts on this?

**Comment by patrikgrenfeldt** [comment]
What's the need to have it reset? Do we want to upload the SAME analysis
again?

There's already the option to force a restart of the upload if needed.

Den ons 5 aug. 2020 14:17Barry Stokman <notifications@github.com> skrev:

**Comment by henrikstranneheim** [comment]
I do not think we are seeing this type of errors that were in the linked issue anymore. Closing this - please reopen if you disagree

**Pull request closed without merging**
