### PR TITLE
Use sample id instead of case id for rnafusion

### PR DESCRIPTION
**Pull request by fevac**
## Description

This is a change to start using sample ID instead of case ID in rnafusion. It involves:
- Updating the sample sheet so it uses sample ID 
- Updating the multiqc parsing so it uses sample ID as search pattern
- Updating the files deliverables so it uses sample ID instead
- It needs to be sync to changes in Hermes to change the deliverable files path: https://github.com/Clinical-Genomics/hermes/pull/104

### Changed

- Use sample id instead of case id for rnafusion

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b rnafusion_multiqc_sample_id -a
    ```

### How to test

- [x] `cg workflow rnafusion start CASE`. Make sure samplesheet contains sample id instead of case ID
- [x] `cg workflow rnafusion store CASE` (with hermes branch). Make sure case can be properly store
- [x] `cg generate delivery-report --force CASE`
- [x] In statusdb stage, make customer cust000, analysis delivery type as analysis-fastq-scout and reads to 200000000. Then run `cg upload -c CASE -r`. Check that case is properly uploaded to scout and caesar (with proper replacement of names) 

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by rannick** [comment]
Should be ready, needs testing

**Comment by fevac** [comment]
Test are passing

**Review by ivadym — APPROVED** [review]
Looks great!

I also tested the delivery report generation for reporting delivered files, and both implementations are aligned 👍

**Comment by fevac** [comment]
- deployed

image

image

**Pull request merged**
