### PR TITLE
Fix(avatar): skip adjective in search to improve hits

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
### Fixed

- Avatars: skip adjective in search to improve hits

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] do submit a couple of orders

### Expected test outcome
- [x] check that the hits are better than before (i.e. more animals as pics)
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by
- [x] tests executed by
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to EM

### CODE REVIEW

**Review by barrystokman — APPROVED** [review]
🦀

**Review by Mropat — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
Deployed to clinical-db:
```
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from ruamel.yaml->housekeeper>=2.5->cg==22.19.5) (0.2.0)
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-22.19.5-py3-none-any.whl size=493869 sha256=0c82675cce57c2294df469470c9a61af965ab684375f4d191e625928c4dc0e7c
  Stored in directory: /tmp/pip-ephem-wheel-cache-sk80m1fv/wheels/43/19/20/6afb75637008fd14885a94b0a0a63f48708cc075611f3704df
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 22.18.0
    Uninstalling cg-22.18.0:
      Successfully uninstalled cg-22.1
´´´

**Comment by patrikgrenfeldt** [comment]
@elevu this fix that should improve the avatars has been deployed in case we want to include them in cigrid as well

**Comment by elevu** [comment]
awesome, I will add them soon!

**Pull request merged**
