### PR TITLE
feat(update): Starlette and Fastapi

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by Vince-janv — COMMENTED** [review]
I don't think we use these anymore. The dependency seems to to come from sendmail-container which is no longer used in cg. I think we can remove these

**Comment by henrikstranneheim** [comment]
> I don't think we use these anymore. The dependency seems to to come from sendmail-container which is no longer used in cg. I think we can remove these

How surprising! Great catch - will give it a spin!

```
cg-py3.11) henrikstranneheim in ~/git/cg on branch update-starlette > poetry remove sendmail-container
Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 0 installs, 0 updates, 8 removals

  - Removing anyio (3.7.1)
  - Removing fastapi (0.115.2)
  - Removing h11 (0.14.0)
  - Removing python-multipart (0.0.9)
  - Removing sendmail-container (0.2.0)
  - Removing sniffio (1.3.0)
  - Removing starlette (0.40.0)
  - Removing uvicorn (0.23.2)

Writing lock file

**Comment by henrikstranneheim** [comment]
### API, 👍 

Screenshot 2024-10-23 at 09 53 04

**Comment by henrikstranneheim** [comment]
@Vince-janv Ready for review!

**Review by Vince-janv — APPROVED** [review]
Nice to clean these out! 🧹

**Comment by henrikstranneheim** [comment]
Deployed to Hasta and CGVS
```
Log deploy... done.
cg, version 64.4.3
```

**Pull request merged**
