### PR TITLE
add: upload BALSAMIC CNV report to Scout

### PR DESCRIPTION
**Pull request by ivadym**
## Description

Implemented upload to Scout of the AscatNgs pdf report.

Context: https://github.com/Clinical-Genomics/BALSAMIC/issues/827.

### Added

- Upload BALSAMIC CNV report to Scout

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] `cg upload create-scout-load-config <TN_WGS_case_ID>`

Logs:

Screen Shot 2022-02-01 at 13 20 13

` scout_load.yaml` file:

Screen Shot 2022-02-01 at 13 16 10

- [x] `cg upload upload-case-to-scout <TN_WGS_case_ID> --dry-run`

Screen Shot 2022-02-01 at 14 30 27

## Review
- [x] code approved by PG
- [x] tests executed by VI
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by patrikgrenfeldt — APPROVED** [review]
Looks very consistent with the code in general, nicely type hinted as well! 👍

**Comment by ivadym** [comment]
Thanks for reviewing the code Patrik!

Uploaded successfully to scout-stage:

Screen Shot 2022-02-08 at 09 57 04

**Comment by patrikgrenfeldt** [comment]
> Should I merge and deploy it @patrikgrenfeldt?

If the Scout application is ready and the customers and Scout team are ready then yes 👍

**Comment by northwestwitch** [comment]
> If the Scout application is ready and the customers and Scout team are ready then yes

Yess! 👍🏻

**Comment by ivadym** [comment]
Deployed on hasta:

Screen Shot 2022-02-09 at 14 16 51


Screen Shot 2022-02-09 at 14 18 27

**Pull request merged**
