### PR TITLE
Fix app tags in order form fixtures

### PR DESCRIPTION
**Pull request by islean**
## Description

The order forms used for texting have a number of archived app tags specified, which should not be allowed to order anymore. This PR updates the app tags to have allowed values.

### Fixed

- Fixtures use valid app tags

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by ChrOertlin** [comment]
image
Impossible to review.

Are these files versioned somewhere in our google drive?

**Comment by islean** [comment]
> image Impossible to review.
> 
> Are these files versioned somewhere in our google drive?

Well, they are not precisely code, they are excel sheets. I would guess easiest is to open them in numbers/excel. Might be difficult to see the difference though. How are these reviews usually performed @Vince-janv ?

**Review by Vince-janv — APPROVED** [review]
I don't feel like looking into every excel 😅 I trust you and the pytests!

**Comment by islean** [comment]
Tested all forms manually and they pass validation

**Pull request merged**
