### PR TITLE
Refactor pipeline to workflow

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

First PR renaming pipeline to workflow.

### Added

-

### Changed

- Refactor Pipeline to workflow for enum
- Remove casting to str

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b refactor-pipeline-to-workflow -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Fram what I can see renaming of Pipeline enum to Workflow. Looks good!

**Comment by henrikstranneheim** [comment]
### cg get case justhusky 👍 
```
[henrik.stranneheim@hasta:~] [S_base] 2m54s $ cg get case justhusky
+-----------+--------------------------------+------------+------------+-----------+----------+
| Case      | Name                           | Customer   | Priority   | Panels    | Action   |
|-----------+--------------------------------+------------+------------+-----------+----------|
| justhusky | SWEDAC-2019-HG-05-Trio-NovaSeq | cust000    | priority   | OMIM-AUTO | running  |
+-----------+--------------------------------+------------+------------+-----------+----------+
+-------------------+----------+----------+
| Sample            | Mother   | Father   |
|-------------------+----------+----------|
| earlycasualcaiman |          |          |
+-------------------+----------+----------+
+-----------------+----------+----------+
| Sample          | Mother   | Father   |
|-----------------+----------+----------|
| slowlycivilbuck |          |          |
+-----------------+----------+----------+
+----------------+-----------------+-------------------+
| Sample         | Mother          | Father            |
|----------------+-----------------+-------------------|
| hugelymodelbat | slowlycivilbuck | earlycasualcaiman |
+----------------+-----------------+-------------------+
+-------------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample            | Name            | Customer   | Application   | State              | Priority   | External?   |
|-------------------+-----------------+------------+---------------+--------------------+------------+-------------|
| earlycasualcaiman | ACC5339A2--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+-------------------+-----------------+------------+---------------+--------------------+------------+-------------+
+-----------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample          | Name            | Customer   | Application   | State              | Priority   | External?   |
|-----------------+-----------------+------------+---------------+--------------------+------------+-------------|
| slowlycivilbuck | ACC5339A3--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+-----------------+-----------------+------------+---------------+--------------------+------------+-------------+
+----------------+-----------------+------------+---------------+--------------------+------------+-------------+
| Sample         | Name            | Customer   | Application   | State              | Priority   | External?   |
|----------------+-----------------+------------+---------------+--------------------+------------+-------------|
| hugelymodelbat | ACC5339A4--300M | cust000    | WGXCUSC000    | Ordered 2019-05-08 | priority   | Yes         |
+----------------+-----------------+------------+---------------+--------------------+------------+-------------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2023-12-07 10:32:30 | mip-dna    | 12.0.3    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2023-05-04 10:11:56 | mip-dna    | 11.2.0    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2023-03-29 14:55:02 | mip-dna    | 11.1.2    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2022-11-24 11:32:28 | mip-dna    | 11.0.3    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2021-08-18 14:19:23 | mip-dna    | 10.2.0    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2021-06-09 15:15:11 | mip-dna    | 10.0.1    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2020-02-20 14:47:52 | mip-dna    | v8.2.1    |
+---------------------+------------+-----------+
+---------------------+------------+-----------+
| Analysis Date       | Workflow   | Version   |
|---------------------+------------+-----------|
| 2019-06-11 10:48:07 | mip-dna    | v6.0.20   |
+---------------------+------------+-----------+
[
```

**Comment by henrikstranneheim** [comment]
### cg workflow mip-dna start justhusky -d 👍 
```
[henrik.stranneheim@hasta:~] [S_base] 1m19s $ cg workflow mip-dna start justhusky -d
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Case justhusky exists in Status DB
Starting full MIP analysis workflow for case justhusky
Flow cell check is not applicable - the case is either down sampled or external.
Found file earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz
Found file earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz
Found file slowlycivilbuck/2019-05-08/HHT5NDSXX_HapMap_S27_L001_R1_001.fastq.gz
Found file slowlycivilbuck/2019-05-08/HHT5NDSXX_HapMap_S27_L001_R2_001.fastq.gz
Found file hugelymodelbat/2019-05-08/HHT5NDSXX_HapMap_S28_L001_R1_001.fastq.gz
Found file hugelymodelbat/2019-05-08/HHT5NDSXX_HapMap_S28_L001_R2_001.fastq.gz
Case justhusky exists in Status DB
Case justhusky exists in Status DB
Running command /home/proj/stage/bin/miniconda3/envs/S_scout/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml export panel --bed BRAIN Cardiology CILM CH CTD DIAB ENDO EP HEARING HYDRO IBMFS IEM IF mcarta MHT MIT MOVE mtDNA NBS-M NEURODEG NMD OMIM-AUTO OPTIC PANELAPP-GREEN PEDHEP PID PIDCAD RETINA SKD SOVM STROKE AID Inherited cancer --build 37
MT	15956	16023	7494	MT-TP
Case justhusky exists in Status DB
Running command /home/proj/stage/bin/miniconda3/envs/S_scout/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml export managed --build 37
##fileformat=VCFv4.2
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##fileDate=2024-02-01 08:26:24.557630
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=TYPE,Number=1,Type=String,Description="Type of variant">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	48696925	.	G	C	.		END=48696925;TYPE=SNV
7	124491972	.	C	A	.		END=124491972;TYPE=SNV
12	103234252	.	T	C	.		END=103234252;TYPE=SNV
14	76548781	.	CTGGACC	G	.		END=76548781;TYPE=INDEL
17	48696925	.	G	T	.		END=48696925;TYPE=SNV
Case justhusky exists in Status DB
{'case': 'justhusky', 'default_gene_panels': ['OMIM-AUTO'], 'samples': [{'sample_id': 'earlycasualcaiman', 'sample_display_name': 'ACC5339A2--300M', 'analysis_type': 'wgs', 'sex': 'male', 'phenotype': 'unaffected', 'expected_coverage': 1, 'capture_kit': 'twistexomerefseq_9.1_hg19_design.bed', 'mother': '0', 'father': '0'}, {'sample_id': 'slowlycivilbuck', 'sample_display_name': 'ACC5339A3--300M', 'analysis_type': 'wgs', 'sex': 'female', 'phenotype': 'unaffected', 'expected_coverage': 1, 'capture_kit': 'twistexomerefseq_9.1_hg19_design.bed', 'mother': '0', 'father': '0'}, {'sample_id': 'hugelymodelbat', 'sample_display_name': 'ACC5339A4--300M', 'analysis_type': 'wgs', 'sex': 'male', 'phenotype': 'affected', 'expected_coverage': 1, 'capture_kit': 'twistexomerefseq_9.1_hg19_design.bed', 'mother': 'slowlycivilbuck', 'father': 'earlycasualcaiman'}]}
Case justhusky exists in Status DB
earlycasualcaiman: downsampled/external - skip evaluation
Running command /home/proj/stage/bin/miniconda3/bin/conda run --name S_mip12.0 /home/proj/stage/bin/miniconda3/envs/S_mip12.0/bin/mip analyse rd_dna --config /home/proj/stage/servers/config/hasta.scilifelab.se/mip12.0-dna-stage.yaml justhusky --slurm_quality_of_service high --email henrik.stranneheim@scilifelab.se --qccollect_skip_evaluation
Dry run: process call will not be executed!!


Running in dry-run mode.
```

**Comment by henrikstranneheim** [comment]
Deployed to production:
```
Log deploy... done.
cg, version 56.2.7
```

**Pull request merged**
