### PR TITLE
Rm pdc spring archive

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Remove PDC spring archive and retrieval

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
So many red lines. :) The additions look also good!

**Review by Vince-janv — APPROVED** [review]
Nice work! What is the reasoning for keeping the decryption part?

**Comment by henrikstranneheim** [comment]
I think we are using it getting flow cells back from PDC.

**Comment by karlnyr** [comment]
Will there be a matching atlas PR describing the changes for backups?

**Comment by henrikstranneheim** [comment]
Yes, I think we need to discuss this.

I also realized that we might need this code fora while longer as the hospital only want K data, and the novaseqX change will make us not archive flow cells. So archiving research data as spring files for a while might not be such a bad idea.

**Pull request closed without merging**
