### PR TITLE
feat(action): Use cache

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Use cache in actions

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [x] Actions run using cached deps

### Expected test outcome

- [x] Take a screenshot and attach or copy/paste the output.

## Review

- [x] "Merge and deploy" approved by @ChrOertlin 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Adding a pip cache to avoid re-downloading packages when running an action! Looks good!

**Comment by seallard** [comment]
Something like

```yml
name: CG Installation tests

on: ["pull_request"]

jobs:
  installations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      # Check out cg code
      - name: Check out git repository
        uses: actions/checkout@v3

      # Set up python
      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}

      # Cache the installed dependencies
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Intall pip
        # Make sure that we have correct python version and pip version
        # For details see .github/workflows/server_info.md
        run: |
          python -m pip install --upgrade pip
          echo $PYTHON_VERSION
          pip --version
        env:
          PYTHON_VERSION: ${{ matrix.python-version}}

```

**Comment by henrikstranneheim** [comment]
Screenshot 2023-04-04 at 14 25 53

I think this action saves the dependencies in the requirements file
Screenshot 2023-04-04 at 14 28 40

**Comment by henrikstranneheim** [comment]
Nothing to deploy

**Pull request merged**
