### PR TITLE
fix: permissions are not preserved on folders rsynced to Caesar

### PR DESCRIPTION
**Pull request by mathiasbio**
## Description

Discovered that permissions on folders created by Rsync on Caesar had the wrong permissions. drwxr-s--- instead of drwxrws--- which meant customers could no longer delete their own data. Unclear why this became an issue now. Created a test directory and Rsynced manually with and without the -p flag, and the -p flag worked as intended. 

### Added

- added -p flag to rsync command in cg to preserve permissions in Caesar

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b fix_caesar_customer_project_permission_post_rsync -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by thelander — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@mathiasbio Nice fix! Usually you test the change on stage and post the results here before merging. That way we can keep production more clean of bugs and unwanted errors. And it makes it less nervous to deploy to production, 😄 .

**Comment by mathiasbio** [comment]
Yes of course, sorry! I made some tests but not wholly within the cg context. Will follow the correct procedure next time. As a sanity check here are the results from the test on production.

Ran:
image

On Caesar before and after:
image

Permissions are preserved on the rsynced directory as intended

**Comment by henrikstranneheim** [comment]
@mathiasbio Well done!

**Pull request merged**
