### PR TITLE
Allow tomte workflow in Order

### PR DESCRIPTION
**Pull request by islean**
## Description

Currently any order submitted with workflow Tomte would fail to add an entry in the Order table, as the allowed enums do not include Tomte. This PR adds support for Tomte orders.

### Changed

- Tomte included in the workflow enum in the order table

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b allow-tomte-orders -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
👍

**Review by ChrOertlin — APPROVED** [review]
💯

**Comment by islean** [comment]
Upon deployment, tomte is part of the allowed workflows:

**Comment by islean** [comment]
Downgrade worked:

image

**Comment by islean** [comment]
Deployed to production:

```
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 59.20.5
θ64° [isak.ohlsson@hasta:~] [P_base] 7m34s $ 

```

**Pull request merged**
