### PR TITLE
Feat: Wipe trimmed fastqs derived from Balsamic in sample bundles after 45 days

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
### Added
- wipe trimmed fastqs derived from Balsamic in sample bundles (default after 45 days)

### How to test 
- [x] ensure master branch
- [x] us 
- [x] run `cg clean scout_finished_cases`
- [x] install branch 'remove-trimmed-fastqs'
- [x] run `cg clean scout_finished_cases`

### Expected test outcome
- [x] check that the outputs mentions the same bundles etc.
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by PG
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch
- [ ] Inform to production

### CODE REVIEW

**Comment by Mropat** [comment]
There is already a cli command to clean specific files by providing tags in clean base. 
This can be done by running `cg clean hk-bundle-files -p balsamic -t fastq -o 45`
All that remains is to make systemd timers with specific arguments for each tag that we want cleaning, without adding more cg code that includes those flags as default

**Comment by patrikgrenfeldt** [comment]
> There is already a cli command to clean specific files by providing tags in clean base. This can be done by running `cg clean hk-bundle-files -p balsamic -t fastq -o 45` All that remains is to make systemd timers with specific arguments for each tag that we want cleaning, without adding more cg code that includes those flags as default

It's missing the "newer than" argument which in turn would cause the the processed list to be ever increasing, maybe I'll add that as well

**Comment by patrikgrenfeldt** [comment]
Test result: 
master:
```
2022-02-01 14:15:40 hasta.scilifelab.se cg.cli.clean[194145] INFO 423 cases marked for bam removal
...
2022-02-01 14:16:00 hasta.scilifelab.se cg.cli.clean[194145] INFO 337 cases marked for bam removal
...
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [bam]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag bam
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [bai]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag bai
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [bam-index]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag bam-index
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [cram]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag cram
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [crai]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag crai
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files from bundle yellowcub
2022-02-01 14:16:01 hasta.scilifelab.se housekeeper.store.api.find[194145] INFO Fetching files with tags in [cram-index]
2022-02-01 14:16:01 hasta.scilifelab.se cg.cli.clean[194145] WARNING Could not find any files ready for cleaning for bundle yellowcub and tag cram-index
```
branch:
```
2022-02-01 14:28:10 hasta.scilifelab.se cg.cli.clean.base[208828] INFO 423 cases marked for bam removal
...
2022-02-01 14:28:31 hasta.scilifelab.se cg.cli.clean.base[208828] INFO 337 cases marked for bam removal
...
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Cleaning analysis yellowcub | 2017-02-15
2022-02-01 14:28:32 hasta.scilifelab.se cg.apps.housekeeper.hk[208828] INFO Fetch version 2017-02-15 10:02:23 from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Version found for bundle:yellowcub; pipeline: mip-dna; date 2017-02-15 10:02:23
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files with tags in [bam,bai,bam-index,cram,crai,cram-index]
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from version 400
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py:2577: SAWarning: Pathed join target File.version has already been joined to; skipping
  "been joined to; skipping" % prop
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Cleaning analysis yellowcub | 2017-11-10
2022-02-01 14:28:32 hasta.scilifelab.se cg.apps.housekeeper.hk[208828] INFO Fetch version 2017-11-10 10:48:16 from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Version found for bundle:yellowcub; pipeline: mip-dna; date 2017-11-10 10:48:16
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files with tags in [bam,bai,bam-index,cram,crai,cram-index]
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from version 2060
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Cleaning analysis yellowcub | 2019-09-11
2022-02-01 14:28:32 hasta.scilifelab.se cg.apps.housekeeper.hk[208828] INFO Fetch version 2019-09-11 16:50:27 from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Version found for bundle:yellowcub; pipeline: mip-dna; date 2019-09-11 16:50:27
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files with tags in [bam,bai,bam-index,cram,crai,cram-index]
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from version 12043
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Cleaning analysis yellowcub | 2019-09-19
2022-02-01 14:28:32 hasta.scilifelab.se cg.apps.housekeeper.hk[208828] INFO Fetch version 2019-09-19 14:02:37 from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Version found for bundle:yellowcub; pipeline: mip-dna; date 2019-09-19 14:02:37
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from bundle yellowcub
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files with tags in [bam,bai,bam-index,cram,crai,cram-index]
2022-02-01 14:28:32 hasta.scilifelab.se housekeeper.store.api.find[208828] INFO Fetching files from version 12521
2022-02-01 14:28:32 hasta.scilifelab.se cg.cli.clean.base[208828] INFO Process freed 0.0GB. Dry run: True
```
🆗  Seems like the new way of cleaning also cleans up alignment files for older bundles

**Comment by patrikgrenfeldt** [comment]
@henrikstranneheim It seems like this PR would change the cleaning of "scout alignment files" to also clean for older bundles than the latest, is that ok?

**Comment by henrikstranneheim** [comment]
We need to protect the the last analysis alignment files (either BAM or CRAM) for 300 days, but older version bundles can be removed. Also see: https://atlas.scilifelab.se/infrastructure/dataflow/data_management_plan/#data-management

**Comment by patrikgrenfeldt** [comment]
> We need to protect the the last analysis alignment files (either BAM or CRAM) for 300 days, but older version bundles can be removed. Also see: https://atlas.scilifelab.se/infrastructure/dataflow/data_management_plan/#data-management

That is regulated by the cron-cg-clean.sh cronjob: 
```
# clean BAM files from finished cases
echo "cg clean scout-finished-cases -y --days-old 300"
cg clean scout-finished-cases -y --days-old 300
```
I.e. it is unchanged

**Comment by patrikgrenfeldt** [comment]
Closing since changing this logic might cause new bugs

**Pull request closed without merging**
