### PR TITLE
Fix alembic script

### PR DESCRIPTION
**Pull request by diitaz93**
## Description
Separated the Alembic migration implemented in #2462 into two migrations

### Added

- New alembic script with one migration

### Changed

-

### Fixed

- Removed part of the migration of the old Alembic script

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b update-alembic-statusdb -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by diitaz93** [comment]
## Tested on stage:
```shell
[js.diazboada@hasta:/home/proj/stage/bin/git/cg] [S_base] update-alembic-statusdb+ 5s 130 ± alembic -c /home/proj/production/servers/alembic/cg/alembic-stage.ini upgrade head
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5cb3ce4c3e39 -> 936887038ba8, Sync parts of cg and statusdb
INFO  [alembic.runtime.migration] Running upgrade 936887038ba8 -> d0aa961845b9, Sync the remaining parts of cg and statusdb
[js.diazboada@hasta:/home/proj/stage/bin/git/cg] [S_base] update-alembic-statusdb+ 33s ± 
```

**Review by Vince-janv — APPROVED** [review]
Looks good 👍

**Comment by Vince-janv** [comment]
### Added the dummy invoice to production as well

**Comment by diitaz93** [comment]
## Updated the alembic version on prod manually

**Comment by diitaz93** [comment]
## Deployed to stage:
```shell
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 49.4.2
[js.diazboada@hasta:~] [S_base] 5m48s $
```
## Deployed to production:
```shell
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 49.4.2
[js.diazboada@hasta:~] [P_base] 4m12s
```

**Pull request merged**
