### PR TITLE
Update constants.py

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR adds: 

- new step names to the lims/constants.py for the search of recieved dates and prepared dates.

- A new function for for getting step dates based on input artifact. The new function is being used in the get received date function.

**How to test:**
Set test preconditions:
1. Log into Hasta
2. install branch on stage: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage lims-constants`
3. activate stage: `usestage`

### `CG TRANSFER LIMS`

**Get received dates for samples from LIMS:**
Execute Test:
1. prepare test data: 
`bash servers/resources/clinical-db.scilifelab.se/dbcopy-prod-to-stage.sh cg`. check the microbial sample ACC6494A9. It should be missing recieved date.
2. run `cg transfer microbials --status received` and check the sample again. It should now have a received date!

**Get prepared dates for samples from LIMS:**
Execute Test:
1. prepare test data: 
`bash servers/resources/clinical-db.scilifelab.se/dbcopy-prod-to-stage.sh cg`.  check the sample ACC6443A1. It should be missing prepared date.
2. run `cg transfer lims --status prepared` and check the sample again. It should now have a prepared date!

- [x] code reviewed @patrikgrenfeldt 
- [x] tested on stage @mayabrandi 18 feb 2020
- [x] deploy approved @ingkebil

### CODE REVIEW

**Comment by mayabrandi** [comment]
Tested for sample prepared date with sample: ACC5963A1


Skärmavbild 2020-02-17 kl  15 17 39

Skärmavbild 2020-02-17 kl  15 17 10

Skärmavbild 2020-02-17 kl  15 17 03

**Comment by mayabrandi** [comment]
Testing prepared date with sample ACC6427A3:

Date NOT updated



Skärmavbild 2020-02-17 kl  15 37 59

Skärmavbild 2020-02-17 kl  15 38 24

**Comment by mayabrandi** [comment]
Testing Received date with sample ACC6494A9
It was run through the microbial reception control step Jan 15.

Skärmavbild 2020-02-18 kl  13 34 58

 This step is of type **Reception Control no placement v1**

Skärmavbild 2020-02-18 kl  13 41 51

The sample was missing received date after copying production database to stage database

Skärmavbild 2020-02-18 kl  13 29 41

Running `cg transfer microbials --status received` 

Skärmavbild 2020-02-18 kl  13 45 00

Uppdated the sample in the database

Skärmavbild 2020-02-18 kl  13 54 04

Skärmavbild 2020-02-18 kl  13 55 42



Conclusion:

The new step type **Reception Control no placement v1** is being picked up from the config.
The new function wich is based on geting step date based on input artifact is working. The date would not have been picked using [this](https://github.com/Clinical-Genomics/cg/blob/3b8eed2b89ac53dcaad3ef73448ae3ce28b4c381/cg/apps/lims/api.py#L348) function since it is searching the step by looking for output artifacts.

**Comment by mayabrandi** [comment]
Testing Prepared date with sample ACC6427A3

The sample has gone through the step **Aggregate QC (Library Validation) (RNA)**

Skärmavbild 2020-02-18 kl  14 01 34

This step is of type **Aggregate QC (Library Validation) (RNA) v2**

Skärmavbild 2020-02-18 kl  14 06 45


The sample was missing prepared date after copying production database to stage database

Skärmavbild 2020-02-18 kl  14 01 24

Running `cg transfer lims --status prepared`

Skärmavbild 2020-02-18 kl  14 03 25

Uppdated the database

Skärmavbild 2020-02-18 kl  14 17 13

Skärmavbild 2020-02-18 kl  14 17 38


Conclusion:
The new step type **Aggregate QC (Library Validation) (RNA) v2** is being picked up from the config.

**Comment by barrystokman** [comment]
Preconditions: make cg installation on stage point to production LIMS
image

Preconditions: microbial sample ACC6542A1 has no received date :heavy_check_mark: 
image

`cg transfer lims --status received` ran with exit code 0:
image

No received date filled :negative_squared_cross_mark: 
image

Preconditions: sample ACC6443A1 has no prepared date :heavy_check_mark: 
image

`cg transfer lims --status prepared` ran with exit code 0:
image

No prepared date filled :negative_squared_cross_mark: 
image

@mayabrandi Can you have a look? Neither the received or the prepared dates seem to be picked up.

**Comment by mayabrandi** [comment]
You want to deploy this @patrikgrenfeldt?

**Comment by patrikgrenfeldt** [comment]
Great that we get this fix @mayabrandi!

**Comment by patrikgrenfeldt** [comment]
deployed on hasta and clinical-db

**Pull request merged**
