### PR TITLE
Fix customer search and show microbial samples

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes the broken microbial sample search in the OP.

Contact: @patrikgrenfeldt 

### How to test microobial sample search:
0. install clinical-api on stage on clinical-db
1. login into OP as a NON-ADMIN-USER(!) (i.e. a user with one customer only)
1. https://clinical-stage.scilifelab.se/microbialsamples
1. search for anything

**Expected outcome:**
Search result is presented

### How to test microobial sample show:
0. install clinical-api on stage on clinical-db
1. login into OP as a NON-ADMIN-USER(!) (i.e. a user with one customer only)
1. https://clinical-stage.scilifelab.se/microbialsamples
1. click on a sample

**Expected outcome:**
Sample is presented

- [x] Code review by @ingkebil 
- [x] Tested by @emiliaol 
- [x] Deploy approved by @ingkebil 

This is a patch since it fixes a bug and does not provide any new functionality

### CODE REVIEW

**Comment by emiliaol** [comment]
Tested on clinical db:
Skärmavbild 2019-06-11 kl  17 43 09

Logged in as non-admin user of cust015 and could not display any microbial samples or search for them:
Skärmavbild 2019-06-11 kl  17 42 34

**Comment by ingkebil** [comment]
Ready for merge and deploy.

**Comment by b4ckm4n** [comment]
@ingkebil Hej! Isn't this ready to merge and deploy?

**Comment by ingkebil** [comment]
Yes, weird. I think Patrik might have forgotten to push it to production. I can do it now.

**Comment by ingkebil** [comment]
:ship:

**Pull request merged**
