### PR TITLE
Feat(RNA): Upload RNA files to Scout

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
Resolves: https://github.com/Clinical-Genomics/cg/issues/1289 - Update a DNA case with RNA files in Scout via cg

### Added
- CLI-command: upload rna-fusion-report-to-scout
- CLI-command: upload splice-junctions-scout
- CLI-command: upload rna-to-scout - both of the obove

### How to prepare for test
- [x] ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [x] make sure there is a rna case that has a sample connected to dna case via subject_id
---

### How to test rna-fusion-report-to-scout
- [x] run upload rna-fusion-report-to-scout RNA_CASE_ID

### Expected test outcome
- [x] check that the fusion report was uploaded to the connected dna samples case 
- [x] check report in scout 

---

### How to test rna-fusion-report-to-scout RESEARCH
- [x] run upload rna-fusion-report-to-scout RNA_CASE_ID --research

### Expected test outcome
- [x] check that the fusion report was uploaded to the connected dna samples case 
- [x] check report in scout 

---

### How to test splice-junctions-scout
- [x] run upload splice-junctions-scout RNA_CASE_ID

### Expected test outcome
- [x] check that the splice junction files was uploaded to the connected dna samples case 
- [x] check report in scout 

---

### How to test rna-to-scout
- [x] run upload rna-to-scout RNA_CASE_ID

### Expected test outcome
- [x] check that the fusion report and splice junction files was uploaded to the connected dna samples case 
- [x] check reports in scout 

---

### How to test rna-to-scout RESEARCH
- [x] run upload rna-to-scout RNA_CASE_ID --research

### Expected test outcome
- [x] check that the RESEARCH fusion report and splice junction files was uploaded to the connected dna samples case 
- [x] check reports in scout 

---

- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by
- [x] tests executed by
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- ~Document in changelog~
- [ ] Deploy this branch
- [ ] Check  "The RNA analysis can be used to automatically update the corresponding DNA case in Scout. Adding PDF fusion reports" in [Project](https://github.com/Clinical-Genomics/project-planning/issues/133)
- [ ] Check "The RNA analysis can be used to automatically update the corresponding DNA case in Scout. Adding files for viewing splice junction track in Scout (BigWig and bedfile)" in [Project](https://github.com/Clinical-Genomics/project-planning/issues/133) 
- [ ] Inform to HS, team prod

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result upload-fusion-report:
```
cg upload rna-fusion-report-to-scout angrygoblin
----------------- UPLOAD ----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Fetching files with tags in [fusion,clinical]
Fetching files from version 12345
Clinical fusion report angrygoblin/2021-11-05/angrygoblin_report.selected.pdf found
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf to case fastsloth
Running command /home/proj/bin/conda/envs/S_scout/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf
Call ['/home/proj/bin/conda/envs/S_scout/bin/scout', '--config', '/path_to_config/scout-stage.yaml', 'load', 'gene-fusion-report', 'fastsloth', '/path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf'] exit with a non zero exit code
2021-11-05 07:22:42 server scout.commands.base[148197] INFO Running scout version 4.40
2021-11-05 07:22:42 server scout.commands.base[148197] DEBUG Debug logging enabled.
2021-11-05 07:22:42 server scout.adapter.client[148197] INFO Connected to MongoDB 4.4.9
2021-11-05 07:22:42 server scout.adapter.mongo.base[148197] DEBUG Database name: scout-stage
2021-11-05 07:22:42 server scout.adapter.mongo.case[148197] INFO Fetching case fastsloth
2021-11-05 07:22:42 server scout.commands.load.report[148197] ERROR Existing report found, use update = True to overwrite
Aborted!
Something went wrong when uploading fusion report
```
🆗 Tried to upload correct rna report to scout for correct dna case

**Comment by patrikgrenfeldt** [comment]
Test result upload fusion report:
```
cg upload rna-fusion-report-to-scout angrygoblin
----------------- UPLOAD ----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Fetching files with tags in [fusion,clinical]
Fetching files from version 12345
Clinical fusion report angrygoblin/2021-11-05/angrygoblin_report.selected.pdf found
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf
Call ['/path_to_binary/bin/scout', '--config', '/path_to_config/scout-stage.yaml', 'load', 'gene-fusion-report', 'fastsloth', '/path_to/housekeeper-bundles/angrygoblin/2021-11-05/angrygoblin_report.selected.pdf'] exit with a non zero exit code
2021-11-05 07:22:42 server scout.commands.base[148197] INFO Running scout version 4.40
2021-11-05 07:22:42 server scout.commands.base[148197] DEBUG Debug logging enabled.
2021-11-05 07:22:42 server scout.adapter.client[148197] INFO Connected to MongoDB 4.4.9
2021-11-05 07:22:42 server scout.adapter.mongo.base[148197] DEBUG Database name: scout-stage
2021-11-05 07:22:42 server scout.adapter.mongo.case[148197] INFO Fetching case fastsloth
2021-11-05 07:22:42 server scout.commands.load.report[148197] ERROR Existing report found, use update = True to overwrite
Aborted!
Something went wrong when uploading fusion report
```
🆗 Tried to upload correct rna report to scout for correct dna case

Test result upload bigwig:
```
cg upload rna-junctions-to-scout angrygoblin
----------------- UPLOAD ----------------------
----------------- UPLOAD RNA JUNCTIONS TO SCOUT -----------------------
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,ACC1234B26,junction]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-1A in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,ACC1234B27,junction]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-2A in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,junction,ACC1234B28]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-2U in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,junction,ACC1234B29]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-1U in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Upload splice junctions bed file finished!
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B26,bigwig,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-1A in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B26_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B27,bigwig,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-2A in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B27_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B28,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-2U in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B28_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B29,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-1U in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-05/ACC1234B29_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Upload RNA coverage bigwig file finished!
```
🆗 uploaded bigwig for all samples of rna case to all individuals of dna case

**Comment by patrikgrenfeldt** [comment]
Test result upload-RNA:
```
cg upload rna-to-scout angrygoblin -u
----------------- UPLOAD ----------------------
----------------- UPLOAD RNA TO SCOUT -----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Fetch latest version from bundle angrygoblin
Fetching files with tags in [fusion,clinical]
Fetching files from version 12345
Clinical fusion report angrygoblin/2021-11-08/angrygoblin_report.selected.pdf found
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --update fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf
Uploaded Clinical fusion report
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --update fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf
Uploaded Clinical fusion report
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --update fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf
Uploaded Clinical fusion report
Uploading Clinical fusion report to scout for case fastsloth
Uploading fusion report /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --update fastsloth /path_to/housekeeper-bundles/angrygoblin/2021-11-08/angrygoblin_report.selected.pdf
Uploaded Clinical fusion report
Upload Clinical fusion report finished!
----------------- UPLOAD RNA JUNCTIONS TO SCOUT -----------------------
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,ACC1234B26,junction]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-1A in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,junction,ACC1234B27]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-2A in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B28,bed,junction]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-2U in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bed,ACC1234B29,junction]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-1U in scout
Uploading splice junctions bed file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U splice_junctions_bed /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Upload splice junctions bed file finished!
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B26,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-1A in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B26_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B27,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-2A in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B27_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B28,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-2U in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B28_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [bigwig,ACC1234B29,coverage]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-1U in scout
Uploading rna coverage bigwig file /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/bin/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U rna_coverage_bigwig /path_to/housekeeper-bundles/angrygoblin/2021-11-08/ACC1234B29_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Upload RNA coverage bigwig file finished!
```
🆗 uploaded both fusion report and junction files

Test result upload RNA RESEARCH:
```
cg upload rna-to-scout angrygoblin -u -r
----------------- UPLOAD ----------------------
----------------- UPLOAD RNA TO SCOUT -----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Fetch latest version from bundle angrygoblin
Fetching files with tags in [fusion,research]
Fetching files from version 12345
Research fusion report angrygoblin/2021-06-29/angrygoblin_report.pdf found
Uploading Research fusion report to scout for case fastsloth
Uploading fusion report /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --research --update fastsloth /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf
Uploaded Research fusion report
Uploading Research fusion report to scout for case fastsloth
Uploading fusion report /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --research --update fastsloth /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf
Uploaded Research fusion report
Uploading Research fusion report to scout for case fastsloth
Uploading fusion report /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --research --update fastsloth /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf
Uploaded Research fusion report
Uploading Research fusion report to scout for case fastsloth
Uploading fusion report /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml load gene-fusion-report --research --update fastsloth /path_to_housekeeper-bundles/angrygoblin/2021-06-29/angrygoblin_report.pdf
Uploaded Research fusion report
Upload Research fusion report finished!
----------------- UPLOAD RNA JUNCTIONS TO SCOUT -----------------------
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B26,junction,bed]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-1A in scout
Uploading splice junctions bed file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A splice_junctions_bed /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B27,junction,bed]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-I-2A in scout
Uploading splice junctions bed file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A splice_junctions_bed /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [junction,ACC1234B28,bed]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-2U in scout
Uploading splice junctions bed file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U splice_junctions_bed /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [junction,ACC1234B29,bed]
Fetching files from version 12345
Splice junctions bed file angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bed.gz found
Uploading splice junctions bed file for 54321-II-1U in scout
Uploading splice junctions bed file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bed.gz to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U splice_junctions_bed /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bed.gz
Uploaded splice junctions bed file
Upload splice junctions bed file finished!
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B26,coverage,bigwig]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-1A in scout
Uploading rna coverage bigwig file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-1A rna_coverage_bigwig /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B26_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [ACC1234B27,coverage,bigwig]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-I-2A in scout
Uploading rna coverage bigwig file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-I-2A rna_coverage_bigwig /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B27_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [coverage,ACC1234B28,bigwig]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-2U in scout
Uploading rna coverage bigwig file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-2U rna_coverage_bigwig /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B28_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Fetch latest version from bundle angrygoblin
Fetching files with tags in [coverage,ACC1234B29,bigwig]
Fetching files from version 12345
RNA coverage bigwig file angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bigWig found
Uploading RNA coverage bigwig file to 54321-II-1U in scout
Uploading rna coverage bigwig file /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bigWig to case fastsloth
Running command /path_to_binary/scout --config /path_to_config/scout-stage.yaml update individual -c fastsloth -n 54321-II-1U rna_coverage_bigwig /path_to_housekeeper-bundles/angrygoblin/2021-06-29/ACC1234B29_lanes_1_star_sorted_sj.bigWig
Uploaded RNA coverage bigwig file
Upload RNA coverage bigwig file finished!
```
🆗 uploaded RESEARCH fusion report and ordinary junction-files

**Review by Mropat — APPROVED** [review]

**Comment by emmser** [comment]
Åh vad bra!!

**Pull request merged**
