### PR TITLE
Add validation cases from balsamic to skip compression

### PR DESCRIPTION
**Pull request by mathiasbio**
## Description

For validation of balsamic v12.0.0 extra validation cases were added; positive controls with known clinically relevant SVs. 

PR to validation report: https://github.com/Clinical-Genomics/validations/pull/96

### Added
- 7 WGS T/N cases to skip compression used for test detection of SVs 

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ivadym — APPROVED** [review]
🎉 💯

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by mathiasbio** [comment]
Deployed to stage:
image

**Comment by mathiasbio** [comment]
Deploy master to stage:
image

Deploy master to production:
image

**Pull request merged**
