### PR TITLE
Update to Pydantic v2 in meta/upload/scout

### PR DESCRIPTION
**Pull request by islean**
## Description

Updates to Pydantic v2 in /cg/meta/upload/scout as part of issue https://github.com/Clinical-Genomics/project-planning/issues/514.

### Fixed

- We now import from Pydantic v2 in meta/upload/scout

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b update-pydantic-scout-models -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by islean** [comment]
After this update, tests work but we get a weird warning regarding return types for data classes. Do we think the update is worth it?:

image

**Comment by islean** [comment]
I have seen this bug mentioned for example here https://youtrack.jetbrains.com/issue/PY-61809 but I have not really seen a fix.

**Comment by seallard** [comment]
Found an issue, might be the editor: https://youtrack.jetbrains.com/issue/PY-61809

**Review by ChrOertlin — APPROVED** [review]
💯

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by diitaz93** [comment]
I think it is worth the merge, we have already some warnings of type hinting that are not a big problem

**Pull request merged**
