### PR TITLE
(fix) Update to pydantic v2 in Housekeeper.models

### PR DESCRIPTION
**Pull request by islean**
## Description

Updates to pydantic v2 in housekeeper.models.

### Changed

- Import pydantic v2
- Set default value for optional.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b fix-pydantic-v2-hk -a
    ```

### How to test

- [x] Run `cg workflow <pipeline> store <case_id>`

### Expected test outcome

- [x] Check that the storing to Housekeeper finishes successfully.
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by diitaz93 — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by islean** [comment]
Deployment to stage and `cg workflow mip-dna store <case_id>` executed successfully by IO.

**Pull request merged**
