### PR TITLE
Support RML OF 1604:10

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds new rml OF version

**How to prepare for test**:
- [x] ssh to clinical-db (depending on type of change)
- [x] install on stage:
`cd servers/resources/clinical-db.scilifelab.se/`
- [x] `bash update-clinical-api-stage.sh [THIS-BRANCH-NAME]`
- [x] if you do not now how to do above, you can Slack PG to do it :)

**How to test**:
- [x] login to OP
- [x] submit an 1604:10 OF where new data is used

**Expected test outcome**:
- [x] check that and order is created with the specified data
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [X] code approved by @barrystokman 
- [X] tests executed by @barrystokman 
- [X] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by barrystokman** [comment]
Test failed, orderform unsupported:

image

**Comment by barrystokman** [comment]
@moonso you can ignore the review request, it was triggered by solving a merge conflict

**Comment by moonso** [comment]
Great! A lot of merging these days, Iove it

**Comment by barrystokman** [comment]
Bumped:
image

Deployed:
image

**Pull request merged**
