### PR TITLE
propagate sample external name for display usage

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds sample_display_name to the mip-rd-dna case config

**How to prepare for test**:
- [x] install on stage: `bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh feat/propagate-cust-sample-name-to-mip`
- [x] activate stage: `us`

**How to test**:
- [x] run following command: `cg workflow mip-dna config-case -d vitalmouse`

**Expected test outcome**:
- [x] `cg` should add the `sample_display_name` for each sample in the case config
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @henrikstranneheim 
- [x] tests executed by @henrikstranneheim 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because we are adding a feature while maintaining backwards compatibility

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
cg should add the sample_display_name for each sample in the case config ✅ 
Screenshot 2020-02-10 at 10 41 46

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt It would be great if you could merge and deploy this one.

**Comment by patrikgrenfeldt** [comment]
I don't have the setup to bump from home, could @barrystokman do it?

**Comment by barrystokman** [comment]
version bumped!

**Comment by barrystokman** [comment]
Merged and bumped, @patrikgrenfeldt can you deploy?

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Could you deploy this one today?

**Pull request merged**
