### PR TITLE
Add new sequencing step info for the NovaSeq X in LIMS

### PR DESCRIPTION
**Pull request by Karl-Svard**
### Added
- New master step name of the NovaSeq X in LIMS

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍 . Is Atlas doc merged?

**Comment by henrikstranneheim** [comment]
Also one code smell to fix

**Comment by Karl-Svard** [comment]
Atlas doc used for this particular lims step is merged. But of course a few others remain.

**Comment by Karl-Svard** [comment]
I'll merge this PR in its current state in order to quickly fix the creation of delivery reports for samples sequenced on the NovaSeq X. A new PR will then be opened later for restructuring the lims constants.

**Pull request merged**
