### PR TITLE
Add subject id for fastq orders

### PR DESCRIPTION
**Pull request by islean**
## Description

Addresses #2884.

### Fixed

- Fastq orders get subject_id set on sample level.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by seallard — APPROVED** [review]
👍 It would be nice to have a better name than `subject_id` (what is that?) but out of scope. Also, do we want to store it on the order model?

**Comment by islean** [comment]
> 👍 It would be nice to have a better name than `subject_id` (what is that?) but out of scope. Also, do we want to store it on the order model?

I don't think there is a need to set it on order_id. This seems to be used to link e.g. RNA samples to corresponding DNA samples. If it should be added, it would need to be refined a bit. Currently I think subject_id can be set per sample, meaning that it is not one subject_id per order.

**Comment by islean** [comment]
Tested on stage and the subject_id is now set for fastq orders: 

image

**Comment by henrikstranneheim** [comment]
Subjekt_id represents the (organism) that a sample has been isolated from. It is a unique identifier used to link multiple samples to an organism.

**Pull request merged**
