### PR TITLE
Include workflow limitations in applications endpoint

### PR DESCRIPTION
**Pull request by ivadym**
## Description

Including the workflow limitations to simplify its access in the order portal:
https://github.com/Clinical-Genomics/cg/pull/3000#issuecomment-1969105379

Issue in the UI: https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/396

### Added
- Workflow limitations dictionary to applications endpoint

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [x] With workflow limitations: https://cg-statusdb-stage.scilifelab.se/api/v1/applications/RNAPOAR100
- [x] Without workflow limitations: https://cg-statusdb-stage.scilifelab.se/api/v1/applications/VWGDPTR001

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]

**Review by moedarrah — APPROVED** [review]
Nice, I'll handle the Front-end once the pull request is merged.

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by ivadym** [comment]
> Nice, I'll handle the Front-end once the pull request is merged.

Great! Thanks @moedarrah!

**Comment by ivadym** [comment]
Screenshot 2024-04-17 at 11 04 18

**Pull request merged**
