### PR TITLE
Add module for calculating sequencing metrics

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR adds a module containing logic for calculating the metrics we need to populate the SequencingStatistics model.
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — COMMENTED** [review]
We should keep this separate per bcl converter by e.g. using a sub folder structure with bcl2fastq and bclconvert

**Comment by seallard** [comment]
I was hoping we could reuse these functions for both modules since they only accept raw values and the metrics should be calculated in the same fashion no matter which Demultiplexing software was used

**Comment by ChrOertlin** [comment]
Agreed, I just hope the software output structure will allow us to do so. Might be too much of a hassle to streamline both to each other. For example the bcl convert already gives pre-calculated metrics

**Comment by seallard** [comment]
Oh, that is nice! Then we can use those values. 

If there are any other values which need to be calculated, I think it would be good to place that logic in a shared module

**Pull request closed without merging**
