### PR TITLE
Feat: customer contacts as emails

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
## Description
*This PR changes that customer contact persons are referred to as emails instead of users. This removes the need to add each contact as a user in the system and it becomes easier to manage the user list*

### How to prepare for test
- [x] ssh to relevant server (hasta & clinical-db)
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test migration
- [x] do open clinical-api-stage and edit the first customer
- [x] select three different users for contacts
- [x] migrate

### Expected test outcome
- [x] check that the tree users emails are present on the customer
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by MR
- [x] tests executed by PG
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [x] Document in changelog
- [ ] Deploy this branch
- [ ] Inform to AG

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result:
image
image
🆗 users migrated to emails on correct places

**Review by Mropat — APPROVED** [review]

**Comment by patrikgrenfeldt** [comment]
deployed to clinical-db: 
image

deployed to hasta:
image

migration:
image

**Comment by patrikgrenfeldt** [comment]
@annagellerbring this is now in production!

**Comment by annagellerbring** [comment]
As discussed yesterday with @patrikgrenfeldt, the email addresses for each customer are not visible in the "regular" view, only in "editing" view.

**Pull request merged**
