### PR TITLE
Balsamic clean ignores errors

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...
Small fix to make cg clean function continue deleting files after encountering permission error

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to stage
- [x] put some dummy files and dirs in /home/proj/stage/cancer/cases/ablemagpie to clean
- [x] run cg clean balsamic-run-dir ablemagpie

### Expected test outcome
- [x] check that cg tries to clean whole directory despite permission errors raised by some files
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by MR
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Mropat** [comment]
Ablemagpie dir before
image

After clean, handled errors
image

**Review by patrikgrenfeldt — APPROVED** [review]
Awesome!

**Comment by Mropat** [comment]
stage
image

prod
image

**Comment by henrikstranneheim** [comment]
Nice work!

**Pull request merged**
