### PR TITLE
Add cascading

### LINKED ISSUE #3805: Set up cascading properties of polymorphic tables
As a developer,
I want the deletion of a `run_device` or `instrument_run` entry to cascade to `pacbio_sequencing_run`, `illumina_sequencing_run` and `sample_sequencing_metrics ` (and children),
So that I don't have to delete everything manually in a complex way.

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Apparently but I have not found it
- How much time would be saved by implementing this feature on a weekly basis?
    - Hopefully not much
- How many users are affected by this issue?
    - All sysdevs and prodbioinfo members. Malformed data will affect customers in the long run.
- Are customers affected by this issue?
    - No

# Acceptance Criteria

- [x] Deleting a `run_device` entry should delete the related `pacbio_smrt_cell`
- [x] Deleting a `run_device` entry should delete the related `illumina_flow_cell`
- [x] Deleting a `run_device` entry should delete any related `instrument_run`
- [x] Deleting an `instrument_run` should delete the related `pacbio_sequencing_run`
- [x] Deleting an `instrument_run` should delete the related `illumina_sequencing_run`
- [x] Deleting an `instrument_run` should delete any related `sample_run_metrics`
- [x] Deleting a `sample_run_metrics` should delete the related `illumina_sample_sequencing_metrics`
- [x] Deleting a `sample_run_metrics` should delete the related `pacbio_sample_run_metrics`

### PR DESCRIPTION
**Pull request by islean**
## Description

Closes #3805 .

### Added

-

### Changed

-

### Fixed

- Cascading properties from the devices project

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b add-cascading -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]

**Comment by islean** [comment]
Upgrade applied successfully:

```
(cg_11) isakohlsson@isakoambp cg % alembic -c alembic/alembic.stage.ini revision -m "Add cascading properties"
  Generating /Users/isakohlsson/dev/cg/alembic/versions/2024_10_08_3b165ec34791_add_cascading_properties.py ...  done
(cg_11) isakohlsson@isakoambp cg % alembic -c alembic/alembic.stage.ini upgrade 3b165ec34791
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade d6474325c722 -> 3b165ec34791, Add cascading properties
(cg_11) isakohlsson@isakoambp cg % 

```

**Comment by islean** [comment]
All cascading foreign keys in stage:

image

**Comment by islean** [comment]
To test:


- [] Deleting a `run_device` entry should delete the related `pacbio_smrt_cell`
- [] Deleting a `run_device` entry should delete the related `illumina_flow_cell`
- [] Deleting a `run_device` entry should delete any related `instrument_run`
- [] Deleting an `instrument_run` should delete the related `pacbio_sequencing_run`
- [] Deleting an `instrument_run` should delete the related `illumina_sequencing_run`
- [] Deleting an `instrument_run` should delete any related `sample_run_metrics`
- [] Deleting a `sample_run_metrics` should delete the related `illumina_sample_sequencing_metrics`
- [] Deleting a `sample_run_metrics` should delete the related `pacbio_sample_run_metrics`

**Comment by islean** [comment]
Downgrade also successful:

```
(cg_11) isakohlsson@isakoambp cg % alembic -c alembic/alembic.stage.ini downgrade d6474325c722
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 3b165ec34791 -> d6474325c722, Add cascading properties
(cg_11) isakohlsson@isakoambp cg % 

```

image

**Comment by islean** [comment]
Tested:

Deleted a run device connected to a pacbio run - corresponding pacbio smrt cell, and sample sequencing metrics were deleted ✅

**Comment by islean** [comment]
Deleting via the web ui also works even with polymorphism

**Comment by islean** [comment]
Problem - Deletion via the web ui leaves ghost entries in the run_device tables.

**Comment by islean** [comment]
Deployed to hasta and the VMs:

```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade d6474325c722 -> 3b165ec34791, Add cascading properties
[isak.ohlsson@hasta:~] [P_base] $ 
```

**Pull request merged**
