### PR TITLE
Only auto-start MIP analyses

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR removes faulty automatic starting of RNA cases 

**How to prepare for test**:
- [x] install on stage of the hasta machine: `bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh skip-MAF-for-RNA`
- [x] activate stage: `us`

**How to test**:
- [x] run following command: `cg analysis auto --dry-run` to get a list of cases ready for analysis
- [x] change application of on of the samples of one of the cases in the previous list to one for RNA (e.g RNADEPR030)
- [x] run following command: `cg analysis auto --dry-run`

**Expected test outcome**:
- [x] `cg` should say that it now skips the case that was changed.
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [x] tests executed by @patrikgrenfeldt 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because it adds the option to dry-run auto

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result:
image

**Comment by patrikgrenfeldt** [comment]
@barrystokman @b4ckm4n could one of you have a look on the code?

**Comment by barrystokman** [comment]
Code looks good, I say M&D :metal:

**Comment by patrikgrenfeldt** [comment]
Thanks!

**Pull request merged**
