### PR TITLE
refactor(functions related to metrics db entry)

### PR DESCRIPTION
**Pull request by ChrOertlin**
## Description

Added functions to fine tune database entry for the sample sequencing metrics.

### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by seallard — COMMENTED** [review]
Nice, we definitely need the existence check 👍  How does this work if we are running `demultiplex finish` again for a flow cell? 

I think @Vince-janv mentioned that sometimes flow cells are re-demultiplexed when an index has been assigned erroneously and I guess that would include re-running the demultiplex finish command

**Review by seallard — APPROVED** [review]
👍 
We need to consider why we parse duplicates and handle it as well, but this is good!

**Comment by ChrOertlin** [comment]
> Nice 👍 We need to consider why we parse duplicates and handle it as well, but this is good! Also what should happen when we rerun the finish command for a re-demultiplexed flow cell.

I think we can pass a parameter in the finish flow-cell that allows to overwrite in case of re-runs?

**Comment by ChrOertlin** [comment]
Stage:
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/christian.oertlin
done.
Log deploy... done.
cg, version 37.0.10

Prod:
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/christian.oertlin
done.
Log deploy... done.
cg, version 37.0.10

**Comment by seallard** [comment]
> > Nice 👍 We need to consider why we parse duplicates and handle it as well, but this is good! Also what should happen when we rerun the finish command for a re-demultiplexed flow cell.
> 
> I think we can pass a parameter in the finish flow-cell that allows to overwrite in case of re-runs?

That could be a good solution 👍

**Pull request merged**
