### PR TITLE
feat(gene_panels): Update master list with "MOVE"

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:
- Update master list with "MOVE"
- Order list alphabetically

### How to prepare for test
- [x] ssh to hasta
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta
- [x] do `us`
1. `cg workflow mip-dna panel -d vitalmouse`

### Expected test outcome
- [x] check that cg tries to connect to scout using the new MOVE panel ✅ 

## Review
- [x] code approved by PG
- [x] tests executed by HS
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
I would like to deploy this now. Is it ok @moonso, @patrikgrenfeldt ?

**Comment by moonso** [comment]
Feel free to go ahead @henrikstranneheim !

**Comment by henrikstranneheim** [comment]
Deployed on hasta:
Screenshot 2020-08-25 at 08 31 15

**Comment by henrikstranneheim** [comment]
@karlnyr Now new analyses should automatically get the Move gene panel included for customers using the Master list

**Pull request merged**
