### PR TITLE
fix(admin view) Made tickets filterable and added new batch options

### PR DESCRIPTION
**Pull request by Vince-janv**
### Added (Family view)

- Batch function to set cases to HOLD
- Batch function to set cases to Empty
- Possibility to filter by tickets
- Possibility to search for families with given ticket

### How to prepare for test

- [x] Deploy branch to cg-vm1

### How to test

- [x] Go to the family tab in the stage admin view page.
- [x] Select cases you want to change action of.
- [x] Under `With selected` select `Set to HOLD`
- [x] Mark the cases again and select `Set to Empty`
- [x] Try to filter by ticket
- [x] Try to search for a ticket

### Expected test outcome

- [x] The database is updated to the correct actions
- [x] Families are correctly filtered
- [x] Families appear when their ticket is searched for

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by Vince-janv** [comment]
### Using the Tickets filter:
Screenshot 2022-12-14 at 16 30 05
### Set to HOLD:
Screenshot 2022-12-14 at 16 30 23
### Set to Empty:
Screenshot 2022-12-14 at 16 30 39
### Search for ticket:
Screenshot 2022-12-14 at 16 30 59

**Review by moahaegglund — APPROVED** [review]
Very good! 🙌

**Review by mathiasbio — APPROVED** [review]
Awesome job! 👍

**Review by henrikstranneheim — APPROVED** [review]
Nice! 👍

**Comment by Vince-janv** [comment]
### Release deployed on cg-prod-services via github action

**Pull request merged**
