### PR TITLE
Fix/cg clean mipauto mip backwards compat

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes cg clean mipauto

**How to prepare for test**:
- [x] ssh to hasta
- [x] install on stage:
`bash servers/resources/hasta.sclifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`
- [x] install on stage:
`bash servers/resources/hasta.sclifelab.se/update-trailblazer-stage.sh [THIS-BRANCH-NAME]`

**How to test dry-run**:
- [x] login to hasta 
- [x] run `cg clean mipauto `date -d '-40days' +'%Y-%m-%d'` -d`

**Expected test outcome**:
- [x] check that that the case was not deleted

**How to test delete**:
- [x] login to hasta 
- [x] run `cg clean mipauto `date -d '-40days' +'%Y-%m-%d'``

**Expected test outcome**:
- [x] check that that the case was deleted

- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @adrosenbaum 
- [x] tests executed by @patrikgrenfeldt @henrikstranneheim 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
test dry run:
image
👍

**Comment by patrikgrenfeldt** [comment]
test real run:
image
👍

**Comment by patrikgrenfeldt** [comment]
deployed on hasta and clinical-db

**Comment by patrikgrenfeldt** [comment]
Test result clean scout with dry-run flag:
image
👍

**Comment by patrikgrenfeldt** [comment]
Test result scoutauto with dry-run:
image
👍

**Comment by henrikstranneheim** [comment]
Looks great! Could you could you include a case with CRAM files as well? Eg. onemite on stage

**Pull request merged**
