### PR TITLE
(Improve order flow) Fix other alias

### PR DESCRIPTION
**Pull request by islean**
## Description

We run into issues due to the order forms not formatted the "other" buffer option in a homogeneous way:

image

On top of this, the order form owners will aim to remove the "Specify in comments"/"add to comment" addition, and just exchange the buffer for anything but Nuclease-free water or Tris-HCl either way. This PR changes the enum to only have the option stating "Other" and adds a before validator to the pydantic models for parsing any buffer beginning with "Other" to this option.

### Added

-

### Changed

-

### Fixed

- Other is the only allowed formatting of the other buffer option. 
- Validator for parsing the elution buffer

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — COMMENTED** [review]
🤔 🤔 🤔 🤔 Change in the front end better?

**Comment by islean** [comment]
> 🤔 🤔 🤔 🤔 Change in the front end better?

The order forms seem consistent! I will check with MOD if he can do a change!

**Comment by islean** [comment]
Closing in favour of https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/611

**Comment by islean** [comment]
Will change the formatting to match the order form in the BE as well, but not have several "other" options

**Review by ChrOertlin — APPROVED** [review]

**Review by diitaz93 — APPROVED** [review]
Looks much better now 💯

**Pull request merged**
