### PR TITLE
move TB queries to Trailblazer

### PR DESCRIPTION
**Pull request by Mropat**
This PR adds/fixes ...

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta 
- [x] do up
- [x] install Trailblazer feat/api-queries
- [x] do cg workflow mip-dna -c keenviper

### Expected test outcome
- [x] No broken imports or requirements
- [x] Case starts successfully and is tracked by Trailblazer on stage

## Review
- [x] code approved by MM
- [x] tests executed by MR
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

To be deployed simultaneously with  [Trailblazer # 114](https://github.com/Clinical-Genomics/trailblazer/pull/114)

### CODE REVIEW

**Review by moonso — APPROVED** [review]
😸 So nice when it's all red...

**Comment by Mropat** [comment]
MIP-dna starts
image
Tb-stage gets case added
image

**Comment by Mropat** [comment]
Deployed with TB stage
image
Deployed with TB prod
image

**Comment by Mropat** [comment]
Deployed on stage
image

Deployed on prod
image

**Pull request merged**
