### PR TITLE
Order Form 1508:18 supported in the Order Portal

### PR DESCRIPTION
**Pull request by barrystokman**
This PR adds support for order form 1508:18 in the order portal.

The order form has an added field 'bone marrow' to the `sample source` drop down menu.

**How to test**:

**Preconditions**:
1. Install on stage:
    1. On Hasta run `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh of-1508-18-in-op`
    1. On clinical-db run `bash /home/hiseq.clinical/servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh of-1508-18-in-op`
    1. On clinical-db run `bash /home/hiseq.clinical/servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh`
1. Prepare order form:
    1. use this new order form (prefilled with test data): [1508-18_1508-18_Orderform_Clinical_samples.xlsx](https://github.com/Clinical-Genomics/cg/files/3368385/1508-18_1508-18_Orderform_Clinical_samples.xlsx)
 and save it to a convenient location.
    1. Remember file location from previous step.

**Test execution**
1. Go to https://clinical-stage.scilifelab.se/ and log in.
1. Click on `Ny order`.
1. Upload the order form from the location you choose in step 2.ii of the preconditions section.
1. If you forgot the file location, repeat step 2 of the preconditions section and bow your head in shame because I **told** you to remember the file location.

**Expected result**:
1. The order form should upload without errors.
1. Sample `TEST-SAMPLE-OF150818-1` should show `bone marrow` as source in the order portal.
1. Go to LIMS, search for the samples and check the `source` in the Lab View.

**Review:**
- [x] code approved by @ingkebil 
- [x] tests executed by @barrystokman, test design reviewed by @emiliaol
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is a minor **version bump** because it's a backwards compatible change to the order form

### CODE REVIEW

**Comment by barrystokman** [comment]
I'm fixing the unit tests too!

**Comment by barrystokman** [comment]
@ingkebil @emiliaol @b4ckm4: ready for review and test, please review the test case too. Considering the changes I made, I see no risk for the other existing order forms, maybe me and @emiliaol can have a look to be sure.

**Comment by barrystokman** [comment]
Regression tested with the other order forms, no regression found. We do need to look at the external sample sheet since it is not working, I'll make a user story for that.

**Comment by ingkebil** [comment]
Approved!

**Pull request merged**
