### PR TITLE
(Archiving) Reuse instantiation

### PR DESCRIPTION
**Pull request by islean**
## Description

Since the rework of the archiving flow to accomodate metadata, which meant that we needed to send one request per file, we have also re-instantiated the `DDNDataflowClient` for every file as well. This means inefficiency and also additional requests towards the API, since we fetch new authorization tokens every time we instantiate the `DDNDataflowClient`. 

This PR makes sure that we instantiate the client once per archival batch, and maximum two times for updating job statuses (once for ongoing archivals and once for ongoing retrievals). Ideally, we might want to refactor the latter to one time in total, but currently I don't see the need for it.

### Fixed

- The archive handlers are instantiated once per batch instead of once per file.

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b archiving-refactor -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Nice 👍

**Review by diitaz93 — APPROVED** [review]
Nice 💯

**Comment by islean** [comment]
Tested on Hasta and both archiving and querying ongoing jobs went well, although there seems to be an issue with the get_job_statuses endpoint currently.

**Comment by islean** [comment]
Deployed to production:

```
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/isak.ohlsson
done.
Log deploy... done.
cg, version 55.4.4
θ65° [isak.ohlsson@hasta:~] [P_base] 2m37s $ 
```

**Pull request merged**
