### PR TITLE
Validate special requirements for PAx and EXx applications in Orderportal

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds the requirement of elution buffer for mip exome and panel applications 

Contact: @annagellerbring @annaengstrom 

How to install: 
1. install or ask someone to install cgweb and clinical-api branch on clinical-db

How to test validation of elution buffer:
1. create mip order in op
1. add family
1. add sample
1. select any application starting with PA or EX
1. try to save sample

Expected outcome:
Red box around elution buffer

How to test validation of capture-kit:
1. create mip order in op
1. add family
1. add sample
1. select any application starting with PA
1. try to save sample

Expected outcome:
Red box around capture kit

How to test submission of elution buffer:
1. create mip order in op
1. add family
1. add sample
1. select any application starting with PA or EX
1. select elution buffer
1. submit
1. open sample in LIMS

Expected outcome:
Elution buffer on the LIMS sample

How to test submission of capture_kit buffer:
1. create mip order in op
1. add family
1. add sample
1. select any application starting with PA 
1. select capture_kit buffer
1. submit
1. open sample in LIMS

Expected outcome:
capture_kit buffer on the LIMS sample

- [x] Code reviewed by @ingkebil 
- [x] Tested by @barrystokman
- [x] Deploy OK:d by @ingkebil

This is a minor **version bump** because it is a bug fix

### CODE REVIEW

**Comment by annaengstrom** [comment]
@emiliaol In referral to the Orderportal issue in ticket #867584 I ask you to bring this to TTN (Patrik Grenfeldt posted 2019/06/20 5:43 PM).

**Comment by ingkebil** [comment]
See also #387

**Comment by ingkebil** [comment]
@Clinical-Genomics/laboratory who wants to test this? Just let me know and I'll set up the stage order portal for this :)

**Comment by barrystokman** [comment]
>  How to test validation of elution buffer:
> 
> create mip order in op
> add family
> add sample
> select any application starting with PA or EX
> try to save sample
> Expected outcome:
> Red box around elution buffer
> 
TEST PASSED :heavy_check_mark: 

image

**Comment by barrystokman** [comment]
> How to test validation of capture-kit:
> 
> create mip order in op
> add family
> add sample
> select any application starting with PA
> try to save sample
> Expected outcome:
> Red box around capture kit
TEST PASSED heavy_check_mark

image

**Comment by barrystokman** [comment]
> How to test submission of elution buffer:
> 
> create mip order in op
> add family
> add sample
> select any application starting with PA or EX
> select elution buffer
> submit
> open sample in LIMS
> Expected outcome:
> Elution buffer on the LIMS sample

TEST PASSED :heavy_check_mark: 

image

**Comment by barrystokman** [comment]
> How to test submission of capture_kit buffer:
> 
> create mip order in op
> add family
> add sample
> select any application starting with PA
> select capture_kit buffer
> submit
> open sample in LIMS
> Expected outcome:
> capture_kit buffer on the LIMS sample

TEST PASSED :chec

image

**Comment by barrystokman** [comment]
@ingkebil With testing approved, can we deploy soon to (hopefully) get rid of the Travis errors? :)

We need to deploy https://github.com/Clinical-Genomics/cgweb/pull/143 too btw, everything is tested and code reviewed, I believe.

**Comment by ingkebil** [comment]
Approved! This needs to be deployed on clinical-db. Are you on it @barrystokman ?

**Comment by barrystokman** [comment]
On it!

**Comment by barrystokman** [comment]
@annagellerbring @annaengstrom This fix is now in production!

**Pull request merged**
