### PR TITLE
Fluffy samplesheet controls

### PR DESCRIPTION
**Pull request by Mropat**
### Added

- New column Control in fluffy samplesheet

### Changed

- Use pandas to parse sampelsheets for fluffy

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by J35P312** [comment]
Hello!
This looks promising! Nicely done =P.

Keep in mind, that fluffy does not use the control column: Fluffy wants a column named "Exclude" or "exclude", and the entries should be labled true or false, depending on if they should be excluded from the reference or not.

Fluffy also wants the flowcell ID and indexes.

**Comment by Mropat** [comment]
Test create samplesheet output @J35P312 

```
[0|0|0] [maryia.ropart@hasta:~] [S_main] 2m19s $ cg workflow fluffy create-samplesheet vocalbull
Case vocalbull exists in status db
Fetching files from bundle HG7GWDRXY
Fetching files with tags in [samplesheet]
Writing modified csv from /home/proj/production/demultiplexed-runs/210712_A00689_0305_AHG7GWDRXY/Unaligned/SampleSheet.csv to /home/proj/stage/nipt/cases/vocalbull/SampleSheet_2111805_NIPT.csv
[0|0|52] [maryia.ropart@hasta:~] [S_main] 32s $ cat /home/proj/stage/nipt/cases/vocalbull/SampleSheet_2111805_NIPT.csv
FCID,Lane,SampleID,SampleRef,index,index2,SampleName,Control,Recipe,Operator,Project,Library_nM,SequencingDate,Exclude
HG7GWDRXY,1,ACC8197A46,hg19,CCGCTGTT,TGCGGTCT,2021-02272-08,N,R1,script,2111805_NIPT,157.11,2021-07-13,False
HG7GWDRXY,1,ACC8197A24,hg19,GATTCCTT,TGCCTATG,2021-18745-07,N,R1,script,2111805_NIPT,138.18,2021-07-13,False
HG7GWDRXY,1,ACC8197A1,hg19,CTACGAAG,CTGTCGAG,2021-19797-06,N,R1,script,2111805_NIPT,168.4,2021-07-13,False
HG7GWDRXY,1,ACC8197A2,hg19,CTTAATAC,CACAATGG,2021-19798-06,N,R1,script,2111805_NIPT,192.77,2021-07-13,False
HG7GWDRXY,1,ACC8197A3,hg19,CTTATGAA,ACATTGGC,2021-19799-06,N,R1,script,2111805_NIPT,134.38,2021-07-13,False
HG7GWDRXY,1,ACC8197A4,hg19,CTATCATT,AGGTGGTC,2021-19800-06,N,R1,script,2111805_NIPT,75.29,2021-07-13,False
HG7GWDRXY,1,ACC8197A5,hg19,CTGGAAGC,TCTGCACC,2021-19801-05,N,R1,script,2111805_NIPT,82.22,2021-07-13,False
HG7GWDRXY,1,ACC8197A6,hg19,CAACCGTG,CGTGAGAG,2021-19826-06,N,R1,script,2111805_NIPT,81.44,2021-07-13,False
```

**Comment by J35P312** [comment]
I approve!

**Review by J35P312 — APPROVED** [review]
very nice!

**Pull request merged**
