### PR TITLE
Set action to "analyze" for cases that decompression started for

### PR DESCRIPTION
**Pull request by henningonsbring**
Currently when `cg workflow mip-dna start <case ID>` is used and the fastqs are decompressed to spring, the user will have to run `cg workflow mip-dna start <case ID>` one more time after the decompression is done. This PR will make the cron tab start the analysis automatically after the decompression is done.

### How to prepare for test
- [x] ssh to hasta
- [x] Use stage: `us`
- [x] paxa the environment: `paxa`
- [x] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh automated_reruns`

### How to test
- [x] do mip-analysis on a case that is compressed to spring

### Expected test outcome
- [x] decompression will start
- [x] when decompression is done the analysis will be started automatically by the cron tab
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by
- [x] tests executed by HO (by telling PG what commands to run on stage, and PG reported back the results)
- [x] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henningonsbring** [comment]
```
cg get family finecow
+----------+---------------+------------+------------+-----------+----------+
| Family   | Name          | Customer   | Priority   | Panels    | Action   |
|----------+---------------+------------+------------+-----------+----------|
| finecow  | AUTOSPRING100 | cust000    | standard   | OMIM-AUTO | NA       |
+----------+---------------+------------+------------+-----------+----------+
+----------+----------+----------+
| Sample   | Mother   | Father   |
|----------+----------+----------|
| ANID1    |          |          |
+----------+----------+----------+
+----------+--------+------------+---------------+--------------------+------------+-------------+
| Sample   | Name   | Customer   | Application   | State              | Priority   | External?   |
|----------+--------+------------+---------------+--------------------+------------+-------------|
| ANID1    | ANID1  | cust000    | WGXCUSC000    | Ordered 2021-02-12 | standard   | Yes         |
+----------+--------+------------+---------------+--------------------+------------+-------------+

```

**Comment by henningonsbring** [comment]
```
cg workflow mip-dna start -p low finecow
Starting full MIP-DNA analysis workflow for case finecow
All flowcells present on disk
Fetch latest version from bundle ANID1
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Compression/decompression is not running
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Fetch latest version from bundle ANID1
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002_R1_001.fastq.gz does not exist
Decompression is possible
Fetch latest version from bundle ANID1
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.spring
Found file /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.spring
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001_R1_001.fastq.gz does not exist
Decompression is possible
Decompressing /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.spring to FASTQ format for sample ANID1
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.json
Validating SPRING metadata content
Generating sbatch header
Generating SPRING to FASTQ sbatch body
Created temporary dir /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/spring_q3h5g5u3_decompress
Submit sbatch
Creating pending flag
Running command sbatch /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001_decompress_spring.sh
Submitted batch job 950959
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L001.json
Validating SPRING metadata content
Adding todays date to SPRING metadata file
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.crunchy.pending.txt does not exist
Check if SPRING archive file exists
Check if FASTQ pair exists
/home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002_R1_001.fastq.gz does not exist
Decompression is possible
Decompressing /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.spring to FASTQ format for sample ANID1
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.json
Validating SPRING metadata content
Generating sbatch header
Generating SPRING to FASTQ sbatch body
Created temporary dir /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/spring_4fdcjtaz_decompress
Submit sbatch
Creating pending flag
Running command sbatch /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002_decompress_spring.sh
Submitted batch job 950960
Fetch SPRING metadata from /home/proj/stage/housekeeper-bundles/movingjay/2020-01-28/ANID1_XXXXXX_S26_L002.json
Validating SPRING metadata content
Adding todays date to SPRING metadata file
The analysis for finecow could not start, started decompression instead
Workflow interrupted: decompression is not finished
```

**Comment by henningonsbring** [comment]
```
cg get family finecow
+----------+---------------+------------+------------+-----------+----------+
| Family   | Name          | Customer   | Priority   | Panels    | Action   |
|----------+---------------+------------+------------+-----------+----------|
| finecow  | AUTOSPRING100 | cust000    | standard   | OMIM-AUTO | analyze  |
+----------+---------------+------------+------------+-----------+----------+
+----------+----------+----------+
| Sample   | Mother   | Father   |
|----------+----------+----------|
| ANID1    |          |          |
+----------+----------+----------+
+----------+--------+------------+---------------+--------------------+------------+-------------+
| Sample   | Name   | Customer   | Application   | State              | Priority   | External?   |
|----------+--------+------------+---------------+--------------------+------------+-------------|
| ANID1    | ANID1  | cust000    | WGXCUSC000    | Ordered 2021-02-12 | standard   | Yes         |
+----------+--------+------------+---------------+--------------------+------------+-------------+
```

**Review by moonso — APPROVED** [review]
👍 A bit smaller than the last one :)

**Comment by Mropat** [comment]
Deployed on prod

```
Building wheels for collected packages: cg
  Building wheel for cg (PEP 517) ... done
  Created wheel for cg: filename=cg-19.2.0-py3-none-any.whl size=397439 sha256=bc883a9ece9e66c515af0899a05e570030881090fad4439832792d63367b2d38
  Stored in directory: /home/maryia.ropart/tmp/pip-ephem-wheel-cache-yekrio29/wheels/8c/1e/b8/816ed4facf8c5628b55966d3f2448eeb6ca70f35deff59389e
Successfully built cg
Installing collected packages: cg
  Attempting uninstall: cg
    Found existing installation: cg 19.1.1
    Uninstalling cg-19.1.1:
      Successfully uninstalled cg-19.1.1
Successfully installed cg-19.2.0
```

**Pull request merged**
