### PR TITLE
Save scout load config

### PR DESCRIPTION
**Pull request by moonso**
This PR adds so that scout load configs are always saved to disc

**How to prepare for test**:
- [x] install on stage on hasta: `bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh save-scout-load-config`
- [x] activate stage: `us`

**How to test**:
- [x] run following command: `cg upload scout CASE_ID`

**Expected test outcome**:
- [x] check housekeeper that `scout_load_config.yml` is there
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [x] tests executed by @patrikgrenfeldt 
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because it adds functionality

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
image
👍

**Comment by moonso** [comment]
So @patrikgrenfeldt what is left to get this merged?

**Comment by ingkebil** [comment]
The last linting errors are typical pytest linting errors that are hard to get rid of. Approving

**Comment by moonso** [comment]
🎆 🍾 😃

**Comment by patrikgrenfeldt** [comment]
deployed

**Pull request merged**
