### PR TITLE
fix(update): Pydantic model Cgconfig

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b fix-pydantic-field
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### Cg executes without fields, 👍 
```
nrik.stranneheim@hasta:~] [S_base] $ cg get case justhusky
+-----------+--------------------------------+------------+------------+-----------+----------+
| Case      | Name                           | Customer   | Priority   | Panels    | Action   |
|-----------+--------------------------------+------------+------------+-----------+----------|
| justhusky | SWEDAC-2019-HG-05-Trio-NovaSeq | cust000    | priority   | OMIM-AUTO | NA       |
+-----------+--------------------------------+------------+------------+-----------+----------+
+-------------------+----------+----------+
| Sample            | Mother   | Father   |
|-------------------+----------+----------|
| earlycasualcaiman |          |          |
+-------------------+----------+----------+
+-----------------+----------+----------+
| Sample          | Mother   | Father   |
|-----------------+----------+----------|
| slowlycivilbuck |          |          |
+-----------------+----------+----------+

**Review by islean — APPROVED** [review]
Nice! I don't think we need to be explicit about which fields we allow arbitrary types for 💪

**Comment by Vince-janv** [comment]
Will this PR resolve this issue?
https://github.com/Clinical-Genomics/cg/issues/3827

**Comment by henrikstranneheim** [comment]
> Will this PR resolve this issue? #3827

Yes, linked it!

**Comment by henrikstranneheim** [comment]
Deployed to prod.
```
Log deploy... done.
cg, version 63.5.4

**Pull request merged**
