### PR TITLE
Remove function for retrieving sample ids

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR replaces a function which wrapped the `get_sample_ids` function on the sample sheet with a direct call to it.
This function
```python
def get_sample_internal_ids_from_sample_sheet(
    sample_sheet_path: Path, flow_cell_sample_type: Type[FlowCellSample]
) -> List[str]:
    """Return the sample internal ids for samples in the sample sheet."""
    sample_sheet = get_sample_sheet_from_file(
        infile=sample_sheet_path, flow_cell_sample_type=flow_cell_sample_type
    )
    return sample_sheet.get_sample_ids()
```
is always called in a context where we have a sample sheet object available. It is not necessary to reparse the entire sample sheet each time we want to retrieve the sample ids. We can just call `sample_sheet.get_sample_ids()` directly.

### Fixed
- Replace unnecessary function for retrieving sample ids from a sample sheet

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Great! 👍

**Review by diitaz93 — APPROVED** [review]
Great simplification 👍

**Review by ChrOertlin — APPROVED** [review]
Nice!

**Comment by seallard** [comment]
Deployed to stage. Could not set up suitable flow cell for testing, but existing tests cover the refactored functionality.

**Pull request merged**
