### PR TITLE
Refactor pipeline to workflow applicationlimit

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Pipeline to workflow in applicationLimitations for database and end-point.

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b refactor-pipeline-to-workflow-applicationlimit -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@ivadym @islean @moedarrah Do you know what apps use the end-point? I am guessing the order portals.

**Comment by moedarrah** [comment]
I think we only use it in the old one "CGWeb": https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/396

**Review by ivadym — APPROVED** [review]
Nice 👍

**Comment by ivadym** [comment]
> I believe we only use it in the old one "CGWeb": [Clinical-Genomics/clinical-genomics-ui#396](https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/396) I will add it to the new order porter

Yes, it's only used by the old order portal

**Comment by henrikstranneheim** [comment]
We promised to keep it alive for a couple of weeks, but the real question is if we should add the use of this end-point to the new OP? Otherwise I will remove it.

**Comment by moedarrah** [comment]
> We promised to keep it alive for a couple of weeks, but the real question is if we should add the use of this end-point to the new OP? Otherwise I will remove it.

The endpoint is not working in the old OP: 
Screenshot 2024-02-28 at 15 12 26

**Comment by ivadym** [comment]
> > We promised to keep it alive for a couple of weeks, but the real question is if we should add the use of this end-point to the new OP? Otherwise I will remove it.
> 
> The endpoint is not working in the old OP: Screenshot 2024-02-28 at 15 12 26

That apptag does not have a pipeline limitation, try with `RNAPOAR100`.

**Comment by ivadym** [comment]
> We promised to keep it alive for a couple of weeks, but the real question is if we should add the use of this end-point to the new OP? Otherwise I will remove it.

I think we should keep it. We have a project https://github.com/Clinical-Genomics/project-planning/issues/534 and I believe AG and AZ are  currently writing the new descriptions and limitations

**Comment by moedarrah** [comment]
> We promised to keep it alive for a couple of weeks, but the real question is if we should add the use of this end-point to the new OP? Otherwise I will remove it.

Can you include it here: https://cg-statusdb.scilifelab.se/api/v1/applications/{application-id}

**Comment by henrikstranneheim** [comment]
@pbiology and @annagellerbring Do you think we can stop supporting the old order portal from Monday next week?

**Comment by annagellerbring** [comment]
> @pbiology and @annagellerbring Do you think we can stop supporting the old order portal from Monday next week?

No one have contacted us saying that they cannot use the new portal, so I can send an email with a heads up that we want to stop using the old from next monday and see if we get any complaints?

**Comment by henrikstranneheim** [comment]
@annagellerbring Thx!

**Comment by henrikstranneheim** [comment]
Deployed in production:
```
Log deploy... done.
cg, version 59.14.6

**Pull request merged**
