### PR TITLE
fix failing microsalt store complete cronjob

### PR DESCRIPTION
**Pull request by barrystokman**
This PR fixes a wrong key in `context.obj`, see https://github.com/Clinical-Genomics/cg/pull/813 

### How to prepare for test
see PR https://github.com/Clinical-Genomics/cg/pull/813

### How to test
- [x] do `cg store microsalt completed`

### Expected test outcome
- [x] check that `cg store microsalt completed` doesn't error on ` KeyError: 'analysis_api'`
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [x] tests executed by @barrystokman 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by barrystokman** [comment]
Test:
image
:check

**Comment by barrystokman** [comment]
forgot one `analysis_api` -> `microsalt_analysis_api` change in PR https://github.com/Clinical-Genomics/cg/pull/813

**Review by Mropat — APPROVED** [review]
👍

**Comment by barrystokman** [comment]
Bumped:
image
Deployed:
image

**Pull request merged**
