### PR TITLE
Fix fastq tag assignment from spring file

### LINKED ISSUE #2709: Spring file tags not being passed correctly to fastq files upon decompression
## Description

In #2473 the tags from the spring file were passed to the fastq files upon decompression. This approach assumes that all spring files for a sample have the same flow cell, so it picks up the first spring file of a sample bundle and uses its tags for all the fastq files for that sample.

## Suggested solution

Modify the function `cg/meta/compress/compress.py:get_fastq_tag_names` so that it picks the correct spring file to inherit the tags, not the first one.

## This can be closed when

New decompressions of spring files inherit the correct tags to fastq files

## Blocked by
*N/A*

### PR DESCRIPTION
**Pull request by diitaz93**
## Description

Closes #2709. To get the correct fastq file tags, this PR fetches the spring file by path, instead of fetching the first file that matched the sample bundle and the tag `spring` as it was done previously.

### Added
- Function `get_file_insensitive_path` to `MockHousekeeperAPI`

### Changed

- The function `cg/meta/compress/compress.py:get_fastq_tag_names` now receives for parameter a spring file path instead of a sample id. The spring file is fetched by the path given as parameter.
- The function `cg/meta/compress/compress.py:add_fastq_hk` receives an additional parameter `fastq_tags`, which is generated using the function `get_fastq_tag_names`.

### Fixed

- The tests of the modified functions
- Function `get_file_insensitive_path` of housekeeper API

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b 2709-fix-fastq-tags -a
    ```

### How to test

- [x] Choose a sample with wrong tags
- [x] Remove a pair of fastq files from Housekeeper (but not from hasta)
- [x] Verify that the removed files no longer appear when running
```shell
housekeeper get bundle -v <sample_id>
```
- [x] Run
```shell
cg -l DEBUG store sample <sample_id>
```

### Expected test outcome

- [x] Check The files are included to housekeeper with the correct tags
- [x] Verify that the files are added back to the database
```shell
housekeeper get bundle -v <sample_id>
```

## Review

- [x] Tests executed by SD
- [x] "Merge and deploy" approved by IO, HS
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Deploy this branch on 
  - [ ] cg stage
  - [ ] cg production

### CODE REVIEW

**Review by islean — APPROVED** [review]
Looks beautiful!

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by diitaz93** [comment]
## Test on stage
```shell
Check if SPRING metadata file <> exists
Check if SPRING metadata file exists
Fetch SPRING metadata from <>
SPRING decompression is done for run HCTCNDSXY_215172_S114_L003
Adding decompressed FASTQ files to Housekeeper for sample <>
Fetching file with path <>
Fetching file with path <>.spring
Adds <>fastq.gz, <>.fastq.gz to bundle <> with tags ['HCTCNDSXY', '<>', <SequencingFileTag.FASTQ: 'fastq'>]
Updating files in Housekeeper...
Fetch latest version from bundle <>
Fetching tag with name: HCTCNDSXY
Fetching tag with name: ACC7204A2
Fetching tag with name: fastq
Fetching tag with name: HCTCNDSXY
Fetching tag with name: <>
Fetching tag with name: fastq
Created new bundle version dir: /home/proj/stage/housekeeper-bundles/<>/2020-10-26
Another file with identical included file path: /home/proj/stage/housekeeper-bundles/<>/2020-10-26/HCTCNDSXY_215172_S114_L003_R1_001.fastq.gz already exist. Skip linking of: /home/proj/stage/housekeeper-bundles/<>/2020-10-26/HCTCNDSXY_215172_S114_L003_R1_001.fastq.gz
Fetch latest version from bundle <>
Fetching tag with name: HCTCNDSXY
Fetching tag with name: <>
Fetching tag with name: fastq
Fetching tag with name: HCTCNDSXY
Fetching tag with name: <>
Fetching tag with name: fastq
Created new bundle version dir: /home/proj/stage/housekeeper-bundles/<>/2020-10-26
Another file with identical included file path: /home/proj/stage/housekeeper-bundles/<>/2020-10-26/HCTCNDSXY_215172_S114_L003_R2_001.fastq.gz already exist. Skip linking of: /home/proj/stage/housekeeper-bundles/<>/2020-10-26/HCTCNDSXY_215172_S114_L003_R2_001.fastq.gz
Stored fastq files for <>

```

**Comment by diitaz93** [comment]
## Deployed to stage:
```shell
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 53.1.5
2d [js.diazboada@hasta:~] [S_base] 3m30s $ up
```
## Deployed to production:
```shell
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/js.diazboada
done.
Log deploy... done.
cg, version 53.1.5
2d [js.diazboada@hasta:~] [P_base] 2m39s $
```

**Pull request merged**
