### PR TITLE
feat - include index settings in sample sheet header

### PR DESCRIPTION
**Pull request by diitaz93**
## Description
Part of #2930. 
We need to implement a new validation for sample sheets that checks if the override cycles are correct. As in many cases we don't have the run parameters file to check the correct configuration of the cycles, this PR adds a field to the v2 sample sheet with the index settings used. This is enough to determine the correct override cycles for each sample.
Note: the validation will be done in another PR

### Added

- A new entry to the Header section of the sample sheet with the name of the index settings used

### How to prepare for test

- [x] Ssh to relevant server (depending on type of change)
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b add-index-settings-samplehseet -a
    ```

### How to test

- [x] Generate new v2 sample sheets for the 7 test flow cells
- [x] start the demultiplexing on dragen through cg

### Expected test outcome

- [x] The sample sheet looks correct
- [x] The demultiplexing finishes without any error in the logs

## Review

- [x] Tests executed by SD
- [x] "Merge and deploy" approved by KN
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [x] Deploy this branch on 
  - [x] cg stage
  - [x] cg production

### CODE REVIEW

**Comment by diitaz93** [comment]
## Tests on stage
- Sample sheet created successfully without errors

**Review by karlnyr — APPROVED** [review]
Cool 👍

**Comment by diitaz93** [comment]
## Tests on stage
Demultiplex finished successfully

**Comment by diitaz93** [comment]
## Deployed to stage and production
```shell
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/proj/stage/sequencing_data/illumina/flow_cells
done.
Log deploy... done.
cg, version 58.1.5
```

**Pull request merged**
