### PR TITLE
WIP: Avoid generating new hk file for cg store balsamic

### PR DESCRIPTION
**Pull request by hassanfa**
This PR fixes the problem with `cg workflow balsamic store`  where it tries to generate new housekeeper files and it fails.

**How to prepare for test**:
- [ ] ssh to hasta
- [ ] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [ ] login to hasta
- [ ] do `cg workflow store balsamic`

**Expected test outcome**:
- [ ] check that above command works
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [X] code approved by @barrystokman 
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by hassanfa** [comment]
@Mropat could you review this one, it is just 2 lines.

**Comment by moonso** [comment]
Did you perform the tests?

**Comment by Mropat** [comment]
This is good as a quick patch to stop the excessive logs. But we still need to implement a more permanent solution soon!

**Comment by Mropat** [comment]
`cg workflow balsamic store` has been reworked and this is no longer applies

**Pull request closed without merging**
