### PR TITLE
Add function to get case-samples from sample internal id

### PR DESCRIPTION
**Pull request by diitaz93**
## Description

Create a function that replaces a previously deleted function with similar functionality.

### Added

- function `get_case_samples_from_sample_internal_id` in `cg/store/api/find_business_data.py`.

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [x] **MINOR** - when you add functionality in a backwards compatible manner

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by beatrizsavinhas** [comment]
# Testing

### Installing branch in stage

```
bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b new-func-cases-by-sample -a
```

### Python script for testing

```
~/BSV_data_processing/get_case_samples_from_sample_internal_id.py
```

### Output
Sample with 2 cases

```
12d [hiseq.clinical@hasta:~/BSV_data_processing] [S_main] 6s $ python get_case_samples_from_sample_internal_id.py sample_id
case1 | sample_id
case2 | sample_id
```

**Comment by beatrizsavinhas** [comment]
Seems to be working great! Thanks @diitaz93 🎉

**Review by beatrizsavinhas — APPROVED** [review]
Seems to be working great! Thanks @diitaz93 🎉

**Comment by diitaz93** [comment]
Closed because this branch was no longer needed. The problem was solved somewhere else.

**Pull request closed without merging**
