### PR TITLE
Rm deprecated sequncers

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

The Miseq never made it production and we never had any Nextseqs. This PR removes them.

### Changed

- Rm deprecated sequncers: Miseq and Nextseq

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by karlnyr — APPROVED** [review]
Nice! I am quite certain that we do have some 2500 flow cells with data - however, we would not handle those inside of CG today - and for now those flow cells are handled inside the `demultiplexing` repo isntead.

**Review by diitaz93 — APPROVED** [review]
This was needed 💯

**Comment by henrikstranneheim** [comment]
@diitaz93 @karlnyr Do you want use this PR as a base to remove flow cell mode or shall I close it?

**Comment by diitaz93** [comment]
> @diitaz93 @karlnyr Do you want use this PR as a base to remove flow cell mode or shall I close it?

You can close it

**Pull request closed without merging**
