### PR TITLE
Lists organisms by internal_id in the Orderportal

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR lists the organisms in the order portal in alphabetical order

How to test:
0. install on stage (add instructions on how to as needed)

1. login to order portal
1. create an Microbial order
1. add sample
1. open Organism drop down

Expected outcome:
The organisms should be listed in alphabetical order

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@ingkebil could you review this PR again, I had to refactor it to make it pass the linting

**Comment by ingkebil** [comment]
Why was the `FindHandler` class split up again?

**Comment by ingkebil** [comment]
Can we find functional splits for that code so we might have an advantage of splitting it up, e.g.:
- customer, sample, family, app tag (more customer related)
- analysis, flowcell, panel (analysis related)
- invoicing, delivery (post analysis related)

Something like that? What do you think?

**Comment by patrikgrenfeldt** [comment]
@ingkebil what are your thoughts about the new separation of the FindHandler into FindBasicDataHandler and FindBusinessDataHandler?

The FindBasicDataHandler is intended for data that lives on over time and is used by data handled in the FindBusinessDataHandler. FindBusinessDataHandler is for data that is created mainly by customers.

**Comment by ingkebil** [comment]
Sounds solid! :solomon_islands:

**Pull request merged**
