### PR TITLE
Add sample name validation for microbial fastq

### PR DESCRIPTION
**Pull request by islean**
## Description

This PR suggests that we disallow any orders reusing sample names within microbial fastq. 

### Added

-

### Changed

- Microbial fastq orders containing samples which the customer has used in a previous order do not pass validation.

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_cg -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
Looks good. We should consider splitting these order types though and treat each as their own instead of solving this with if statements. I think we would gain a bit more clarity that way.

**Review by diitaz93 — APPROVED** [review]
looks good 👍

**Comment by islean** [comment]
Tested in stage:

image

**Comment by islean** [comment]
Deployed to the VMs

**Pull request merged**
