### PR TITLE
Add validation cases to skip compression

### PR DESCRIPTION
**Pull request by fevac**
## Description

Fixes https://github.com/Clinical-Genomics/cg/issues/1855
Fixes https://github.com/Clinical-Genomics/cg/issues/1971

### Added

- Balsamic WES validation cases
- RNAfusion validation cases

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by fevac** [comment]
@ivadym @mathiasbio any other case we need to add?

**Comment by ivadym** [comment]
In the issue you mention a TN-WES case, should I check if we have one available or you did it already?

**Comment by fevac** [comment]
> In the issue you mention a TN-WES case, should I check if we have one available or you did it already?

I didn't find any

**Comment by ivadym** [comment]
I found a few, but we need to know which samples of which customers  we can use:

https://docs.google.com/spreadsheets/d/1XeepO390huwMTPFnzfxZ0YUVwOqLUfh_5vrR0HQ0vmY/edit#gid=0

**Comment by vwirta** [comment]
@ivadym I think the cust052 samples in your list are not exome samples but TGA using the GMS Myeloid panel.

TN cases:
Regarding samples from cust009, cust082, cust096 - I do not think we should include these samples in the validation data set as they are from different research projects.  The cust127 sample is however interesting, because it is a ped cancer pat and has been sequenced with high depth (like we would do for exome for a cancer case).

TO cases:
Also here, we should not include samples from cust082, cust091, cust096 (various research projects).
Also probably good to avoid are various internal customers: cust000, cust900
Good candidate customer numbers would be: cust002, cust087 (surprised they have exomes) and cust127

**Comment by fevac** [comment]
Just took two cases considering all mentioned before. Adding  `properpigeon` as TN and `rightthrush` as TO

**Review by ivadym — APPROVED** [review]
⭐

**Review by mathiasbio — APPROVED** [review]
Nice! :) One step closer to being able to do smaller and faster releases! 🥳

**Pull request merged**
